modLoader = "javafml" #mandatory
loaderVersion = "[37,38)" #mandatory This is typically bumped every Minecraft version by Forge. See https://files.minecraftforge.net/ for a list of versions.
license = "MIT" # Review your options at https://choosealicense.com/.
issueTrackerURL = "https://github.com/sa-shiro/Minecraft-Compressed-Blocks/issues" #optional

[[mods]] #mandatory
modId = "compressedblocks" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "Compressed Blocks" #mandatory
updateJSONURL = "https://raw.githubusercontent.com/sa-shiro/Minecraft-Compressed-Blocks/master/update.json" #optional
displayURL = "https://www.curseforge.com/minecraft/mc-mods/cb-compressed-blocks" #optional
logoFile = "pack.png" #optional
authors = "sashiro" #optional
description = '''
CB: Compressed Blocks\nA Block Compression and Crate mod to organize your storage.
'''

[[dependencies.compressedblocks]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[37,38)" #mandatory
ordering = "NONE" # The order that this dependency should load in relation to your mod, required to be either 'BEFORE' or 'AFTER' if the dependency is not mandatory
side = "BOTH" # Side this dependency is applied on - 'BOTH', 'CLIENT' or 'SERVER'

[[dependencies.compressedblocks]]
modId = "minecraft"
mandatory = true
versionRange = "[1.17,1.18)"
ordering = "NONE"
side = "BOTH"