modLoader = "javafml" #mandatory
loaderVersion = "${loader_version_range}" #mandatory This is typically bumped every Minecraft version by Forge. See https://files.minecraftforge.net/ for a list of versions.
license = "${mod_license}" # Review your options at https://choosealicense.com/.
issueTrackerURL = "${source}/issues" #optional

[[mods]] #mandatory
    modId = "${mod_id}" #mandatory
    version = "${version}" #mandatory
    displayName = "${mod_name}" #mandatory
    updateJSONURL = "${update_url}" #optional (see https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/)
    displayURL = "${curseforge_page}" #optional (displayed in the mod UI)
    logoFile = "${logo_file}" #optional (needs to be in the root of your mod jar (root of your 'resources' folder))
    authors = "${mod_author}" #optional
    description = '''${mod_description}''' #mandatory (Supports multiline text)

[[dependencies.${mod_id}]] #optional
    modId = "forge" #mandatory
    mandatory = true #mandatory
    versionRange = "${forge_version_range}" #mandatory
    ordering = "NONE" # The order that this dependency should load in relation to your mod, required to be either 'BEFORE' or 'AFTER' if the dependency is not mandatory
    side = "BOTH" # Side this dependency is applied on - 'BOTH', 'CLIENT' or 'SERVER'

[[dependencies.${mod_id}]]
    modId = "minecraft"
    mandatory = true
    versionRange = "${forge_mc_version_range}"
    ordering = "NONE"
    side = "BOTH"