plugins {
    id 'multiloader-loader'
    id 'fabric-loom' version '1.6-SNAPSHOT'
}
repositories {
    maven {
        name = "Terraformers"
        url = "https://maven.terraformersmc.com/"
    }
}
dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    //modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"

    // Forge Config API Port - Fabric
    modApi "fuzs.forgeconfigapiport:forgeconfigapiport-fabric:${forgeconfigapi_version}"

    // Prior to Minecraft 26.x, use "modImplementation" instead
    modImplementation("com.terraformersmc:modmenu:${project.modmenu_version}")
}

loom {
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}

fabricApi {
    configureDataGeneration()
}