NAMES=(stone granite diorite andesite dirt cobblestone sandstone red_sandstone bricks netherrack glowstone stone_bricks nether_bricks end_stone coal_block lapis_block gold_block iron_block diamond_block emerald_block redstone_block sand red_sand gravel soul_sand obsidian)

cd src/main/resources/assets/compressedblocks/blockstates/ || exit

for i in "${NAMES[@]}"
do
  printf "{\"variants\": {\"\": {\"model\":\"compressedblocks:block/c0_$i\"}}}" > c0_"$i".json
  printf "{\"variants\": {\"\": {\"model\":\"compressedblocks:block/c1_$i\"}}}" > c1_"$i".json
  printf "{\"variants\": {\"\": {\"model\":\"compressedblocks:block/c2_$i\"}}}" > c2_"$i".json
  printf "{\"variants\": {\"\": {\"model\":\"compressedblocks:block/c3_$i\"}}}" > c3_"$i".json
  printf "{\"variants\": {\"\": {\"model\":\"compressedblocks:block/c4_$i\"}}}" > c4_"$i".json
  printf "{\"variants\": {\"\": {\"model\":\"compressedblocks:block/c5_$i\"}}}" > c5_"$i".json
  printf "{\"variants\": {\"\": {\"model\":\"compressedblocks:block/c6_$i\"}}}" > c6_"$i".json
  printf "{\"variants\": {\"\": {\"model\":\"compressedblocks:block/c7_$i\"}}}" > c7_"$i".json
  printf "{\"variants\": {\"\": {\"model\":\"compressedblocks:block/c8_$i\"}}}" > c8_"$i".json
  printf "{\"variants\": {\"\": {\"model\":\"compressedblocks:block/c9_$i\"}}}" > c9_"$i".json
done

  cd ../models/block/ || exit
for i in "${NAMES[@]}"
do
  printf "{\"parent\":\"block/block\",\"textures\":{\"particle\":\"minecraft:block/$i\",\"sides\":\"minecraft:block/$i\",\"overlay\":\"compressedblocks:block/compression_level_0\"},\"elements\":[{\"from\":[0,0,0],\"to\":[16,16,16],\"faces\":{\"down\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"},\"up\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"},\"north\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"},\"south\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"},\"west\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"},\"east\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"}}},{\"from\":[0,0,0],\"to\":[16,16,16],\"faces\":{\"up\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"},\"down\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"},\"north\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"},\"south\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"},\"west\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"},\"east\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"}}}]}" > c0_"$i".json
  printf "{\"parent\":\"block/block\",\"textures\":{\"particle\":\"minecraft:block/$i\",\"sides\":\"minecraft:block/$i\",\"overlay\":\"compressedblocks:block/compression_level_1\"},\"elements\":[{\"from\":[0,0,0],\"to\":[16,16,16],\"faces\":{\"down\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"},\"up\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"},\"north\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"},\"south\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"},\"west\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"},\"east\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"}}},{\"from\":[0,0,0],\"to\":[16,16,16],\"faces\":{\"up\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"},\"down\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"},\"north\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"},\"south\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"},\"west\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"},\"east\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"}}}]}" > c1_"$i".json
  printf "{\"parent\":\"block/block\",\"textures\":{\"particle\":\"minecraft:block/$i\",\"sides\":\"minecraft:block/$i\",\"overlay\":\"compressedblocks:block/compression_level_2\"},\"elements\":[{\"from\":[0,0,0],\"to\":[16,16,16],\"faces\":{\"down\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"},\"up\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"},\"north\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"},\"south\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"},\"west\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"},\"east\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"}}},{\"from\":[0,0,0],\"to\":[16,16,16],\"faces\":{\"up\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"},\"down\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"},\"north\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"},\"south\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"},\"west\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"},\"east\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"}}}]}" > c2_"$i".json
  printf "{\"parent\":\"block/block\",\"textures\":{\"particle\":\"minecraft:block/$i\",\"sides\":\"minecraft:block/$i\",\"overlay\":\"compressedblocks:block/compression_level_3\"},\"elements\":[{\"from\":[0,0,0],\"to\":[16,16,16],\"faces\":{\"down\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"},\"up\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"},\"north\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"},\"south\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"},\"west\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"},\"east\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"}}},{\"from\":[0,0,0],\"to\":[16,16,16],\"faces\":{\"up\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"},\"down\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"},\"north\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"},\"south\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"},\"west\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"},\"east\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"}}}]}" > c3_"$i".json
  printf "{\"parent\":\"block/block\",\"textures\":{\"particle\":\"minecraft:block/$i\",\"sides\":\"minecraft:block/$i\",\"overlay\":\"compressedblocks:block/compression_level_4\"},\"elements\":[{\"from\":[0,0,0],\"to\":[16,16,16],\"faces\":{\"down\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"},\"up\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"},\"north\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"},\"south\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"},\"west\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"},\"east\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"}}},{\"from\":[0,0,0],\"to\":[16,16,16],\"faces\":{\"up\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"},\"down\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"},\"north\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"},\"south\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"},\"west\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"},\"east\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"}}}]}" > c4_"$i".json
  printf "{\"parent\":\"block/block\",\"textures\":{\"particle\":\"minecraft:block/$i\",\"sides\":\"minecraft:block/$i\",\"overlay\":\"compressedblocks:block/compression_level_5\"},\"elements\":[{\"from\":[0,0,0],\"to\":[16,16,16],\"faces\":{\"down\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"},\"up\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"},\"north\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"},\"south\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"},\"west\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"},\"east\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"}}},{\"from\":[0,0,0],\"to\":[16,16,16],\"faces\":{\"up\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"},\"down\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"},\"north\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"},\"south\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"},\"west\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"},\"east\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"}}}]}" > c5_"$i".json
  printf "{\"parent\":\"block/block\",\"textures\":{\"particle\":\"minecraft:block/$i\",\"sides\":\"minecraft:block/$i\",\"overlay\":\"compressedblocks:block/compression_level_6\"},\"elements\":[{\"from\":[0,0,0],\"to\":[16,16,16],\"faces\":{\"down\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"},\"up\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"},\"north\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"},\"south\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"},\"west\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"},\"east\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"}}},{\"from\":[0,0,0],\"to\":[16,16,16],\"faces\":{\"up\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"},\"down\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"},\"north\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"},\"south\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"},\"west\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"},\"east\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"}}}]}" > c6_"$i".json
  printf "{\"parent\":\"block/block\",\"textures\":{\"particle\":\"minecraft:block/$i\",\"sides\":\"minecraft:block/$i\",\"overlay\":\"compressedblocks:block/compression_level_7\"},\"elements\":[{\"from\":[0,0,0],\"to\":[16,16,16],\"faces\":{\"down\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"},\"up\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"},\"north\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"},\"south\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"},\"west\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"},\"east\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"}}},{\"from\":[0,0,0],\"to\":[16,16,16],\"faces\":{\"up\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"},\"down\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"},\"north\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"},\"south\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"},\"west\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"},\"east\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"}}}]}" > c7_"$i".json
  printf "{\"parent\":\"block/block\",\"textures\":{\"particle\":\"minecraft:block/$i\",\"sides\":\"minecraft:block/$i\",\"overlay\":\"compressedblocks:block/compression_level_8\"},\"elements\":[{\"from\":[0,0,0],\"to\":[16,16,16],\"faces\":{\"down\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"},\"up\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"},\"north\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"},\"south\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"},\"west\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"},\"east\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"}}},{\"from\":[0,0,0],\"to\":[16,16,16],\"faces\":{\"up\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"},\"down\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"},\"north\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"},\"south\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"},\"west\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"},\"east\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"}}}]}" > c8_"$i".json
  printf "{\"parent\":\"block/block\",\"textures\":{\"particle\":\"minecraft:block/$i\",\"sides\":\"minecraft:block/$i\",\"overlay\":\"compressedblocks:block/compression_level_9\"},\"elements\":[{\"from\":[0,0,0],\"to\":[16,16,16],\"faces\":{\"down\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"},\"up\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"},\"north\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"},\"south\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"},\"west\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"},\"east\":{\"uv\":[0,0,16,16],\"texture\":\"#sides\"}}},{\"from\":[0,0,0],\"to\":[16,16,16],\"faces\":{\"up\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"},\"down\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"},\"north\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"},\"south\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"},\"west\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"},\"east\":{\"uv\":[0,0,16,16],\"texture\":\"#overlay\"}}}]}" > c9_"$i".json
done

  cd ../item || exit
for i in "${NAMES[@]}"
do
  printf "{\"parent\": \"compressedblocks:block/c0_$i\"}" > c0_"$i".json
  printf "{\"parent\": \"compressedblocks:block/c1_$i\"}" > c1_"$i".json
  printf "{\"parent\": \"compressedblocks:block/c2_$i\"}" > c2_"$i".json
  printf "{\"parent\": \"compressedblocks:block/c3_$i\"}" > c3_"$i".json
  printf "{\"parent\": \"compressedblocks:block/c4_$i\"}" > c4_"$i".json
  printf "{\"parent\": \"compressedblocks:block/c5_$i\"}" > c5_"$i".json
  printf "{\"parent\": \"compressedblocks:block/c6_$i\"}" > c6_"$i".json
  printf "{\"parent\": \"compressedblocks:block/c7_$i\"}" > c7_"$i".json
  printf "{\"parent\": \"compressedblocks:block/c8_$i\"}" > c8_"$i".json
  printf "{\"parent\": \"compressedblocks:block/c9_$i\"}" > c9_"$i".json
done

  cd ../../../../data/compressedblocks/loot_tables/blocks || exit

for i in "${NAMES[@]}"
do
  printf "{\"type\": \"minecraft:block\", \"pools\": [{\"rolls\": 1, \"entries\": [{\"type\": \"minecraft:item\", \"name\": \"compressedblocks:c0_$i\"}], \"conditions\": [{\"condition\": \"minecraft:survives_explosion\"}]}]}" > c0_"$i".json
  printf "{\"type\": \"minecraft:block\", \"pools\": [{\"rolls\": 1, \"entries\": [{\"type\": \"minecraft:item\", \"name\": \"compressedblocks:c1_$i\"}], \"conditions\": [{\"condition\": \"minecraft:survives_explosion\"}]}]}" > c1_"$i".json
  printf "{\"type\": \"minecraft:block\", \"pools\": [{\"rolls\": 1, \"entries\": [{\"type\": \"minecraft:item\", \"name\": \"compressedblocks:c2_$i\"}], \"conditions\": [{\"condition\": \"minecraft:survives_explosion\"}]}]}" > c2_"$i".json
  printf "{\"type\": \"minecraft:block\", \"pools\": [{\"rolls\": 1, \"entries\": [{\"type\": \"minecraft:item\", \"name\": \"compressedblocks:c3_$i\"}], \"conditions\": [{\"condition\": \"minecraft:survives_explosion\"}]}]}" > c3_"$i".json
  printf "{\"type\": \"minecraft:block\", \"pools\": [{\"rolls\": 1, \"entries\": [{\"type\": \"minecraft:item\", \"name\": \"compressedblocks:c4_$i\"}], \"conditions\": [{\"condition\": \"minecraft:survives_explosion\"}]}]}" > c4_"$i".json
  printf "{\"type\": \"minecraft:block\", \"pools\": [{\"rolls\": 1, \"entries\": [{\"type\": \"minecraft:item\", \"name\": \"compressedblocks:c5_$i\"}], \"conditions\": [{\"condition\": \"minecraft:survives_explosion\"}]}]}" > c5_"$i".json
  printf "{\"type\": \"minecraft:block\", \"pools\": [{\"rolls\": 1, \"entries\": [{\"type\": \"minecraft:item\", \"name\": \"compressedblocks:c6_$i\"}], \"conditions\": [{\"condition\": \"minecraft:survives_explosion\"}]}]}" > c6_"$i".json
  printf "{\"type\": \"minecraft:block\", \"pools\": [{\"rolls\": 1, \"entries\": [{\"type\": \"minecraft:item\", \"name\": \"compressedblocks:c7_$i\"}], \"conditions\": [{\"condition\": \"minecraft:survives_explosion\"}]}]}" > c7_"$i".json
  printf "{\"type\": \"minecraft:block\", \"pools\": [{\"rolls\": 1, \"entries\": [{\"type\": \"minecraft:item\", \"name\": \"compressedblocks:c8_$i\"}], \"conditions\": [{\"condition\": \"minecraft:survives_explosion\"}]}]}" > c8_"$i".json
  printf "{\"type\": \"minecraft:block\", \"pools\": [{\"rolls\": 1, \"entries\": [{\"type\": \"minecraft:item\", \"name\": \"compressedblocks:c9_$i\"}], \"conditions\": [{\"condition\": \"minecraft:survives_explosion\"}]}]}" > c9_"$i".json
done

  cd ../../recipes || exit

for i in "${NAMES[@]}"
do
  printf "{\"type\": \"minecraft:crafting_shapeless\", \"ingredients\": [{\"item\": \"compressedblocks:c0_$i\"}], \"result\": {\"item\": \"minecraft:$i\", \"count\": 9}}" > shapeless_c0_"$i".json
  printf "{\"type\": \"minecraft:crafting_shapeless\", \"ingredients\": [{\"item\": \"compressedblocks:c1_$i\"}], \"result\": {\"item\": \"compressedblocks:c0_$i\", \"count\": 9}}" > shapeless_c1_"$i".json
  printf "{\"type\": \"minecraft:crafting_shapeless\", \"ingredients\": [{\"item\": \"compressedblocks:c2_$i\"}], \"result\": {\"item\": \"compressedblocks:c1_$i\", \"count\": 9}}" > shapeless_c2_"$i".json
  printf "{\"type\": \"minecraft:crafting_shapeless\", \"ingredients\": [{\"item\": \"compressedblocks:c3_$i\"}], \"result\": {\"item\": \"compressedblocks:c2_$i\", \"count\": 9}}" > shapeless_c3_"$i".json
  printf "{\"type\": \"minecraft:crafting_shapeless\", \"ingredients\": [{\"item\": \"compressedblocks:c4_$i\"}], \"result\": {\"item\": \"compressedblocks:c3_$i\", \"count\": 9}}" > shapeless_c4_"$i".json
  printf "{\"type\": \"minecraft:crafting_shapeless\", \"ingredients\": [{\"item\": \"compressedblocks:c5_$i\"}], \"result\": {\"item\": \"compressedblocks:c4_$i\", \"count\": 9}}" > shapeless_c5_"$i".json
  printf "{\"type\": \"minecraft:crafting_shapeless\", \"ingredients\": [{\"item\": \"compressedblocks:c6_$i\"}], \"result\": {\"item\": \"compressedblocks:c5_$i\", \"count\": 9}}" > shapeless_c6_"$i".json
  printf "{\"type\": \"minecraft:crafting_shapeless\", \"ingredients\": [{\"item\": \"compressedblocks:c7_$i\"}], \"result\": {\"item\": \"compressedblocks:c6_$i\", \"count\": 9}}" > shapeless_c7_"$i".json
  printf "{\"type\": \"minecraft:crafting_shapeless\", \"ingredients\": [{\"item\": \"compressedblocks:c8_$i\"}], \"result\": {\"item\": \"compressedblocks:c7_$i\", \"count\": 9}}" > shapeless_c8_"$i".json
  printf "{\"type\": \"minecraft:crafting_shapeless\", \"ingredients\": [{\"item\": \"compressedblocks:c9_$i\"}], \"result\": {\"item\": \"compressedblocks:c8_$i\", \"count\": 9}}" > shapeless_c9_"$i".json

  printf "{\"type\": \"minecraft:crafting_shaped\", \"pattern\": [\"AAA\", \"AAA\", \"AAA\"], \"key\": {\"A\": {\"item\": \"minecraft:$i\"}}, \"result\": {\"item\": \"compressedblocks:c0_$i\"}}" > shaped_c0_"$i".json
  printf "{\"type\": \"minecraft:crafting_shaped\", \"pattern\": [\"AAA\", \"AAA\", \"AAA\"], \"key\": {\"A\": {\"item\": \"compressedblocks:c0_$i\"}}, \"result\": {\"item\": \"compressedblocks:c1_$i\"}}" > shaped_c1_"$i".json
  printf "{\"type\": \"minecraft:crafting_shaped\", \"pattern\": [\"AAA\", \"AAA\", \"AAA\"], \"key\": {\"A\": {\"item\": \"compressedblocks:c1_$i\"}}, \"result\": {\"item\": \"compressedblocks:c2_$i\"}}" > shaped_c2_"$i".json
  printf "{\"type\": \"minecraft:crafting_shaped\", \"pattern\": [\"AAA\", \"AAA\", \"AAA\"], \"key\": {\"A\": {\"item\": \"compressedblocks:c2_$i\"}}, \"result\": {\"item\": \"compressedblocks:c3_$i\"}}" > shaped_c3_"$i".json
  printf "{\"type\": \"minecraft:crafting_shaped\", \"pattern\": [\"AAA\", \"AAA\", \"AAA\"], \"key\": {\"A\": {\"item\": \"compressedblocks:c3_$i\"}}, \"result\": {\"item\": \"compressedblocks:c4_$i\"}}" > shaped_c4_"$i".json
  printf "{\"type\": \"minecraft:crafting_shaped\", \"pattern\": [\"AAA\", \"AAA\", \"AAA\"], \"key\": {\"A\": {\"item\": \"compressedblocks:c4_$i\"}}, \"result\": {\"item\": \"compressedblocks:c5_$i\"}}" > shaped_c5_"$i".json
  printf "{\"type\": \"minecraft:crafting_shaped\", \"pattern\": [\"AAA\", \"AAA\", \"AAA\"], \"key\": {\"A\": {\"item\": \"compressedblocks:c5_$i\"}}, \"result\": {\"item\": \"compressedblocks:c6_$i\"}}" > shaped_c6_"$i".json
  printf "{\"type\": \"minecraft:crafting_shaped\", \"pattern\": [\"AAA\", \"AAA\", \"AAA\"], \"key\": {\"A\": {\"item\": \"compressedblocks:c6_$i\"}}, \"result\": {\"item\": \"compressedblocks:c7_$i\"}}" > shaped_c7_"$i".json
  printf "{\"type\": \"minecraft:crafting_shaped\", \"pattern\": [\"AAA\", \"AAA\", \"AAA\"], \"key\": {\"A\": {\"item\": \"compressedblocks:c7_$i\"}}, \"result\": {\"item\": \"compressedblocks:c8_$i\"}}" > shaped_c8_"$i".json
  printf "{\"type\": \"minecraft:crafting_shaped\", \"pattern\": [\"AAA\", \"AAA\", \"AAA\"], \"key\": {\"A\": {\"item\": \"compressedblocks:c8_$i\"}}, \"result\": {\"item\": \"compressedblocks:c9_$i\"}}" > shaped_c9_"$i".json
done