# suppress inspection "SpellCheckingInspection" for whole file

# ============================================================
# Project
# ============================================================

version=3.0.0-1.20.1
group=net.sashiro.compressedblocks

# ============================================================
# Mod
# ============================================================

mod_name=Compressed Blocks
mod_author=sashiro
mod_id=compressedblocks
mod_license=MIT
mod_author_email=contact@sashiro.net
mod_description=CB: Compressed Blocks\nA Block Compression and Crate mod to organize your storage.

logo_file=pack.png

version_type=release

# ============================================================
# Minecraft
# ============================================================

java_version=17
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.20.3)

# This is the version of Minecraft that the 'common' project uses.
# NeoForm versions:
# https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.20.1-20230612.114412

# ============================================================
# Mappings
# ============================================================

mappings_version=1.20.1

# ParchmentMC version:
# https://parchmentmc.org/docs/getting-started#choose-a-version
parchment_minecraft=1.20.1
parchment_version=2023.09.03

# ============================================================
# Forge:
# https://files.minecraftforge.net/net/minecraftforge/forge/
# ============================================================

forge_version=47.4.26
forge_loader_version_range=[0,)

# ============================================================
# NeoForge:
# https://neoforged.net/
# ============================================================

neoforge_version=47.1.106
neoforge_loader_version_range=[0,)

# ============================================================
# Fabric:
# https://fabricmc.net/develop/
# ============================================================

fabric_loader_version=0.19.5
fabric_mc_version_range=>=1.20
fabric_api_version=0.92.12+1.20.1

# ============================================================
# Configuration
# ============================================================

# Forge Config API Port:
# https://www.curseforge.com/minecraft/mc-mods/forge-config-api-port-fabric/files
forgeconfigapi_version=8.0.3

# Fabric Mod Menu:
# https://modrinth.com/mod/modmenu
modmenu_version=7.2.2

# ============================================================
# Distribution / Project Links
# ============================================================

curseforge_id=361354
modrinth_id=IQRVlbit

# Misc for mods.toml & fabric.mod.json
# curseforge_page is used in mods.toml
curseforge_page=https://www.curseforge.com/minecraft/mc-mods/cb-compressed-blocks
modrinth_page=https://modrinth.com/mod/cb-compressed-blocks
discord=https://discord.gg/EKyjXRH9xN
source=https://github.com/sa-shiro/Minecraft-Compressed-Blocks
update_url=https://raw.githubusercontent.com/sa-shiro/Minecraft-Compressed-Blocks/master/update.json
homepage=https://www.curseforge.com/minecraft/mc-mods/cb-compressed-blocks

# ============================================================
# Gradle
# ============================================================

org.gradle.jvmargs=-Xmx3G

org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.workers.max=24

org.gradle.caching=true

systemProp.http.socketTimeout=60000
systemProp.https.socketTimeout=60000