package net.sashiro.compressedblocks.block;

import net.minecraft.world.level.block.state.BlockBehaviour;

import static net.sashiro.compressedblocks.Constants.HARDNESS;
import static net.sashiro.compressedblocks.Constants.RESISTANCE;

public class BlockList {

    public static final CBBlock[] DIRT = createBlocks(0.925F);
    public static final CBBlock[] GRAVEL = createBlocks(0.925F);
    public static final CBBlock[] COBBLESTONE = createBlocks(null);
    public static final CBBlock[] STONE = createBlocks(null);
    public static final CBBlock[] GRANITE = createBlocks(null);
    public static final CBBlock[] DIORITE = createBlocks(null);
    public static final CBBlock[] ANDESITE = createBlocks(null);
    public static final CBBlock[] CRIMSON_NYLIUM = createBlocks(null);
    public static final CBBlock[] WARPED_NYLIUM = createBlocks(null);
    public static final CBBlock[] CLAY = createBlocks(0.925F);
    public static final CBBlock[] SAND = createBlocks(0.925F);
    public static final CBBlock[] RED_SAND = createBlocks(0.925F);
    public static final CBBlock[] SANDSTONE = createBlocks(null);
    public static final CBBlock[] RED_SANDSTONE = createBlocks(null);
    public static final CBBlock[] COAL_ORE = createBlocks(null);
    public static final CBBlock[] COPPER_ORE = createBlocks(null);
    public static final CBBlock[] IRON_ORE = createBlocks(null);
    public static final CBBlock[] GOLD_ORE = createBlocks(null);
    public static final CBBlock[] REDSTONE_ORE = createBlocks(null);
    public static final CBBlock[] EMERALD_ORE = createBlocks(null);
    public static final CBBlock[] LAPIS_ORE = createBlocks(null);
    public static final CBBlock[] DIAMOND_ORE = createBlocks(null);
    public static final CBBlock[] NETHER_GOLD_ORE = createBlocks(null);
    public static final CBBlock[] NETHER_QUARTZ_ORE = createBlocks(null);
    public static final CBBlock[] DEEPSLATE_COAL_ORE = createBlocks(null);
    public static final CBBlock[] DEEPSLATE_COPPER_ORE = createBlocks(null);
    public static final CBBlock[] DEEPSLATE_IRON_ORE = createBlocks(null);
    public static final CBBlock[] DEEPSLATE_GOLD_ORE = createBlocks(null);
    public static final CBBlock[] DEEPSLATE_REDSTONE_ORE = createBlocks(null);
    public static final CBBlock[] DEEPSLATE_EMERALD_ORE = createBlocks(null);
    public static final CBBlock[] DEEPSLATE_LAPIS_ORE = createBlocks(null);
    public static final CBBlock[] DEEPSLATE_DIAMOND_ORE = createBlocks(null);
    public static final CBBlock[] RAW_IRON_BLOCK = createBlocks(1.25F);
    public static final CBBlock[] RAW_COPPER_BLOCK = createBlocks(1.25F);
    public static final CBBlock[] RAW_GOLD_BLOCK = createBlocks(1.25F);
    public static final CBBlock[] IRON_BLOCK = createBlocks(1.5F);
    public static final CBBlock[] GOLD_BLOCK = createBlocks(1.5F);
    public static final CBBlock[] LAPIS_BLOCK = createBlocks(1.5F);
    public static final CBBlock[] REDSTONE_BLOCK = createBlocks(1.5F);
    public static final CBBlock[] EMERALD_BLOCK = createBlocks(1.5F);
    public static final CBBlock[] DIAMOND_BLOCK = createBlocks(2.0F);
    public static final CBBlock[] NETHERITE_BLOCK = createBlocks(2.5F);
    public static final CBBlock[] COAL_BLOCK = createBlocks(null);
    public static final CBBlock[] SLIME_BLOCK = createBlocks(0.925F);
    public static final CBBlock[] HONEY_BLOCK = createBlocks(0.925F);
    public static final CBBlock[] BRICKS = createBlocks(null);
    public static final CBBlock[] STONE_BRICKS = createBlocks(null);
    public static final CBBlock[] NETHERRACK = createBlocks(null);
    public static final CBBlock[] NETHER_BRICKS = createBlocks(null);
    public static final CBBlock[] RED_NETHER_BRICKS = createBlocks(null);
    public static final CBBlock[] NETHER_WART_BLOCK = createBlocks(null);
    public static final CBBlock[] SOUL_SAND = createBlocks(null);
    public static final CBBlock[] SOUL_SOIL = createBlocks(null);
    public static final CBBlock[] END_STONE = createBlocks(null);
    public static final CBBlock[] END_STONE_BRICKS = createBlocks(null);
    public static final CBBlock[] BLACKSTONE = createBlocks(null);
    public static final CBBlock[] DEEPSLATE = createBlocks(null);
    public static final CBBlock[] COBBLED_DEEPSLATE = createBlocks(null);
    public static final CBBlock[] TUFF = createBlocks(null);
    public static final CBRotationalBlock[] BASALT = createRotationalBlocks(null);
    public static final CBBlock[] OBSIDIAN = createBlocks(3.5F);
    public static final CBBlock[] MUD = createBlocks(0.8F);
    public static final CBRotationalBlock[] OAK_LOG = createRotationalBlocks(null);
    public static final CBRotationalBlock[] SPRUCE_LOG = createRotationalBlocks(null);
    public static final CBRotationalBlock[] BIRCH_LOG = createRotationalBlocks(null);
    public static final CBRotationalBlock[] JUNGLE_LOG = createRotationalBlocks(null);
    public static final CBRotationalBlock[] ACACIA_LOG = createRotationalBlocks(null);
    public static final CBRotationalBlock[] DARK_OAK_LOG = createRotationalBlocks(null);
    public static final CBRotationalBlock[] MANGROVE_LOG = createRotationalBlocks(null);
    public static final CBRotationalBlock[] CHERRY_LOG = createRotationalBlocks(null);
    public static final CBRotationalBlock[] STRIPPED_OAK_LOG = createRotationalBlocks(null);
    public static final CBRotationalBlock[] STRIPPED_SPRUCE_LOG = createRotationalBlocks(null);
    public static final CBRotationalBlock[] STRIPPED_BIRCH_LOG = createRotationalBlocks(null);
    public static final CBRotationalBlock[] STRIPPED_JUNGLE_LOG = createRotationalBlocks(null);
    public static final CBRotationalBlock[] STRIPPED_ACACIA_LOG = createRotationalBlocks(null);
    public static final CBRotationalBlock[] STRIPPED_DARK_OAK_LOG = createRotationalBlocks(null);
    public static final CBRotationalBlock[] STRIPPED_MANGROVE_LOG = createRotationalBlocks(null);
    public static final CBRotationalBlock[] STRIPPED_CHERRY_LOG = createRotationalBlocks(null);
    public static final CBRotationalBlock[] OAK_PLANKS = createRotationalBlocks(null);
    public static final CBRotationalBlock[] SPRUCE_PLANKS = createRotationalBlocks(null);
    public static final CBRotationalBlock[] BIRCH_PLANKS = createRotationalBlocks(null);
    public static final CBRotationalBlock[] JUNGLE_PLANKS = createRotationalBlocks(null);
    public static final CBRotationalBlock[] ACACIA_PLANKS = createRotationalBlocks(null);
    public static final CBRotationalBlock[] DARK_OAK_PLANKS = createRotationalBlocks(null);
    public static final CBRotationalBlock[] MANGROVE_PLANKS = createRotationalBlocks(null);
    public static final CBRotationalBlock[] CHERRY_PLANKS = createRotationalBlocks(null);
    public static final CBRotationalBlock[] BAMBOO_PLANKS = createRotationalBlocks(null);
    public static final CBRotationalBlock[] BAMBOO_MOSAIC = createRotationalBlocks(null);
    public static final CBBlock[] COPPER_BLOCK = createBlocks(1.5F);
    public static final CBBlock[] CUT_COPPER = createBlocks(1.75F);
    public static final CBBlock[] EXPOSED_COPPER = createBlocks(1.35F);
    public static final CBBlock[] EXPOSED_CUT_COPPER = createBlocks(1.35F);
    public static final CBBlock[] WEATHERED_COPPER = createBlocks(1.35F);
    public static final CBBlock[] WEATHERED_CUT_COPPER = createBlocks(1.35F);
    public static final CBBlock[] OXIDIZED_COPPER = createBlocks(1.35F);
    public static final CBBlock[] OXIDIZED_CUT_COPPER = createBlocks(1.35F);
    public static final CBBlock[] WAXED_COPPER_BLOCK = createBlocks(1.75F);
    public static final CBBlock[] WAXED_CUT_COPPER = createBlocks(1.75F);
    public static final CBBlock[] WAXED_EXPOSED_COPPER = createBlocks(1.75F);
    public static final CBBlock[] WAXED_EXPOSED_CUT_COPPER = createBlocks(1.75F);
    public static final CBBlock[] WAXED_WEATHERED_COPPER = createBlocks(1.75F);
    public static final CBBlock[] WAXED_WEATHERED_CUT_COPPER = createBlocks(1.75F);
    public static final CBBlock[] WAXED_OXIDIZED_COPPER = createBlocks(1.75F);
    public static final CBBlock[] WAXED_OXIDIZED_CUT_COPPER = createBlocks(1.75F);
    public static final CBRotationalBlock[] BONE_BLOCK = createRotationalBlocks(null);
    public static final CBRotationalBlock[] SCULK = createRotationalBlocks(null);
    public static final CBBlock[] SMOOTH_SANDSTONE = createBlocks(null);
    public static final CBBlock[] CUT_SANDSTONE = createBlocks(null);
    public static final CBBlock[] CHISELED_SANDSTONE = createBlocks(null);
    public static final CBBlock[] SMOOTH_RED_SANDSTONE = createBlocks(null);
    public static final CBBlock[] CUT_RED_SANDSTONE = createBlocks(null);
    public static final CBBlock[] CHISELED_RED_SANDSTONE = createBlocks(null);
    public static final CBRotationalBlock[] CRIMSON_STEM = createRotationalBlocks(null);
    public static final CBRotationalBlock[] WARPED_STEM = createRotationalBlocks(null);
    public static final CBBlock[] TNT = createBlocks(0.25F);
    public static final CBRotationalBlock[] BAMBOO_BLOCK = createRotationalBlocks(null);
    public static final CBRotationalBlock[] STRIPPED_BAMBOO_BLOCK = createRotationalBlocks(null);
    public static final CBRotationalBlock[] STRIPPED_CRIMSON_STEM = createRotationalBlocks(null);
    public static final CBBlock[] CRIMSON_PLANKS = createBlocks(null);
    public static final CBRotationalBlock[] STRIPPED_WARPED_STEM = createRotationalBlocks(null);
    public static final CBBlock[] WARPED_PLANKS = createBlocks(null);
    public static final CBBlock[] MOSSY_COBBLESTONE = createBlocks(null);
    public static final CBBlock[] MOSSY_STONE_BRICKS = createBlocks(null);
    public static final CBBlock[] CRACKED_STONE_BRICKS = createBlocks(null);
    public static final CBBlock[] CHISELED_STONE_BRICKS = createBlocks(null);
    public static final CBBlock[] POLISHED_GRANITE = createBlocks(null);
    public static final CBBlock[] POLISHED_DIORITE = createBlocks(null);
    public static final CBBlock[] POLISHED_ANDESITE = createBlocks(null);
    public static final CBBlock[] CHISELED_DEEPSLATE = createBlocks(null);
    public static final CBBlock[] POLISHED_DEEPSLATE = createBlocks(null);
    public static final CBBlock[] DEEPSLATE_BRICKS = createBlocks(null);
    public static final CBBlock[] CRACKED_DEEPSLATE_BRICKS = createBlocks(null);
    public static final CBBlock[] DEEPSLATE_TILES = createBlocks(null);
    public static final CBBlock[] CRACKED_DEEPSLATE_TILES = createBlocks(null);
    public static final CBBlock[] PACKED_MUD = createBlocks(null);
    public static final CBBlock[] MUD_BRICKS = createBlocks(null);
    public static final CBBlock[] PRISMARINE = createBlocks(null);
    public static final CBBlock[] PRISMARINE_BRICKS = createBlocks(null);
    public static final CBBlock[] DARK_PRISMARINE = createBlocks(null);
    public static final CBRotationalBlock[] QUARTZ_BLOCK = createRotationalBlocks(null);
    public static final CBBlock[] CHISELED_QUARTZ_BLOCK = createBlocks(null);
    public static final CBBlock[] QUARTZ_BRICKS = createBlocks(null);
    public static final CBRotationalBlock[] QUARTZ_PILLAR = createRotationalBlocks(null);
    public static final CBBlock[] SMOOTH_QUARTZ_BLOCK = createBlocks(null);
    public static final CBBlock[] AMETHYST_BLOCK = createBlocks(null);
    public static final CBBlock[] WHITE_WOOL = createBlocks(0.5F);
    public static final CBBlock[] LIGHT_GRAY_WOOL = createBlocks(0.5F);
    public static final CBBlock[] GRAY_WOOL = createBlocks(0.5F);
    public static final CBBlock[] BLACK_WOOL = createBlocks(0.5F);
    public static final CBBlock[] BROWN_WOOL = createBlocks(0.5F);
    public static final CBBlock[] RED_WOOL = createBlocks(0.5F);
    public static final CBBlock[] ORANGE_WOOL = createBlocks(0.5F);
    public static final CBBlock[] YELLOW_WOOL = createBlocks(0.5F);
    public static final CBBlock[] LIME_WOOL = createBlocks(0.5F);
    public static final CBBlock[] GREEN_WOOL = createBlocks(0.5F);
    public static final CBBlock[] CYAN_WOOL = createBlocks(0.5F);
    public static final CBBlock[] LIGHT_BLUE_WOOL = createBlocks(0.5F);
    public static final CBBlock[] BLUE_WOOL = createBlocks(0.5F);
    public static final CBBlock[] PURPLE_WOOL = createBlocks(0.5F);
    public static final CBBlock[] MAGENTA_WOOL = createBlocks(0.5F);
    public static final CBBlock[] PINK_WOOL = createBlocks(0.5F);
    public static final CBBlock[] TERRACOTTA = createBlocks(null);
    public static final CBBlock[] WHITE_TERRACOTTA = createBlocks(null);
    public static final CBBlock[] LIGHT_GRAY_TERRACOTTA = createBlocks(null);
    public static final CBBlock[] GRAY_TERRACOTTA = createBlocks(null);
    public static final CBBlock[] BLACK_TERRACOTTA = createBlocks(null);
    public static final CBBlock[] BROWN_TERRACOTTA = createBlocks(null);
    public static final CBBlock[] RED_TERRACOTTA = createBlocks(null);
    public static final CBBlock[] ORANGE_TERRACOTTA = createBlocks(null);
    public static final CBBlock[] YELLOW_TERRACOTTA = createBlocks(null);
    public static final CBBlock[] LIME_TERRACOTTA = createBlocks(null);
    public static final CBBlock[] GREEN_TERRACOTTA = createBlocks(null);
    public static final CBBlock[] CYAN_TERRACOTTA = createBlocks(null);
    public static final CBBlock[] LIGHT_BLUE_TERRACOTTA = createBlocks(null);
    public static final CBBlock[] BLUE_TERRACOTTA = createBlocks(null);
    public static final CBBlock[] PURPLE_TERRACOTTA = createBlocks(null);
    public static final CBBlock[] MAGENTA_TERRACOTTA = createBlocks(null);
    public static final CBBlock[] PINK_TERRACOTTA = createBlocks(null);
    public static final CBBlock[] WHITE_GLAZED_TERRACOTTA = createBlocks(null);
    public static final CBBlock[] LIGHT_GRAY_GLAZED_TERRACOTTA = createBlocks(null);
    public static final CBBlock[] GRAY_GLAZED_TERRACOTTA = createBlocks(null);
    public static final CBBlock[] BLACK_GLAZED_TERRACOTTA = createBlocks(null);
    public static final CBBlock[] BROWN_GLAZED_TERRACOTTA = createBlocks(null);
    public static final CBBlock[] RED_GLAZED_TERRACOTTA = createBlocks(null);
    public static final CBBlock[] ORANGE_GLAZED_TERRACOTTA = createBlocks(null);
    public static final CBBlock[] YELLOW_GLAZED_TERRACOTTA = createBlocks(null);
    public static final CBBlock[] LIME_GLAZED_TERRACOTTA = createBlocks(null);
    public static final CBBlock[] GREEN_GLAZED_TERRACOTTA = createBlocks(null);
    public static final CBBlock[] CYAN_GLAZED_TERRACOTTA = createBlocks(null);
    public static final CBBlock[] LIGHT_BLUE_GLAZED_TERRACOTTA = createBlocks(null);
    public static final CBBlock[] BLUE_GLAZED_TERRACOTTA = createBlocks(null);
    public static final CBBlock[] PURPLE_GLAZED_TERRACOTTA = createBlocks(null);
    public static final CBBlock[] MAGENTA_GLAZED_TERRACOTTA = createBlocks(null);
    public static final CBBlock[] PINK_GLAZED_TERRACOTTA = createBlocks(null);
    public static final CBBlock[] WHITE_CONCRETE_POWDER = createBlocks(null);
    public static final CBBlock[] LIGHT_GRAY_CONCRETE_POWDER = createBlocks(null);
    public static final CBBlock[] GRAY_CONCRETE_POWDER = createBlocks(null);
    public static final CBBlock[] BLACK_CONCRETE_POWDER = createBlocks(null);
    public static final CBBlock[] BROWN_CONCRETE_POWDER = createBlocks(null);
    public static final CBBlock[] RED_CONCRETE_POWDER = createBlocks(null);
    public static final CBBlock[] ORANGE_CONCRETE_POWDER = createBlocks(null);
    public static final CBBlock[] YELLOW_CONCRETE_POWDER = createBlocks(null);
    public static final CBBlock[] LIME_CONCRETE_POWDER = createBlocks(null);
    public static final CBBlock[] GREEN_CONCRETE_POWDER = createBlocks(null);
    public static final CBBlock[] CYAN_CONCRETE_POWDER = createBlocks(null);
    public static final CBBlock[] LIGHT_BLUE_CONCRETE_POWDER = createBlocks(null);
    public static final CBBlock[] BLUE_CONCRETE_POWDER = createBlocks(null);
    public static final CBBlock[] PURPLE_CONCRETE_POWDER = createBlocks(null);
    public static final CBBlock[] MAGENTA_CONCRETE_POWDER = createBlocks(null);
    public static final CBBlock[] PINK_CONCRETE_POWDER = createBlocks(null);
    public static final CBBlock[] WHITE_CONCRETE = createBlocks(null);
    public static final CBBlock[] LIGHT_GRAY_CONCRETE = createBlocks(null);
    public static final CBBlock[] GRAY_CONCRETE = createBlocks(null);
    public static final CBBlock[] BLACK_CONCRETE = createBlocks(null);
    public static final CBBlock[] BROWN_CONCRETE = createBlocks(null);
    public static final CBBlock[] RED_CONCRETE = createBlocks(null);
    public static final CBBlock[] ORANGE_CONCRETE = createBlocks(null);
    public static final CBBlock[] YELLOW_CONCRETE = createBlocks(null);
    public static final CBBlock[] LIME_CONCRETE = createBlocks(null);
    public static final CBBlock[] GREEN_CONCRETE = createBlocks(null);
    public static final CBBlock[] CYAN_CONCRETE = createBlocks(null);
    public static final CBBlock[] LIGHT_BLUE_CONCRETE = createBlocks(null);
    public static final CBBlock[] BLUE_CONCRETE = createBlocks(null);
    public static final CBBlock[] PURPLE_CONCRETE = createBlocks(null);
    public static final CBBlock[] MAGENTA_CONCRETE = createBlocks(null);
    public static final CBBlock[] PINK_CONCRETE = createBlocks(null);
    public static final CBBlock[] GLASS = createGlassBlocks(0.125F);
    public static final CBBlock[] TINTED_GLASS = createGlassBlocks(0.25F);
    public static final CBBlock[] WHITE_STAINED_GLASS = createGlassBlocks(0.125F);
    public static final CBBlock[] LIGHT_GRAY_STAINED_GLASS = createGlassBlocks(0.125F);
    public static final CBBlock[] GRAY_STAINED_GLASS = createGlassBlocks(0.125F);
    public static final CBBlock[] BLACK_STAINED_GLASS = createGlassBlocks(0.125F);
    public static final CBBlock[] BROWN_STAINED_GLASS = createGlassBlocks(0.125F);
    public static final CBBlock[] RED_STAINED_GLASS = createGlassBlocks(0.125F);
    public static final CBBlock[] ORANGE_STAINED_GLASS = createGlassBlocks(0.125F);
    public static final CBBlock[] YELLOW_STAINED_GLASS = createGlassBlocks(0.125F);
    public static final CBBlock[] LIME_STAINED_GLASS = createGlassBlocks(0.125F);
    public static final CBBlock[] GREEN_STAINED_GLASS = createGlassBlocks(0.125F);
    public static final CBBlock[] CYAN_STAINED_GLASS = createGlassBlocks(0.125F);
    public static final CBBlock[] LIGHT_BLUE_STAINED_GLASS = createGlassBlocks(0.125F);
    public static final CBBlock[] BLUE_STAINED_GLASS = createGlassBlocks(0.125F);
    public static final CBBlock[] PURPLE_STAINED_GLASS = createGlassBlocks(0.125F);
    public static final CBBlock[] MAGENTA_STAINED_GLASS = createGlassBlocks(0.125F);
    public static final CBBlock[] PINK_STAINED_GLASS = createGlassBlocks(0.125F);
    public static final CBBlock[] ICE = createBlocks(0.75F);
    public static final CBBlock[] PACKED_ICE = createBlocks(0.75F);
    public static final CBBlock[] BLUE_ICE = createBlocks(0.75F);
    public static final CBBlock[] SNOW_BLOCK = createBlocks(0.5F);
    public static final CBBlock[] MOSS_BLOCK = createBlocks(0.5F);
    public static final CBBlock[] CALCITE = createBlocks(null);
    public static final CBBlock[] DRIPSTONE_BLOCK = createBlocks(null);
    public static final CBBlock[] MAGMA_BLOCK = createBlocks(null);
    public static final CBBlock[] GLOWSTONE = createBlocks(null);
    public static final CBBlock[] DRIED_KELP_BLOCK = createBlocks(0.5F);
    public static final CBBlock[] BROWN_MUSHROOM_BLOCK = createBlocks(null);
    public static final CBBlock[] RED_MUSHROOM_BLOCK = createBlocks(null);
    public static final CBBlock[] SHROOMLIGHT = createBlocks(null);
    public static final CBRotationalBlock[] MELON = createRotationalBlocks(null);
    public static final CBRotationalBlock[] PUMPKIN = createRotationalBlocks(null);
    public static final CBRotationalBlock[] HAY_BLOCK = createRotationalBlocks(0.5F);
    public static final CBRotationalBlock[] OCHRE_FROGLIGHT = createRotationalBlocks(null);
    public static final CBRotationalBlock[] VERDANT_FROGLIGHT = createRotationalBlocks(null);
    public static final CBRotationalBlock[] PEARLESCENT_FROGLIGHT = createRotationalBlocks(null);
    public static final CBBlock[] SEA_LANTERN = createBlocks(null);

    private static CBBlock[] createBlocks(Float amplifier) {
        return createBlocks(amplifier, false);
    }

    private static CBBlock[] createBlocks(Float amplifier, boolean isLesser) {
        // todo: add configurable max compression level
        int maxCompressionLevel = 10;
        CBBlock[] result = new CBBlock[maxCompressionLevel];

        for (int i = 0; i < maxCompressionLevel; i++) {
            float baseHardness = HARDNESS[i];
            float baseResistance = RESISTANCE[i];

            float factor = (amplifier == null ? 1 : amplifier) * (isLesser ? 0.5f : 1.0f);

            float blockHardness = baseHardness * factor;
            float blockResistance = baseResistance * factor;

            result[i] = new CBBlock(BlockBehaviour.Properties.of().strength(blockHardness, blockResistance), i, isLesser);
        }
        return result;
    }

    private static CBBlock[] createGlassBlocks(Float amplifier) {
        int maxCompressionLevel = 10;
        CBBlock[] result = new CBBlock[maxCompressionLevel];
        for (int i = 0; i < maxCompressionLevel; i++) {
            float blockHardness = amplifier != null ? HARDNESS[i] * amplifier : HARDNESS[i];
            float blockResistance = amplifier != null ? RESISTANCE[i] * amplifier : RESISTANCE[i];

            result[i] = new CBBlock(BlockBehaviour.Properties.of().noCollission().strength(blockHardness, blockResistance), i, false);
        }
        return result;
    }

    private static CBRotationalBlock[] createRotationalBlocks(Float amplifier) {
        int maxCompressionLevel = 10;
        CBRotationalBlock[] result = new CBRotationalBlock[maxCompressionLevel];
        for (int i = 0; i < maxCompressionLevel; i++) {
            float blockHardness = amplifier != null ? HARDNESS[i] * amplifier : HARDNESS[i];
            float blockResistance = amplifier != null ? RESISTANCE[i] * amplifier : RESISTANCE[i];
            result[i] = new CBRotationalBlock(BlockBehaviour.Properties.of().strength(blockHardness, blockResistance), i);
        }
        return result;
    }
}