modLoader = "javafml" #mandatory, The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
loaderVersion = "[43,)" #mandatory, A version range to match for said mod loader - for regular FML @Mod it will be the forge version
# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license = "GPLv3" #mandatory since 1.16.3
issueTrackerURL = "https://github.com/sa-shiro/Minecraft-Compressed-Blocks/issues" #optional, A URL to refer people to when problems occur with this mod
[[mods]] #mandatory, A list of mods - how many allowed here is determined by the individual mod loader
modId = "compressedblocks" #mandatory, The modid of the mod
version = "${file.jarVersion}" #mandatory, # The version number of the mod
displayName = "CB: Compressed Blocks" #mandatory, A display name for the mod
updateJSONURL = "https://raw.githubusercontent.com/sa-shiro/Minecraft-Compressed-Blocks/master/update.json" #optional, A URL to query for updates for this mod
displayURL = "https://www.curseforge.com/minecraft/mc-mods/cb-compressed-blocks" #optional, A URL for the "homepage" for this mod, displayed in the mod UI
logoFile = "logo.png" #optional, A file name (in the root of the mod JAR) containing a logo for display
#credits="" #optional, A text field displayed in the mod UI
authors = "Sashiro" #optional, A text field displayed in the mod UI
# The description text for the mod (multi line!) (#mandatory)
description = '''
Compressed Blocks Mod
'''
[[dependencies.compressedblocks]] #optional, # A dependency - use the . to indicate dependency for a specific modid.
modId = "forge" #mandatory, the modid of the dependency
mandatory = true #mandatory, Does this dependency have to exist - if not, ordering below must be specified
versionRange = "[43,)" #mandatory, The version range of the dependency
ordering = "NONE" # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
side = "BOTH" # Side this dependency is applied on - BOTH, CLIENT or SERVER

[[dependencies.compressedblocks]]
modId = "minecraft"
mandatory = true
versionRange="[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"