package com.github.sa_shiro.compressedblocks.util;

import com.github.sa_shiro.compressedblocks.block.BlockFactory;
import com.github.sa_shiro.compressedblocks.block.BlockType;
import net.minecraft.block.SoundType;
import net.minecraft.block.material.Material;
import net.minecraft.block.material.MaterialColor;

import java.util.ArrayList;

public class Lists {
    public final static ArrayList<Float> HARDNESS = new ArrayList<>();
    public final static ArrayList<Float> RESISTANCE = new ArrayList<>();
    public final static ArrayList<Integer> HARVEST_LEVEL = new ArrayList<>();
    public static final ArrayList<BlockFactory> blockList = new ArrayList<>();
    public static final ArrayList<BlockFactory> mekanismBlockList = new ArrayList<>();
    //public static final ArrayList<BlockFactory> thermalBlockList = new ArrayList<>();

    //------------------------------------------------------------------------------------------------------------------
    // Minecraft Blocks
    //------------------------------------------------------------------------------------------------------------------
    public static final BlockFactory STONE = new BlockFactory(BlockType.DEFAULT, "stone", Material.ROCK, MaterialColor.STONE, SoundType.STONE);
    public static final BlockFactory GRANITE = new BlockFactory(BlockType.DEFAULT, "granite", Material.ROCK, MaterialColor.DIRT, SoundType.STONE);
    public static final BlockFactory DIORITE = new BlockFactory(BlockType.DEFAULT, "diorite", Material.ROCK, MaterialColor.QUARTZ, SoundType.STONE);
    public static final BlockFactory ANDESITE = new BlockFactory(BlockType.DEFAULT, "andesite", Material.ROCK, MaterialColor.STONE, SoundType.STONE);
    public static final BlockFactory DIRT = new BlockFactory(BlockType.DEFAULT, "dirt", Material.EARTH, MaterialColor.DIRT, SoundType.GROUND);
    public static final BlockFactory GRASS_BLOCK = new BlockFactory(BlockType.DEFAULT, "grass_block", Material.EARTH, MaterialColor.DIRT, SoundType.GROUND);
    public static final BlockFactory COARSE_DIRT = new BlockFactory(BlockType.DEFAULT, "coarse_dirt", Material.EARTH, MaterialColor.DIRT, SoundType.GROUND);
    public static final BlockFactory CRIMSON_NYLIUM = new BlockFactory(BlockType.DEFAULT, "crimson_nylium", Material.ROCK, MaterialColor.CRIMSON_NYLIUM, SoundType.NYLIUM);
    public static final BlockFactory WARPED_NYLIUM = new BlockFactory(BlockType.DEFAULT, "warped_nylium", Material.ROCK, MaterialColor.WARPED_NYLIUM, SoundType.NYLIUM);
    public static final BlockFactory COBBLESTONE = new BlockFactory(BlockType.DEFAULT, "cobblestone", Material.ROCK, null, SoundType.STONE);
    public static final BlockFactory MOSSY_COBBLESTONE = new BlockFactory(BlockType.DEFAULT, "mossy_cobblestone", Material.ROCK, null, SoundType.STONE);
    public static final BlockFactory CLAY = new BlockFactory(BlockType.DEFAULT, "clay", Material.CLAY, MaterialColor.CLAY, SoundType.GROUND);
    public static final BlockFactory SAND = new BlockFactory(BlockType.SAND, "sand", Material.SAND, MaterialColor.SAND, SoundType.SAND);
    public static final BlockFactory RED_SAND = new BlockFactory(BlockType.RED_SAND, "red_sand", Material.SAND, MaterialColor.SAND, SoundType.SAND);
    public static final BlockFactory GRAVEL = new BlockFactory(BlockType.GRAVEL, "gravel", Material.SAND, MaterialColor.STONE, SoundType.GROUND);
    public static final BlockFactory SANDSTONE = new BlockFactory(BlockType.DEFAULT, "sandstone", Material.ROCK, MaterialColor.SAND, SoundType.STONE);
    public static final BlockFactory RED_SANDSTONE = new BlockFactory(BlockType.DEFAULT, "red_sandstone", Material.ROCK, MaterialColor.SAND, SoundType.STONE);
    public static final BlockFactory COAL_ORE = new BlockFactory(BlockType.DEFAULT, "coal_ore", Material.ROCK, null, SoundType.STONE);
    public static final BlockFactory IRON_ORE = new BlockFactory(BlockType.DEFAULT, "iron_ore", Material.ROCK, null, SoundType.STONE);
    public static final BlockFactory GOLD_ORE = new BlockFactory(BlockType.DEFAULT, "gold_ore", Material.ROCK, null, SoundType.STONE);
    public static final BlockFactory NETHER_GOLD_ORE = new BlockFactory(BlockType.DEFAULT, "nether_gold_ore", Material.ROCK, MaterialColor.NETHERRACK, SoundType.STONE);
    public static final BlockFactory NETHER_QUARTZ_ORE= new BlockFactory(BlockType.DEFAULT, "nether_quartz_ore", Material.ROCK, MaterialColor.NETHERRACK, SoundType.STONE);
    public static final BlockFactory LAPIS_ORE = new BlockFactory(BlockType.DEFAULT, "lapis_ore", Material.ROCK, null, SoundType.STONE);
    public static final BlockFactory EMERALD_ORE = new BlockFactory(BlockType.DEFAULT, "emerald_ore", Material.ROCK, null, SoundType.STONE);
    public static final BlockFactory REDSTONE_ORE = new BlockFactory(BlockType.DEFAULT, "redstone_ore", Material.ROCK, null, SoundType.STONE);
    public static final BlockFactory DIAMOND_ORE = new BlockFactory(BlockType.DEFAULT, "diamond_ore", Material.ROCK, null, SoundType.STONE);
    public static final BlockFactory IRON_BLOCK = new BlockFactory(BlockType.DEFAULT, "iron_block", Material.IRON, MaterialColor.IRON, SoundType.METAL);
    public static final BlockFactory GOLD_BLOCK = new BlockFactory(BlockType.DEFAULT, "gold_block", Material.IRON, MaterialColor.GOLD, SoundType.METAL);
    public static final BlockFactory DIAMOND_BLOCK = new BlockFactory(BlockType.DEFAULT, "diamond_block", Material.IRON, MaterialColor.DIAMOND, SoundType.METAL);
    public static final BlockFactory LAPIS_BLOCK = new BlockFactory(BlockType.DEFAULT, "lapis_block", Material.IRON, MaterialColor.LAPIS, SoundType.METAL);
    public static final BlockFactory EMERALD_BLOCK = new BlockFactory(BlockType.DEFAULT, "emerald_block", Material.IRON, MaterialColor.EMERALD, SoundType.METAL);
    public static final BlockFactory REDSTONE_BLOCK = new BlockFactory(BlockType.REDSTONE, "redstone_block", Material.IRON, MaterialColor.TNT, SoundType.METAL);
    public static final BlockFactory COAL_BLOCK = new BlockFactory(BlockType.DEFAULT, "coal_block", Material.ROCK, MaterialColor.BLACK, SoundType.STONE);
    public static final BlockFactory OBSIDIAN = new BlockFactory(BlockType.DEFAULT, "obsidian", Material.ROCK, MaterialColor.BLACK, SoundType.STONE);
    public static final BlockFactory SLIME_BLOCK = new BlockFactory(BlockType.SLIME, "slime_block", Material.CLAY, MaterialColor.GRASS, SoundType.SLIME);
    public static final BlockFactory BRICKS = new BlockFactory(BlockType.DEFAULT, "bricks", Material.ROCK, MaterialColor.RED, SoundType.STONE);
    public static final BlockFactory STONE_BRICKS = new BlockFactory(BlockType.DEFAULT, "stone_bricks", Material.ROCK, null, SoundType.STONE);
    public static final BlockFactory NETHERRACK = new BlockFactory(BlockType.DEFAULT, "netherrack", Material.ROCK, MaterialColor.NETHERRACK, SoundType.NETHERRACK);
    public static final BlockFactory NETHER_BRICKS = new BlockFactory(BlockType.DEFAULT, "nether_bricks", Material.EARTH, MaterialColor.NETHERRACK, SoundType.NETHER_BRICK);
    public static final BlockFactory RED_NETHER_BRICKS = new BlockFactory(BlockType.DEFAULT, "red_nether_bricks", Material.EARTH, MaterialColor.NETHERRACK, SoundType.NETHER_BRICK);
    public static final BlockFactory NETHER_WART_BLOCK = new BlockFactory(BlockType.DEFAULT, "nether_wart_block", Material.ORGANIC, MaterialColor.RED, SoundType.NETHER_WART);
    public static final BlockFactory WARPED_WART_BLOCK = new BlockFactory(BlockType.DEFAULT, "warped_wart_block", Material.ORGANIC, MaterialColor.WARPED_WART, SoundType.WART);
    public static final BlockFactory SOUL_SAND = new BlockFactory(BlockType.SOUL_SAND, "soul_sand", Material.SAND, MaterialColor.BROWN, SoundType.SOUL_SAND);
    public static final BlockFactory SOUL_SOIL = new BlockFactory(BlockType.DEFAULT, "soul_soil", Material.EARTH, MaterialColor.BROWN, SoundType.SOUL_SOIL);
    public static final BlockFactory END_STONE = new BlockFactory(BlockType.DEFAULT, "end_stone", Material.ROCK, MaterialColor.SAND, SoundType.STONE);
    public static final BlockFactory END_STONE_BRICKS = new BlockFactory(BlockType.DEFAULT, "end_stone_bricks", Material.ROCK, MaterialColor.SAND, SoundType.STONE);
    public static final BlockFactory PRISMARINE = new BlockFactory(BlockType.DEFAULT, "prismarine", Material.ROCK, MaterialColor.CYAN, SoundType.STONE);
    public static final BlockFactory PRISMARINE_BRICKS = new BlockFactory(BlockType.DEFAULT, "prismarine_bricks", Material.ROCK, MaterialColor.DIAMOND, SoundType.STONE);
    public static final BlockFactory DARK_PRISMARINE = new BlockFactory(BlockType.DEFAULT, "dark_prismarine", Material.ROCK, MaterialColor.DIAMOND, SoundType.STONE);
    public static final BlockFactory BLACKSTONE = new BlockFactory(BlockType.DEFAULT, "blackstone", Material.ANVIL, MaterialColor.BLACK, SoundType.STONE);
    public static final BlockFactory WHITE_WOOL = new BlockFactory(BlockType.WOOL, "white_wool", Material.WOOL, MaterialColor.SNOW, SoundType.CLOTH);
    public static final BlockFactory ORANGE_WOOL = new BlockFactory(BlockType.WOOL, "orange_wool", Material.WOOL, MaterialColor.ADOBE, SoundType.CLOTH);
    public static final BlockFactory MAGENTA_WOOL = new BlockFactory(BlockType.WOOL, "magenta_wool", Material.WOOL, MaterialColor.MAGENTA, SoundType.CLOTH);
    public static final BlockFactory LIGHT_BLUE_WOOL = new BlockFactory(BlockType.WOOL, "light_blue_wool", Material.WOOL, MaterialColor.LIGHT_BLUE, SoundType.CLOTH);
    public static final BlockFactory YELLOW_WOOL = new BlockFactory(BlockType.WOOL, "yellow_wool", Material.WOOL, MaterialColor.YELLOW, SoundType.CLOTH);
    public static final BlockFactory LIME_WOOL = new BlockFactory(BlockType.WOOL, "lime_wool", Material.WOOL, MaterialColor.LIME, SoundType.CLOTH);
    public static final BlockFactory PINK_WOOL = new BlockFactory(BlockType.WOOL, "pink_wool", Material.WOOL, MaterialColor.PINK, SoundType.CLOTH);
    public static final BlockFactory GRAY_WOOL = new BlockFactory(BlockType.WOOL, "gray_wool", Material.WOOL, MaterialColor.GRAY, SoundType.CLOTH);
    public static final BlockFactory LIGHT_GRAY_WOOL = new BlockFactory(BlockType.WOOL, "light_gray_wool", Material.WOOL, MaterialColor.LIGHT_GRAY, SoundType.CLOTH);
    public static final BlockFactory CYAN_WOOL = new BlockFactory(BlockType.WOOL, "cyan_wool", Material.WOOL, MaterialColor.CYAN, SoundType.CLOTH);
    public static final BlockFactory PURPLE_WOOL = new BlockFactory(BlockType.WOOL, "purple_wool", Material.WOOL, MaterialColor.PURPLE, SoundType.CLOTH);
    public static final BlockFactory BLUE_WOOL = new BlockFactory(BlockType.WOOL, "blue_wool", Material.WOOL, MaterialColor.BLUE, SoundType.CLOTH);
    public static final BlockFactory BROWN_WOOL = new BlockFactory(BlockType.WOOL, "brown_wool", Material.WOOL, MaterialColor.BROWN, SoundType.CLOTH);
    public static final BlockFactory GREEN_WOOL = new BlockFactory(BlockType.WOOL, "green_wool", Material.WOOL, MaterialColor.GREEN, SoundType.CLOTH);
    public static final BlockFactory RED_WOOL = new BlockFactory(BlockType.WOOL, "red_wool", Material.WOOL, MaterialColor.RED, SoundType.CLOTH);
    public static final BlockFactory BLACK_WOOL = new BlockFactory(BlockType.WOOL, "black_wool", Material.WOOL, MaterialColor.BLACK, SoundType.CLOTH);
    public static final BlockFactory TERRACOTTA = new BlockFactory(BlockType.DEFAULT, "terracotta", Material.ROCK, MaterialColor.ADOBE, SoundType.STONE);
    public static final BlockFactory WHITE_TERRACOTTA = new BlockFactory(BlockType.DEFAULT, "white_terracotta", Material.ROCK, MaterialColor.WHITE_TERRACOTTA, SoundType.STONE);
    public static final BlockFactory ORANGE_TERRACOTTA = new BlockFactory(BlockType.DEFAULT, "orange_terracotta", Material.ROCK, MaterialColor.ORANGE_TERRACOTTA, SoundType.STONE);
    public static final BlockFactory MAGENTA_TERRACOTTA = new BlockFactory(BlockType.DEFAULT, "magenta_terracotta", Material.ROCK, MaterialColor.MAGENTA_TERRACOTTA, SoundType.STONE);
    public static final BlockFactory LIGHT_BLUE_TERRACOTTA = new BlockFactory(BlockType.DEFAULT, "light_blue_terracotta", Material.ROCK, MaterialColor.LIGHT_BLUE_TERRACOTTA, SoundType.STONE);
    public static final BlockFactory YELLOW_TERRACOTTA = new BlockFactory(BlockType.DEFAULT, "yellow_terracotta", Material.ROCK, MaterialColor.YELLOW_TERRACOTTA, SoundType.STONE);
    public static final BlockFactory LIME_TERRACOTTA = new BlockFactory(BlockType.DEFAULT, "lime_terracotta", Material.ROCK, MaterialColor.LIME_TERRACOTTA, SoundType.STONE);
    public static final BlockFactory PINK_TERRACOTTA = new BlockFactory(BlockType.DEFAULT, "pink_terracotta", Material.ROCK, MaterialColor.PINK_TERRACOTTA, SoundType.STONE);
    public static final BlockFactory GRAY_TERRACOTTA = new BlockFactory(BlockType.DEFAULT, "gray_terracotta", Material.ROCK, MaterialColor.GRAY_TERRACOTTA, SoundType.STONE);
    public static final BlockFactory LIGHT_GRAY_TERRACOTTA = new BlockFactory(BlockType.DEFAULT, "light_gray_terracotta", Material.ROCK, MaterialColor.LIGHT_GRAY_TERRACOTTA, SoundType.STONE);
    public static final BlockFactory CYAN_TERRACOTTA = new BlockFactory(BlockType.DEFAULT, "cyan_terracotta", Material.ROCK, MaterialColor.CYAN_TERRACOTTA, SoundType.STONE);
    public static final BlockFactory PURPLE_TERRACOTTA = new BlockFactory(BlockType.DEFAULT, "purple_terracotta", Material.ROCK, MaterialColor.PURPLE_TERRACOTTA, SoundType.STONE);
    public static final BlockFactory BLUE_TERRACOTTA = new BlockFactory(BlockType.DEFAULT, "blue_terracotta", Material.ROCK, MaterialColor.BLUE_TERRACOTTA, SoundType.STONE);
    public static final BlockFactory BROWN_TERRACOTTA = new BlockFactory(BlockType.DEFAULT, "brown_terracotta", Material.ROCK, MaterialColor.BROWN_TERRACOTTA, SoundType.STONE);
    public static final BlockFactory GREEN_TERRACOTTA = new BlockFactory(BlockType.DEFAULT, "green_terracotta", Material.ROCK, MaterialColor.GREEN_TERRACOTTA, SoundType.STONE);
    public static final BlockFactory RED_TERRACOTTA = new BlockFactory(BlockType.DEFAULT, "red_terracotta", Material.ROCK, MaterialColor.RED_TERRACOTTA, SoundType.STONE);
    public static final BlockFactory BLACK_TERRACOTTA = new BlockFactory(BlockType.DEFAULT, "black_terracotta", Material.ROCK, MaterialColor.BLACK_TERRACOTTA, SoundType.STONE);
    public static final BlockFactory WHITE_CONCRETE = new BlockFactory(BlockType.DEFAULT, "white_concrete", Material.ROCK, MaterialColor.SNOW, SoundType.STONE);
    public static final BlockFactory ORANGE_CONCRETE = new BlockFactory(BlockType.DEFAULT, "orange_concrete", Material.ROCK, MaterialColor.ADOBE, SoundType.STONE);
    public static final BlockFactory MAGENTA_CONCRETE = new BlockFactory(BlockType.DEFAULT, "magenta_concrete", Material.ROCK, MaterialColor.MAGENTA, SoundType.STONE);
    public static final BlockFactory LIGHT_BLUE_CONCRETE = new BlockFactory(BlockType.DEFAULT, "light_blue_concrete", Material.ROCK, MaterialColor.LIGHT_BLUE, SoundType.STONE);
    public static final BlockFactory YELLOW_CONCRETE = new BlockFactory(BlockType.DEFAULT, "yellow_concrete", Material.ROCK, MaterialColor.YELLOW, SoundType.STONE);
    public static final BlockFactory LIME_CONCRETE = new BlockFactory(BlockType.DEFAULT, "lime_concrete", Material.ROCK, MaterialColor.LIME, SoundType.STONE);
    public static final BlockFactory PINK_CONCRETE = new BlockFactory(BlockType.DEFAULT, "pink_concrete", Material.ROCK, MaterialColor.PINK, SoundType.STONE);
    public static final BlockFactory GRAY_CONCRETE = new BlockFactory(BlockType.DEFAULT, "gray_concrete", Material.ROCK, MaterialColor.GRAY, SoundType.STONE);
    public static final BlockFactory LIGHT_GRAY_CONCRETE = new BlockFactory(BlockType.DEFAULT, "light_gray_concrete", Material.ROCK, MaterialColor.LIGHT_GRAY, SoundType.STONE);
    public static final BlockFactory CYAN_CONCRETE = new BlockFactory(BlockType.DEFAULT, "cyan_concrete", Material.ROCK, MaterialColor.CYAN, SoundType.STONE);
    public static final BlockFactory PURPLE_CONCRETE = new BlockFactory(BlockType.DEFAULT, "purple_concrete", Material.ROCK, MaterialColor.PURPLE, SoundType.STONE);
    public static final BlockFactory BLUE_CONCRETE = new BlockFactory(BlockType.DEFAULT, "blue_concrete", Material.ROCK, MaterialColor.BLUE, SoundType.STONE);
    public static final BlockFactory BROWN_CONCRETE = new BlockFactory(BlockType.DEFAULT, "brown_concrete", Material.ROCK, MaterialColor.BROWN, SoundType.STONE);
    public static final BlockFactory GREEN_CONCRETE = new BlockFactory(BlockType.DEFAULT, "green_concrete", Material.ROCK, MaterialColor.GREEN, SoundType.STONE);
    public static final BlockFactory RED_CONCRETE = new BlockFactory(BlockType.DEFAULT, "red_concrete", Material.ROCK, MaterialColor.RED, SoundType.STONE);
    public static final BlockFactory BLACK_CONCRETE = new BlockFactory(BlockType.DEFAULT, "black_concrete", Material.ROCK, MaterialColor.BLACK, SoundType.STONE);
    public static final BlockFactory ROTTEN_FLESH_BLOCK = new BlockFactory(BlockType.CUSTOM, "rotten_flesh_block", Material.ORGANIC, MaterialColor.RED, SoundType.SLIME);
    public static final BlockFactory FLINT_BLOCK = new BlockFactory(BlockType.DEFAULT, "flint_block", Material.ROCK, null, SoundType.STONE);
    public static final BlockFactory GUNPOWDER_BLOCK = new BlockFactory(BlockType.SAND, "gunpowder_block", 5000268, Material.SAND, null, SoundType.SAND);

    //------------------------------------------------------------------------------------------------------------------
    // Mekanism Blocks
    public static final BlockFactory OSMIUM_BLOCK_MEKANISM = new BlockFactory(BlockType.DEFAULT, "osmium_block_mekanism", Material.IRON, null, SoundType.METAL);
    public static final BlockFactory COPPER_BLOCK_MEKANISM = new BlockFactory(BlockType.DEFAULT, "copper_block_mekanism", Material.IRON, null, SoundType.METAL);
    public static final BlockFactory TIN_BLOCK_MEKANISM = new BlockFactory(BlockType.DEFAULT, "tin_block_mekanism", Material.IRON, null, SoundType.METAL);
    public static final BlockFactory LEAD_BLOCK_MEKANISM = new BlockFactory(BlockType.DEFAULT, "lead_block_mekanism", Material.IRON, null, SoundType.METAL);
    public static final BlockFactory URANIUM_BLOCK_MEKANISM = new BlockFactory(BlockType.DEFAULT, "uranium_block_mekanism", Material.IRON, null, SoundType.METAL);
    public static final BlockFactory COPPER_ORE_MEKANISM = new BlockFactory(BlockType.DEFAULT, "copper_ore_mekanism", Material.ROCK, null, SoundType.STONE);
    public static final BlockFactory TIN_ORE_MEKANISM = new BlockFactory(BlockType.DEFAULT, "tin_ore_mekanism", Material.ROCK, null, SoundType.STONE);
    public static final BlockFactory OSMIUM_ORE_MEKANISM = new BlockFactory(BlockType.DEFAULT, "osmium_ore_mekanism", Material.ROCK, null, SoundType.STONE);
    public static final BlockFactory URANIUM_ORE_MEKANISM = new BlockFactory(BlockType.DEFAULT, "uranium_ore_mekanism", Material.ROCK, null, SoundType.STONE);
    public static final BlockFactory FLUORITE_ORE_MEKANISM = new BlockFactory(BlockType.DEFAULT, "fluorite_ore_mekanism", Material.ROCK, null, SoundType.STONE);
    public static final BlockFactory LEAD_ORE_MEKANISM = new BlockFactory(BlockType.DEFAULT, "lead_ore_mekanism", Material.ROCK, null, SoundType.STONE);
    public static final BlockFactory BRONZE_BLOCK_MEKANISM = new BlockFactory(BlockType.DEFAULT, "bronze_block_mekanism", Material.IRON, null, SoundType.METAL);
    public static final BlockFactory REFINED_OBSIDIAN_MEKANISM = new BlockFactory(BlockType.DEFAULT, "refined_obsidian_mekanism", Material.ROCK, null, SoundType.STONE);
    public static final BlockFactory CHARCOAL_BLOCK_MEKANISM = new BlockFactory(BlockType.DEFAULT, "charcoal_block_mekanism", Material.ROCK, null, SoundType.STONE);
    public static final BlockFactory REFINED_GLOWSTONE_MEKANISM = new BlockFactory(BlockType.GLASS, "refined_glowstone_mekanism", Material.GLASS, null, SoundType.GLASS);
    public static final BlockFactory STEEL_BLOCK_MEKANISM = new BlockFactory(BlockType.DEFAULT, "steel_block_mekanism", Material.IRON, null, SoundType.METAL);
    // END Mekanism Blocks
    //------------------------------------------------------------------------------------------------------------------

    //------------------------------------------------------------------------------------------------------------------
    // Thermal Blocks
    /*
    public static final BlockFactory CHARCOAL_BLOCK_THERMAL = new BlockFactory(BlockType.DEFAULT, "charcoal_block_thermal", Material.ROCK, null, SoundType.STONE);
    public static final BlockFactory GUNPOWDER_BLOCK_THERMAL = new BlockFactory(BlockType.SAND, "gunpowder_block_thermal", Material.SAND, null, SoundType.SAND);
    public static final BlockFactory APATITE_ORE_THERMAL = new BlockFactory(BlockType.DEFAULT, "apatite_ore_thermal", Material.ROCK, null, SoundType.STONE);
    public static final BlockFactory CINNABAR_ORE_THERMAL = new BlockFactory(BlockType.DEFAULT, "cinnabar_ore_thermal", Material.ROCK, null, SoundType.STONE);
    public static final BlockFactory NITER_ORE_THERMAL = new BlockFactory(BlockType.DEFAULT, "niter_ore_thermal", Material.ROCK, null, SoundType.STONE);
    public static final BlockFactory SULFUR_ORE_THERMAL = new BlockFactory(BlockType.DEFAULT, "sulfur_ore_thermal", Material.ROCK, null, SoundType.STONE);
    public static final BlockFactory COPPER_ORE_THERMAL = new BlockFactory(BlockType.DEFAULT, "copper_ore_thermal", Material.ROCK, null, SoundType.STONE);
    public static final BlockFactory TIN_ORE_THERMAL = new BlockFactory(BlockType.DEFAULT, "tin_ore_thermal", Material.ROCK, null, SoundType.STONE);
    public static final BlockFactory LEAD_ORE_THERMAL = new BlockFactory(BlockType.DEFAULT, "lead_ore_thermal", Material.ROCK, null, SoundType.STONE);
    public static final BlockFactory SILVER_ORE_THERMAL = new BlockFactory(BlockType.DEFAULT, "silver_ore_thermal", Material.ROCK, null, SoundType.STONE);
    public static final BlockFactory NICKEL_ORE_THERMAL = new BlockFactory(BlockType.DEFAULT, "nickel_ore_thermal", Material.ROCK, null, SoundType.STONE);
    public static final BlockFactory APATITE_BLOCK_THERMAL = new BlockFactory(BlockType.DEFAULT, "apatite_block_thermal", Material.IRON, null, SoundType.METAL);
    public static final BlockFactory CINNABAR_BLOCK_THERMAL = new BlockFactory(BlockType.DEFAULT, "cinnabar_block_thermal", Material.IRON, null, SoundType.METAL);
    public static final BlockFactory NITER_BLOCK_THERMAL = new BlockFactory(BlockType.DEFAULT, "niter_block_thermal", Material.IRON, null, SoundType.METAL);
    public static final BlockFactory SULFUR_BLOCK_THERMAL = new BlockFactory(BlockType.DEFAULT, "sulfur_block_thermal", Material.IRON, null, SoundType.METAL);
    public static final BlockFactory COPPER_BLOCK_THERMAL = new BlockFactory(BlockType.DEFAULT, "copper_block_thermal", Material.IRON, null, SoundType.METAL);
    public static final BlockFactory TIN_BLOCK_THERMAL = new BlockFactory(BlockType.DEFAULT, "tin_block_thermal", Material.IRON, null, SoundType.METAL);
    public static final BlockFactory LEAD_BLOCK_THERMAL = new BlockFactory(BlockType.DEFAULT, "lead_block_thermal", Material.IRON, null, SoundType.METAL);
    public static final BlockFactory SILVER_BLOCK_THERMAL = new BlockFactory(BlockType.DEFAULT, "silver_block_thermal", Material.IRON, null, SoundType.METAL);
    public static final BlockFactory NICKEL_BLOCK_THERMAL = new BlockFactory(BlockType.DEFAULT, "nickel_block_thermal", Material.IRON, null, SoundType.METAL);
    public static final BlockFactory BRONZE_BLOCK_THERMAL = new BlockFactory(BlockType.DEFAULT, "bronze_block_thermal", Material.IRON, null, SoundType.METAL);
    public static final BlockFactory ELECTRUM_BLOCK_THERMAL = new BlockFactory(BlockType.DEFAULT, "electrum_block_thermal", Material.IRON, null, SoundType.METAL);
    public static final BlockFactory INVAR_BLOCK_THERMAL = new BlockFactory(BlockType.DEFAULT, "invar_block_thermal", Material.IRON, null, SoundType.METAL);
    public static final BlockFactory CONSTANTAN_BLOCK_THERMAL = new BlockFactory(BlockType.DEFAULT, "constantan_block_thermal", Material.IRON, null, SoundType.METAL);
    public static final BlockFactory SIGNALUM_BLOCK_THERMAL = new BlockFactory(BlockType.DEFAULT, "signalum_block_thermal", Material.IRON, null, SoundType.METAL);
    public static final BlockFactory LUMIUM_BLOCK_THERMAL = new BlockFactory(BlockType.DEFAULT, "lumium_block_thermal", Material.IRON, null, SoundType.METAL);
    public static final BlockFactory ENDERIUM_BLOCK_THERMAL = new BlockFactory(BlockType.DEFAULT, "enderium_block_thermal", Material.IRON, null, SoundType.METAL);
    public static final BlockFactory COAL_COKE_BLOCK_THERMAL = new BlockFactory(BlockType.DEFAULT, "coal_coke_block_thermal", Material.ROCK, null, SoundType.STONE);
    public static final BlockFactory SAWDUST_BLOCK_THERMAL = new BlockFactory(BlockType.SAND, "sawdust_block_thermal", Material.SAND, null, SoundType.SAND);
    public static final BlockFactory ROSIN_BLOCK_THERMAL = new BlockFactory(BlockType.DEFAULT, "rosin_block_thermal", Material.ROCK, null, SoundType.STONE);
    public static final BlockFactory RUBBER_BLOCK_THERMAL = new BlockFactory(BlockType.DEFAULT, "rubber_block_thermal", Material.ROCK, null, SoundType.STONE);
    public static final BlockFactory CURED_RUBBER_BLOCK_THERMAL = new BlockFactory(BlockType.DEFAULT, "cured_rubber_block_thermal", Material.ROCK, null, SoundType.STONE);
    public static final BlockFactory SLAG_BLOCK_THERMAL = new BlockFactory(BlockType.DEFAULT, "slag_block_thermal", Material.ROCK, null, SoundType.STONE);
    public static final BlockFactory RICH_SLAG_BLOCK_THERMAL = new BlockFactory(BlockType.DEFAULT, "rich_slag_block_thermal", Material.ROCK, null, SoundType.STONE);
    */
    // END Thermal Blocks
    //------------------------------------------------------------------------------------------------------------------

    public static void populate() {
        blockList.add(STONE);
        blockList.add(GRANITE);
        blockList.add(DIORITE);
        blockList.add(ANDESITE);
        blockList.add(DIRT);
        blockList.add(GRASS_BLOCK);
        blockList.add(COARSE_DIRT);
        blockList.add(CRIMSON_NYLIUM);
        blockList.add(WARPED_NYLIUM);
        blockList.add(COBBLESTONE);
        blockList.add(MOSSY_COBBLESTONE);
        blockList.add(CLAY);
        blockList.add(SAND);
        blockList.add(RED_SAND);
        blockList.add(GRAVEL);
        blockList.add(SANDSTONE);
        blockList.add(RED_SANDSTONE);
        blockList.add(COAL_ORE);
        blockList.add(IRON_ORE);
        blockList.add(GOLD_ORE);
        blockList.add(NETHER_GOLD_ORE);
        blockList.add(NETHER_QUARTZ_ORE);
        blockList.add(LAPIS_ORE);
        blockList.add(EMERALD_ORE);
        blockList.add(REDSTONE_ORE);
        blockList.add(DIAMOND_ORE);
        blockList.add(IRON_BLOCK);
        blockList.add(GOLD_BLOCK);
        blockList.add(DIAMOND_BLOCK);
        blockList.add(LAPIS_BLOCK);
        blockList.add(EMERALD_BLOCK);
        blockList.add(REDSTONE_BLOCK);
        blockList.add(COAL_BLOCK);
        blockList.add(OBSIDIAN);
        blockList.add(SLIME_BLOCK);
        blockList.add(BRICKS);
        blockList.add(STONE_BRICKS);
        blockList.add(NETHERRACK);
        blockList.add(NETHER_BRICKS);
        blockList.add(RED_NETHER_BRICKS);
        blockList.add(NETHER_WART_BLOCK);
        blockList.add(WARPED_WART_BLOCK);
        blockList.add(SOUL_SAND);
        blockList.add(SOUL_SOIL);
        blockList.add(END_STONE);
        blockList.add(END_STONE_BRICKS);
        blockList.add(PRISMARINE);
        blockList.add(PRISMARINE_BRICKS);
        blockList.add(DARK_PRISMARINE);
        blockList.add(BLACKSTONE);
        blockList.add(WHITE_WOOL);
        blockList.add(ORANGE_WOOL);
        blockList.add(MAGENTA_WOOL);
        blockList.add(LIGHT_BLUE_WOOL);
        blockList.add(YELLOW_WOOL);
        blockList.add(LIME_WOOL);
        blockList.add(PINK_WOOL);
        blockList.add(GRAY_WOOL);
        blockList.add(LIGHT_GRAY_WOOL);
        blockList.add(CYAN_WOOL);
        blockList.add(PURPLE_WOOL);
        blockList.add(BLUE_WOOL);
        blockList.add(BROWN_WOOL);
        blockList.add(GREEN_WOOL);
        blockList.add(RED_WOOL);
        blockList.add(BLACK_WOOL);
        blockList.add(TERRACOTTA);
        blockList.add(WHITE_TERRACOTTA);
        blockList.add(ORANGE_TERRACOTTA);
        blockList.add(MAGENTA_TERRACOTTA);
        blockList.add(LIGHT_BLUE_TERRACOTTA);
        blockList.add(YELLOW_TERRACOTTA);
        blockList.add(LIME_TERRACOTTA);
        blockList.add(PINK_TERRACOTTA);
        blockList.add(GRAY_TERRACOTTA);
        blockList.add(LIGHT_GRAY_TERRACOTTA);
        blockList.add(CYAN_TERRACOTTA);
        blockList.add(PURPLE_TERRACOTTA);
        blockList.add(BLUE_TERRACOTTA);
        blockList.add(BROWN_TERRACOTTA);
        blockList.add(GREEN_TERRACOTTA);
        blockList.add(RED_TERRACOTTA);
        blockList.add(BLACK_TERRACOTTA);
        blockList.add(WHITE_CONCRETE);
        blockList.add(ORANGE_CONCRETE);
        blockList.add(MAGENTA_CONCRETE);
        blockList.add(LIGHT_BLUE_CONCRETE);
        blockList.add(YELLOW_CONCRETE);
        blockList.add(LIME_CONCRETE);
        blockList.add(PINK_CONCRETE);
        blockList.add(GRAY_CONCRETE);
        blockList.add(LIGHT_GRAY_CONCRETE);
        blockList.add(CYAN_CONCRETE);
        blockList.add(PURPLE_CONCRETE);
        blockList.add(BLUE_CONCRETE);
        blockList.add(BROWN_CONCRETE);
        blockList.add(GREEN_CONCRETE);
        blockList.add(RED_CONCRETE);
        blockList.add(BLACK_CONCRETE);
        blockList.add(ROTTEN_FLESH_BLOCK);
        blockList.add(FLINT_BLOCK);
        blockList.add(GUNPOWDER_BLOCK);

        HARDNESS.add(0, 8.0f);
        HARDNESS.add(1, 10.5f);
        HARDNESS.add(2, 15.0f);
        HARDNESS.add(3, 20.0f);
        HARDNESS.add(4, 25.0f);
        HARDNESS.add(5, 35.0f);
        HARDNESS.add(6, 40.0f);
        HARDNESS.add(7, 45.0f);
        HARDNESS.add(8, 50.0f);
        HARDNESS.add(9, 55.0f);

        RESISTANCE.add(0, 35.0f);
        RESISTANCE.add(1, 40.0f);
        RESISTANCE.add(2, 40.0f);
        RESISTANCE.add(3, 50.0f);
        RESISTANCE.add(4, 50.0f);
        RESISTANCE.add(5, 50.0f);
        RESISTANCE.add(6, 75.0f);
        RESISTANCE.add(7, 125.0f);
        RESISTANCE.add(8, 150.0f);
        RESISTANCE.add(9, 200.0f);

        HARVEST_LEVEL.add(0, 1);
        HARVEST_LEVEL.add(1, 1);
        HARVEST_LEVEL.add(2, 1);
        HARVEST_LEVEL.add(3, 2);
        HARVEST_LEVEL.add(4, 2);
        HARVEST_LEVEL.add(5, 2);
        HARVEST_LEVEL.add(6, 3);
        HARVEST_LEVEL.add(7, 3);
        HARVEST_LEVEL.add(8, 4);
        HARVEST_LEVEL.add(9, 4);
    }

    public static void populateMekanism() {
        mekanismBlockList.add(OSMIUM_BLOCK_MEKANISM);
        mekanismBlockList.add(COPPER_BLOCK_MEKANISM);
        mekanismBlockList.add(TIN_BLOCK_MEKANISM);
        mekanismBlockList.add(LEAD_BLOCK_MEKANISM);
        mekanismBlockList.add(URANIUM_BLOCK_MEKANISM);
        mekanismBlockList.add(COPPER_ORE_MEKANISM);
        mekanismBlockList.add(TIN_ORE_MEKANISM);
        mekanismBlockList.add(OSMIUM_ORE_MEKANISM);
        mekanismBlockList.add(URANIUM_ORE_MEKANISM);
        mekanismBlockList.add(FLUORITE_ORE_MEKANISM);
        mekanismBlockList.add(LEAD_ORE_MEKANISM);
        mekanismBlockList.add(BRONZE_BLOCK_MEKANISM);
        mekanismBlockList.add(REFINED_OBSIDIAN_MEKANISM);
        mekanismBlockList.add(CHARCOAL_BLOCK_MEKANISM);
        mekanismBlockList.add(REFINED_GLOWSTONE_MEKANISM);
        mekanismBlockList.add(STEEL_BLOCK_MEKANISM);
    }

    /*
    public static void populateThermal() {
        thermalBlockList.add(CHARCOAL_BLOCK_THERMAL);
        thermalBlockList.add(GUNPOWDER_BLOCK_THERMAL);
        thermalBlockList.add(APATITE_ORE_THERMAL);
        thermalBlockList.add(CINNABAR_ORE_THERMAL);
        thermalBlockList.add(NITER_ORE_THERMAL);
        thermalBlockList.add(SULFUR_ORE_THERMAL);
        thermalBlockList.add(COPPER_ORE_THERMAL);
        thermalBlockList.add(TIN_ORE_THERMAL);
        thermalBlockList.add(LEAD_ORE_THERMAL);
        thermalBlockList.add(SILVER_ORE_THERMAL);
        thermalBlockList.add(NICKEL_ORE_THERMAL);
        thermalBlockList.add(APATITE_BLOCK_THERMAL);
        thermalBlockList.add(CINNABAR_BLOCK_THERMAL);
        thermalBlockList.add(NITER_BLOCK_THERMAL);
        thermalBlockList.add(SULFUR_BLOCK_THERMAL);
        thermalBlockList.add(COPPER_BLOCK_THERMAL);
        thermalBlockList.add(TIN_BLOCK_THERMAL);
        thermalBlockList.add(LEAD_BLOCK_THERMAL);
        thermalBlockList.add(SILVER_BLOCK_THERMAL);
        thermalBlockList.add(NICKEL_BLOCK_THERMAL);
        thermalBlockList.add(BRONZE_BLOCK_THERMAL);
        thermalBlockList.add(ELECTRUM_BLOCK_THERMAL);
        thermalBlockList.add(INVAR_BLOCK_THERMAL);
        thermalBlockList.add(CONSTANTAN_BLOCK_THERMAL);
        thermalBlockList.add(SIGNALUM_BLOCK_THERMAL);
        thermalBlockList.add(LUMIUM_BLOCK_THERMAL);
        thermalBlockList.add(ENDERIUM_BLOCK_THERMAL);
        thermalBlockList.add(COAL_COKE_BLOCK_THERMAL);
        thermalBlockList.add(SAWDUST_BLOCK_THERMAL);
        thermalBlockList.add(ROSIN_BLOCK_THERMAL);
        thermalBlockList.add(RUBBER_BLOCK_THERMAL);
        thermalBlockList.add(CURED_RUBBER_BLOCK_THERMAL);
        thermalBlockList.add(SLAG_BLOCK_THERMAL);
        thermalBlockList.add(RICH_SLAG_BLOCK_THERMAL);
    }
    */
}