modLoader = "javafml" #mandatory
loaderVersion = "${neoforge_loader_version_range}" #mandatory
license = "${mod_license}" # Review your options at https://choosealicense.com/.
issueTrackerURL = "${source}/issues" #optional

[[mods]] #mandatory
    modId = "${mod_id}" #mandatory
    version = "${version}" #mandatory
    displayName = "${mod_name}" #mandatory
    updateJSONURL = "${update_url}" #optional (see https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/)
    displayURL = "${curseforge_page}" #optional (displayed in the mod UI)
    logoFile = "${logo_file}" #optional (needs to be in the root of your mod jar (root of your 'resources' folder))
    credits = "" #optional
    authors = "${mod_author}" #optional
    description = '''${mod_description}''' #mandatory (Supports multiline text)

[[dependencies.${mod_id}]] #optional
    modId = "neoforge" #mandatory
mandatory = true #mandatory
    versionRange = "${neoforge_version_range}" #mandatory
    ordering = "NONE" # The order that this dependency should load in relation to your mod, required to be either 'BEFORE' or 'AFTER' if the dependency is not mandatory
    side = "BOTH" # Side this dependency is applied on - 'BOTH', 'CLIENT' or 'SERVER'

[[dependencies.${mod_id}]]
    modId = "minecraft"
mandatory = true #mandatory
    versionRange = "${forge_mc_version_range}"
    ordering = "NONE"
    side = "BOTH"

# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
#[features.${mod_id}]
#openGLVersion="[3.2,)"