package net.sashiro.compressedblocks.world.level.item;

import net.minecraft.world.item.Item;
import net.minecraft.world.item.Items;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;
import net.sashiro.compressedblocks.CompressedBlocks;
import net.sashiro.compressedblocks.util.StringUtils;

import java.util.ArrayList;

@SuppressWarnings({"unused", "CanBeFinal"})
@Mod.EventBusSubscriber(modid = CompressedBlocks.MOD_ID)
public class CrateItems {
    public static final ArrayList<String> CRATE_ITEMS = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> PUMPKIN = new ArrayList<>();
   // DECORATION
    public static ArrayList<RegistryObject<Item>> OAK_SAPLING = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> SPRUCE_SAPLING = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> BIRCH_SAPLING = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> JUNGLE_SAPLING = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> ACACIA_SAPLING = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> DARK_OAK_SAPLING = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> MANGROVE_PROPAGULE = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> OAK_LEAVES = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> SPRUCE_LEAVES = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> BIRCH_LEAVES = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> JUNGLE_LEAVES = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> ACACIA_LEAVES = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> DARK_OAK_LEAVES = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> MANGROVE_LEAVES = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> AZAELA_LEAVES = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> FLOWERING_AZAELA_LEAVES = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> COBWEB = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> GRASS = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> FERN = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> AZAELA = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> DEAD_BUSH = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> SEAGRASS = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> SEA_PICKLE = new ArrayList<>();
    /*
    public static ArrayList<RegistryObject<Item>> DANDELION = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> POPPY = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> BLUE_ORCHID = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> ALLIUM = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> AZURE_BLUET = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> RED_TULIP = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> ORANGE_TULIP = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> WHITE_TULIP = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> PINK_TULIP = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> OXEYE_DAISY = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> CORNFLOWER = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> LILY_OF_THE_VALLEY = new ArrayList<>();
    */
    public static ArrayList<RegistryObject<Item>> WITHER_ROSE = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> SPORE_BLOSSOM = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> BROWN_MUSHROOM = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> RED_MUSHROOM = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> CRIMSON_FUNGUS = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> WARPED_FUNGUS = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> CRIMSON_ROOTS = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> WARPED_ROOTS = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> NETHER_SPROUTS = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> WEEPING_VINES = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> TWISTING_VINES = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> SUGAR_CANE = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> KELP = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> MOSS_CARPET = new ArrayList<>();
    // MOSS BLOCK
    public static ArrayList<RegistryObject<Item>> HANGING_ROOTS = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> BIG_DRIPLEAF = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> BAMBOO = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> TORCH = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> END_ROD = new ArrayList<>();
    //public static ArrayList<RegistryObject<Item>> CHORUS_PLANT = new ArrayList<>();
    //public static ArrayList<RegistryObject<Item>> CHORUS_FLOWER = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> CACTUS = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> SOUL_TORCH = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> CHAIN = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> GLASS_PANE = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> VINES = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> GLOW_LICHEN = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> LILY_PAD = new ArrayList<>();
    // SKULK
    public static ArrayList<RegistryObject<Item>> SCULK_VEIN = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> ANVIL = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> WHITE_CARPET = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> ORANGE_CARPET = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> MAGENTA_CARPET = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> LIGHT_BLUE_CARPET = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> YELLOW_CARPET = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> LIME_CARPET = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> PINK_CARPET = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> GRAY_CARPET = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> LIGHT_GRAY_CARPET = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> CYAN_CARPET = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> PURPLE_CARPET = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> BLUE_CARPET = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> BROWN_CARPET = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> GREEN_CARPET = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> RED_CARPET = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> BLACK_CARPET = new ArrayList<>();
    /*
    public static ArrayList<RegistryObject<Item>> SUNFLOWER = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> LILAC = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> ROSE_BUSH = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> PEONY = new ArrayList<>();
    */
    // CORAL
    public static ArrayList<RegistryObject<Item>> SCAFFOLDING = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> PAINTING = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> FLOWER_POT = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> BELL = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> LANTERN = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> SOUL_LANTERN = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> CAMPFIRE = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> SOUL_CAMPFIRE = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> SMALL_AMETHYST_BUD = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> MEDIUM_AMETHYST_BUD = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> LARGE_AMETHYST_BUD = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> AMETHYST_CLUSTER = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> POINTED_DRIPSTONE = new ArrayList<>();
    // REDSTONE
    public static ArrayList<RegistryObject<Item>> REDSTONE_DUST = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> REDSTONE_TORCH = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> REDSTONE_REPEATER = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> REDSTONE_COMPARATOR = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> PISTON = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> STICKY_PISTON = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> HOPPER = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> LEVER = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> LIGHTNING_ROD = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> DAYLIGHT_DETECTOR = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> SCULK_SENSOR = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> TRIPWIRE_HOOK = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> REDSTONE_LAMP = new ArrayList<>();
    // TRANSPORTATION
    public static ArrayList<RegistryObject<Item>> POWERED_RAIL = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> DETECTOR_RAIL = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> RAIL = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> ACTIVATOR_RAIL = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> MINECART = new ArrayList<>();
    // MISC
    public static ArrayList<RegistryObject<Item>> TURTLE_EGG = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> COAL = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> CHARCOAL = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> DIAMOND = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> EMERALD = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> LAPIS = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> NETHER_QUARTZ = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> AMETHYST_SHARD = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> RAW_IRON = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> IRON_INGOT = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> RAW_COPPER = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> COPPER_INGOT = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> RAW_GOLD = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> GOLD_INGOT = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> STICK = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> BOWL = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> STRING = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> FEATHER = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> GUNPOWDER = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> WHEAT_SEEDS = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> WHEAT = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> FLINT = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> BUCKET = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> POWDER_SNOW_BUCKET = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> SNOWBALL = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> LEATHER = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> MILK_BUCKET = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> BRICK = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> CLAY_BALL = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> PAPER = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> BOOK = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> SLIMEBALL = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> EGG = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> GLOWSTONE_DUST = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> INK_SACS = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> GLOW_INK_SACS = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> COCOA_BEANS = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> BONE_MEAL = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> BONE = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> SUGAR = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> PUMPKIN_SEEDS = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> MELON_SEEDS = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> ENDER_PEARL = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> BLAZE_ROD = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> NETHER_WART = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> ENDER_EYE = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> PRISMARINE_SHARD = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> PRISMARINE_CRYSTALS = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> RABBIT_HIDE = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> CHORUS_FRUIT = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> BEETROOT_SEEDS = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> SHULKER_SHELL = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> HONEYCOMB = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> FROGSPAWN = new ArrayList<>();
    // FOOD
    public static ArrayList<RegistryObject<Item>> APPLE = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> MUSHROOM_STEW = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> BREAD = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> RAW_PORKCHOP = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> COOKED_PORKCHOP = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> GOLDEN_APPLE = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> RAW_COD = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> RAW_SALMON = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> TROPICAL_FISH = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> PUFFERFISH = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> COOKED_COD = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> COOKED_SALMON = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> CAKE = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> COOKIE = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> MELON_SLICE = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> DRIED_KELP = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> RAW_BEEF = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> COOKED_BEEF = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> RAW_CHICKEN = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> COOKED_CHICKEN = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> ROTTEN_FLESH = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> SPIDER_EYE = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> CARROT = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> POTATO = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> BAKED_POTATO = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> POISONOUS_POTATO = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> PUMPKIN_PIE = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> RAW_RABBIT = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> COOKED_RABBIT = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> RABBIT_STEW = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> MUTTON = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> COOKED_MUTTON = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> BEETROOT = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> BEETROOT_SOUP = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> SWEET_BERRIES = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> GLOW_BERRIES = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> HONEY_BOTTLE = new ArrayList<>();
    // COMBAT
    public static ArrayList<RegistryObject<Item>> ARROW = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> SPECTRAL_ARROW = new ArrayList<>();
    // BREWING
    public static ArrayList<RegistryObject<Item>> GHAST_TEAR = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> WATER_BOTTLE = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> GLASS_BOTTLE = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> FERMENTED_SPIDER_EYE = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> BLAZE_POWDER = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> MAGMA_CREAM = new ArrayList<>();

    // fixme: fix translations
    public static void populate() {
        // FOOD
        CRATE_ITEMS.add("apple");
        CRATE_ITEMS.add("mushroom_stew");
        CRATE_ITEMS.add("bread");
        CRATE_ITEMS.add("porkchop");
        CRATE_ITEMS.add("cooked_porkchop");
        CRATE_ITEMS.add("cod");
        CRATE_ITEMS.add("salmon");
        CRATE_ITEMS.add("tropical_fish");
        CRATE_ITEMS.add("pufferfish");
        CRATE_ITEMS.add("cooked_cod");
        CRATE_ITEMS.add("cooked_salmon");
        CRATE_ITEMS.add("cake");
        CRATE_ITEMS.add("cookie");
        CRATE_ITEMS.add("melon_slice");
        CRATE_ITEMS.add("melon_seeds");
        CRATE_ITEMS.add("dried_kelp");
        CRATE_ITEMS.add("beef");
        CRATE_ITEMS.add("cooked_beef");
        CRATE_ITEMS.add("chicken");
        CRATE_ITEMS.add("cooked_chicken");
        CRATE_ITEMS.add("rotten_flesh");
        CRATE_ITEMS.add("carrot");
        CRATE_ITEMS.add("potato");
        CRATE_ITEMS.add("baked_potato");
        CRATE_ITEMS.add("poisonous_potato");
        CRATE_ITEMS.add("pumpkin_pie");
        CRATE_ITEMS.add("rabbit");
        CRATE_ITEMS.add("cooked_rabbit");
        CRATE_ITEMS.add("rabbit_stew");
        CRATE_ITEMS.add("mutton");
        CRATE_ITEMS.add("cooked_mutton");
        CRATE_ITEMS.add("beetroot");
        CRATE_ITEMS.add("beetroot_seeds");
        CRATE_ITEMS.add("beetroot_soup");
        CRATE_ITEMS.add("sweet_berries");
        CRATE_ITEMS.add("glow_berries");
        CRATE_ITEMS.add("egg");
        CRATE_ITEMS.add("sugar_cane");
        CRATE_ITEMS.add("sugar");
        CRATE_ITEMS.add("pumpkin");
        CRATE_ITEMS.add("pumpkin_seeds");
        CRATE_ITEMS.add("wheat");
        CRATE_ITEMS.add("wheat_seeds");
        CRATE_ITEMS.add("cocoa_beans");
        // MOB LOOT
        CRATE_ITEMS.add("arrow");
        CRATE_ITEMS.add("spider_eye");
        CRATE_ITEMS.add("fermented_spider_eye");
        CRATE_ITEMS.add("blaze_rod");
        CRATE_ITEMS.add("blaze_powder");
        CRATE_ITEMS.add("magma_cream");
        CRATE_ITEMS.add("bone");
        CRATE_ITEMS.add("bone_meal");
        CRATE_ITEMS.add("ender_eye");
        CRATE_ITEMS.add("ender_pearl");
        CRATE_ITEMS.add("feather");
        CRATE_ITEMS.add("leather");
        CRATE_ITEMS.add("string");
        CRATE_ITEMS.add("ink_sac");
        CRATE_ITEMS.add("glow_ink_sac");
        // MISC
        CRATE_ITEMS.add("stick");
        CRATE_ITEMS.add("glass_bottle");
        CRATE_ITEMS.add("snowball");
        CRATE_ITEMS.add("paper");
        CRATE_ITEMS.add("flint");
        // SAPLINGS / NATURE
        CRATE_ITEMS.add("oak_sapling");
        CRATE_ITEMS.add("spruce_sapling");
        CRATE_ITEMS.add("birch_sapling");
        CRATE_ITEMS.add("jungle_sapling");
        CRATE_ITEMS.add("acacia_sapling");
        CRATE_ITEMS.add("dark_oak_sapling");
        CRATE_ITEMS.add("chorus_fruit");
        CRATE_ITEMS.add("seagrass");
        CRATE_ITEMS.add("kelp");
        CRATE_ITEMS.add("bamboo");
        CRATE_ITEMS.add("brown_mushroom");
        CRATE_ITEMS.add("red_mushroom");
        CRATE_ITEMS.add("crimson_fungus");
        CRATE_ITEMS.add("warped_fungus");
        CRATE_ITEMS.add("wither_rose");
        CRATE_ITEMS.add("nether_wart");

        APPLE.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.APPLE), ForgeRegistries.ITEMS));
        MUSHROOM_STEW.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.MUSHROOM_STEW), ForgeRegistries.ITEMS));
        BREAD.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.BREAD), ForgeRegistries.ITEMS));
        RAW_PORKCHOP.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.PORKCHOP), ForgeRegistries.ITEMS));
        COOKED_PORKCHOP.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.COOKED_PORKCHOP), ForgeRegistries.ITEMS));
        RAW_COD.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.COD), ForgeRegistries.ITEMS));
        RAW_SALMON.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.SALMON), ForgeRegistries.ITEMS));
        TROPICAL_FISH.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.TROPICAL_FISH), ForgeRegistries.ITEMS));
        PUFFERFISH.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.PUFFERFISH), ForgeRegistries.ITEMS));
        COOKED_COD.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.COOKED_COD), ForgeRegistries.ITEMS));
        COOKED_SALMON.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.COOKED_SALMON), ForgeRegistries.ITEMS));
        CAKE.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.CAKE), ForgeRegistries.ITEMS));
        COOKIE.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.COOKIE), ForgeRegistries.ITEMS));
        MELON_SLICE.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.MELON_SLICE), ForgeRegistries.ITEMS));
        MELON_SEEDS.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.MELON_SEEDS), ForgeRegistries.ITEMS));
        DRIED_KELP.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.DRIED_KELP), ForgeRegistries.ITEMS));
        RAW_BEEF.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.BEEF), ForgeRegistries.ITEMS));
        COOKED_BEEF.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.COOKED_BEEF), ForgeRegistries.ITEMS));
        RAW_CHICKEN.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.CHICKEN), ForgeRegistries.ITEMS));
        COOKED_CHICKEN.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.COOKED_CHICKEN), ForgeRegistries.ITEMS));
        ROTTEN_FLESH.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.ROTTEN_FLESH), ForgeRegistries.ITEMS));
        CARROT.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.CARROT), ForgeRegistries.ITEMS));
        POTATO.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.POTATO), ForgeRegistries.ITEMS));
        BAKED_POTATO.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.BAKED_POTATO), ForgeRegistries.ITEMS));
        POISONOUS_POTATO.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.POISONOUS_POTATO), ForgeRegistries.ITEMS));
        PUMPKIN_PIE.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.PUMPKIN_PIE), ForgeRegistries.ITEMS));
        RAW_RABBIT.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.RABBIT), ForgeRegistries.ITEMS));
        COOKED_RABBIT.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.COOKED_RABBIT), ForgeRegistries.ITEMS));
        RABBIT_STEW.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.RABBIT_STEW), ForgeRegistries.ITEMS));
        MUTTON.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.MUTTON), ForgeRegistries.ITEMS));
        COOKED_MUTTON.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.COOKED_MUTTON), ForgeRegistries.ITEMS));
        BEETROOT.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.BEETROOT), ForgeRegistries.ITEMS));
        BEETROOT_SEEDS.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.BEETROOT_SEEDS), ForgeRegistries.ITEMS));
        BEETROOT_SOUP.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.BEETROOT_SOUP), ForgeRegistries.ITEMS));
        SWEET_BERRIES.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.SWEET_BERRIES), ForgeRegistries.ITEMS));
        GLOW_BERRIES.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.GLOW_BERRIES), ForgeRegistries.ITEMS));
        EGG.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.EGG), ForgeRegistries.ITEMS));
        SUGAR_CANE.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.SUGAR_CANE), ForgeRegistries.ITEMS));
        SUGAR.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.SUGAR), ForgeRegistries.ITEMS));
        PUMPKIN.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.PUMPKIN), ForgeRegistries.ITEMS));
        PUMPKIN_SEEDS.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.PUMPKIN_SEEDS), ForgeRegistries.ITEMS));
        WHEAT.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.WHEAT), ForgeRegistries.ITEMS));
        WHEAT_SEEDS.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.WHEAT_SEEDS), ForgeRegistries.ITEMS));
        COCOA_BEANS.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.COCOA_BEANS), ForgeRegistries.ITEMS));
        ARROW.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.ARROW), ForgeRegistries.ITEMS));
        SPIDER_EYE.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.SPIDER_EYE), ForgeRegistries.ITEMS));
        FERMENTED_SPIDER_EYE.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.FERMENTED_SPIDER_EYE), ForgeRegistries.ITEMS));
        BLAZE_ROD.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.BLAZE_ROD), ForgeRegistries.ITEMS));
        BLAZE_POWDER.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.BLAZE_POWDER), ForgeRegistries.ITEMS));
        MAGMA_CREAM.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.MAGMA_CREAM), ForgeRegistries.ITEMS));
        BONE.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.BONE), ForgeRegistries.ITEMS));
        BONE_MEAL.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.BONE_MEAL), ForgeRegistries.ITEMS));
        ENDER_EYE.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.ENDER_EYE), ForgeRegistries.ITEMS));
        ENDER_PEARL.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.ENDER_PEARL), ForgeRegistries.ITEMS));
        FEATHER.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.FEATHER), ForgeRegistries.ITEMS));
        LEATHER.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.LEATHER), ForgeRegistries.ITEMS));
        STRING.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.STRING), ForgeRegistries.ITEMS));
        INK_SACS.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.INK_SAC), ForgeRegistries.ITEMS));
        GLOW_INK_SACS.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.GLOW_INK_SAC), ForgeRegistries.ITEMS));
        STICK.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.STICK), ForgeRegistries.ITEMS));
        GLASS_BOTTLE.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.GLASS_BOTTLE), ForgeRegistries.ITEMS));
        SNOWBALL.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.SNOWBALL), ForgeRegistries.ITEMS));
        PAPER.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.PAPER), ForgeRegistries.ITEMS));
        FLINT.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.FLINT), ForgeRegistries.ITEMS));
        OAK_SAPLING.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.OAK_SAPLING), ForgeRegistries.ITEMS));
        SPRUCE_SAPLING.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.SPRUCE_SAPLING), ForgeRegistries.ITEMS));
        BIRCH_SAPLING.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.BIRCH_SAPLING), ForgeRegistries.ITEMS));
        JUNGLE_SAPLING.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.JUNGLE_SAPLING), ForgeRegistries.ITEMS));
        ACACIA_SAPLING.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.ACACIA_SAPLING), ForgeRegistries.ITEMS));
        DARK_OAK_SAPLING.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.DARK_OAK_SAPLING), ForgeRegistries.ITEMS));
        CHORUS_FRUIT.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.CHORUS_FRUIT), ForgeRegistries.ITEMS));
        SEAGRASS.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.SEAGRASS), ForgeRegistries.ITEMS));
        KELP.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.KELP), ForgeRegistries.ITEMS));
        BAMBOO.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.BAMBOO), ForgeRegistries.ITEMS));
        BROWN_MUSHROOM.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.BROWN_MUSHROOM), ForgeRegistries.ITEMS));
        RED_MUSHROOM.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.RED_MUSHROOM), ForgeRegistries.ITEMS));
        CRIMSON_FUNGUS.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.CRIMSON_FUNGUS), ForgeRegistries.ITEMS));
        WARPED_FUNGUS.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.WARPED_FUNGUS), ForgeRegistries.ITEMS));
        WITHER_ROSE.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.WITHER_ROSE.asItem()), ForgeRegistries.ITEMS));
        NETHER_WART.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.NETHER_WART), ForgeRegistries.ITEMS));
    }
}
