package net.sashiro.compressedblocks.world.level.item;

import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.Items;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;
import net.sashiro.compressedblocks.CompressedBlocks;
import net.sashiro.compressedblocks.util.StringUtils;

import java.util.ArrayList;

import static net.sashiro.compressedblocks.event.ModRegistryEvent.ITEMS;
import static net.sashiro.compressedblocks.event.ModRegistryEvent.PROPERTIES;
import static net.sashiro.compressedblocks.world.level.block.CustomBlocks.*;

@Mod.EventBusSubscriber(modid = CompressedBlocks.MOD_ID)
public class CustomItems {
    public static final ArrayList<String> CRATE_ITEMS = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> APPLES = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> MUSHROOM_STEW = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> BREAD = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> PORKCHOP = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> COOKED_PORKCHOP = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> COD = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> SALMON = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> TROPICAL_FISH = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> PUFFERFISH = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> COOKED_COD = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> COOKED_SALMON = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> CAKES = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> COOKIES = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> MELON_SLICES = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> MELON_SEEDS = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> DRIED_KELP = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> BEEF = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> COOKED_BEEF = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> CHICKEN = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> COOKED_CHICKEN = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> ROTTEN_FLESH = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> CARROTS = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> POTATOES = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> BAKED_POTATOES = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> POISONOUS_POTATOES = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> PUMPKIN_PIES = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> RABBIT = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> COOKED_RABBIT = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> RABBIT_STEW = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> MUTTON = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> COOKED_MUTTON = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> BEETROOT = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> BEETROOT_SEEDS = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> BEETROOT_SOUP = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> SWEET_BERRIES = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> GLOW_BERRIES = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> EGGS = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> SUGAR_CANES = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> SUGAR = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> PUMPKINS = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> PUMPKIN_SEEDS = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> WHEAT = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> WHEAT_SEEDS = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> COCOA_BEANS = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> ARROWS = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> SPIDER_EYES = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> FERMENTED_SPIDER_EYES = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> BLAZE_RODS = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> BLAZE_POWDER = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> MAGMA_CREAM = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> BONES = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> BONE_MEAL = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> ENDER_EYES = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> ENDER_PEARLS = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> FEATHERS = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> LEATHER = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> STRINGS = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> INK_SACS = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> GLOW_INK_SACS = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> STICKS = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> GLASS_BOTTLES = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> SNOWBALLS = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> PAPER = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> FLINTS = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> OAK_SAPLINGS = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> SPRUCE_SAPLINGS = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> BIRCH_SAPLINGS = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> JUNGLE_SAPLINGS = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> ACACIA_SAPLINGS = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> DARK_OAK_SAPLINGS = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> CHORUS_FRUITS = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> SEAGRASS = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> KELP = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> BAMBOO = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> BROWN_MUSHROOMS = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> RED_MUSHROOMS = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> CRIMSON_FUNGUS = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> WARPED_FUNGUS = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> WITHER_ROSES = new ArrayList<>();
    public static ArrayList<RegistryObject<Item>> NETHER_WARTS = new ArrayList<>();

    public static final RegistryObject<Item> LOGO_BLOCK_ITEM = ITEMS.register("logo_block", () -> new BlockItem(LOGO_BLOCK.get(), PROPERTIES));
    public static final RegistryObject<Item> STONE_0_ITEM = ITEMS.register("c0_stone", () -> new BlockItem(STONE_0.get(), PROPERTIES));
    public static final RegistryObject<Item> STONE_1_ITEM = ITEMS.register("c1_stone", () -> new BlockItem(STONE_1.get(), PROPERTIES));
    public static final RegistryObject<Item> STONE_2_ITEM = ITEMS.register("c2_stone", () -> new BlockItem(STONE_2.get(), PROPERTIES));
    public static final RegistryObject<Item> STONE_3_ITEM = ITEMS.register("c3_stone", () -> new BlockItem(STONE_3.get(), PROPERTIES));
    public static final RegistryObject<Item> STONE_4_ITEM = ITEMS.register("c4_stone", () -> new BlockItem(STONE_4.get(), PROPERTIES));
    public static final RegistryObject<Item> STONE_5_ITEM = ITEMS.register("c5_stone", () -> new BlockItem(STONE_5.get(), PROPERTIES));
    public static final RegistryObject<Item> STONE_6_ITEM = ITEMS.register("c6_stone", () -> new BlockItem(STONE_6.get(), PROPERTIES));
    public static final RegistryObject<Item> STONE_7_ITEM = ITEMS.register("c7_stone", () -> new BlockItem(STONE_7.get(), PROPERTIES));
    public static final RegistryObject<Item> STONE_8_ITEM = ITEMS.register("c8_stone", () -> new BlockItem(STONE_8.get(), PROPERTIES));
    public static final RegistryObject<Item> STONE_9_ITEM = ITEMS.register("c9_stone", () -> new BlockItem(STONE_9.get(), PROPERTIES));
    public static final RegistryObject<Item> GRANITE_0_ITEM = ITEMS.register("c0_granite", () -> new BlockItem(GRANITE_0.get(), PROPERTIES));
    public static final RegistryObject<Item> GRANITE_1_ITEM = ITEMS.register("c1_granite", () -> new BlockItem(GRANITE_1.get(), PROPERTIES));
    public static final RegistryObject<Item> GRANITE_2_ITEM = ITEMS.register("c2_granite", () -> new BlockItem(GRANITE_2.get(), PROPERTIES));
    public static final RegistryObject<Item> GRANITE_3_ITEM = ITEMS.register("c3_granite", () -> new BlockItem(GRANITE_3.get(), PROPERTIES));
    public static final RegistryObject<Item> GRANITE_4_ITEM = ITEMS.register("c4_granite", () -> new BlockItem(GRANITE_4.get(), PROPERTIES));
    public static final RegistryObject<Item> GRANITE_5_ITEM = ITEMS.register("c5_granite", () -> new BlockItem(GRANITE_5.get(), PROPERTIES));
    public static final RegistryObject<Item> GRANITE_6_ITEM = ITEMS.register("c6_granite", () -> new BlockItem(GRANITE_6.get(), PROPERTIES));
    public static final RegistryObject<Item> GRANITE_7_ITEM = ITEMS.register("c7_granite", () -> new BlockItem(GRANITE_7.get(), PROPERTIES));
    public static final RegistryObject<Item> GRANITE_8_ITEM = ITEMS.register("c8_granite", () -> new BlockItem(GRANITE_8.get(), PROPERTIES));
    public static final RegistryObject<Item> GRANITE_9_ITEM = ITEMS.register("c9_granite", () -> new BlockItem(GRANITE_9.get(), PROPERTIES));
    public static final RegistryObject<Item> DIORITE_0_ITEM = ITEMS.register("c0_diorite", () -> new BlockItem(DIORITE_0.get(), PROPERTIES));
    public static final RegistryObject<Item> DIORITE_1_ITEM = ITEMS.register("c1_diorite", () -> new BlockItem(DIORITE_1.get(), PROPERTIES));
    public static final RegistryObject<Item> DIORITE_2_ITEM = ITEMS.register("c2_diorite", () -> new BlockItem(DIORITE_2.get(), PROPERTIES));
    public static final RegistryObject<Item> DIORITE_3_ITEM = ITEMS.register("c3_diorite", () -> new BlockItem(DIORITE_3.get(), PROPERTIES));
    public static final RegistryObject<Item> DIORITE_4_ITEM = ITEMS.register("c4_diorite", () -> new BlockItem(DIORITE_4.get(), PROPERTIES));
    public static final RegistryObject<Item> DIORITE_5_ITEM = ITEMS.register("c5_diorite", () -> new BlockItem(DIORITE_5.get(), PROPERTIES));
    public static final RegistryObject<Item> DIORITE_6_ITEM = ITEMS.register("c6_diorite", () -> new BlockItem(DIORITE_6.get(), PROPERTIES));
    public static final RegistryObject<Item> DIORITE_7_ITEM = ITEMS.register("c7_diorite", () -> new BlockItem(DIORITE_7.get(), PROPERTIES));
    public static final RegistryObject<Item> DIORITE_8_ITEM = ITEMS.register("c8_diorite", () -> new BlockItem(DIORITE_8.get(), PROPERTIES));
    public static final RegistryObject<Item> DIORITE_9_ITEM = ITEMS.register("c9_diorite", () -> new BlockItem(DIORITE_9.get(), PROPERTIES));
    public static final RegistryObject<Item> ANDESITE_0_ITEM = ITEMS.register("c0_andesite", () -> new BlockItem(ANDESITE_0.get(), PROPERTIES));
    public static final RegistryObject<Item> ANDESITE_1_ITEM = ITEMS.register("c1_andesite", () -> new BlockItem(ANDESITE_1.get(), PROPERTIES));
    public static final RegistryObject<Item> ANDESITE_2_ITEM = ITEMS.register("c2_andesite", () -> new BlockItem(ANDESITE_2.get(), PROPERTIES));
    public static final RegistryObject<Item> ANDESITE_3_ITEM = ITEMS.register("c3_andesite", () -> new BlockItem(ANDESITE_3.get(), PROPERTIES));
    public static final RegistryObject<Item> ANDESITE_4_ITEM = ITEMS.register("c4_andesite", () -> new BlockItem(ANDESITE_4.get(), PROPERTIES));
    public static final RegistryObject<Item> ANDESITE_5_ITEM = ITEMS.register("c5_andesite", () -> new BlockItem(ANDESITE_5.get(), PROPERTIES));
    public static final RegistryObject<Item> ANDESITE_6_ITEM = ITEMS.register("c6_andesite", () -> new BlockItem(ANDESITE_6.get(), PROPERTIES));
    public static final RegistryObject<Item> ANDESITE_7_ITEM = ITEMS.register("c7_andesite", () -> new BlockItem(ANDESITE_7.get(), PROPERTIES));
    public static final RegistryObject<Item> ANDESITE_8_ITEM = ITEMS.register("c8_andesite", () -> new BlockItem(ANDESITE_8.get(), PROPERTIES));
    public static final RegistryObject<Item> ANDESITE_9_ITEM = ITEMS.register("c9_andesite", () -> new BlockItem(ANDESITE_9.get(), PROPERTIES));
    public static final RegistryObject<Item> DIRT_0_ITEM = ITEMS.register("c0_dirt", () -> new BlockItem(DIRT_0.get(), PROPERTIES));
    public static final RegistryObject<Item> DIRT_1_ITEM = ITEMS.register("c1_dirt", () -> new BlockItem(DIRT_1.get(), PROPERTIES));
    public static final RegistryObject<Item> DIRT_2_ITEM = ITEMS.register("c2_dirt", () -> new BlockItem(DIRT_2.get(), PROPERTIES));
    public static final RegistryObject<Item> DIRT_3_ITEM = ITEMS.register("c3_dirt", () -> new BlockItem(DIRT_3.get(), PROPERTIES));
    public static final RegistryObject<Item> DIRT_4_ITEM = ITEMS.register("c4_dirt", () -> new BlockItem(DIRT_4.get(), PROPERTIES));
    public static final RegistryObject<Item> DIRT_5_ITEM = ITEMS.register("c5_dirt", () -> new BlockItem(DIRT_5.get(), PROPERTIES));
    public static final RegistryObject<Item> DIRT_6_ITEM = ITEMS.register("c6_dirt", () -> new BlockItem(DIRT_6.get(), PROPERTIES));
    public static final RegistryObject<Item> DIRT_7_ITEM = ITEMS.register("c7_dirt", () -> new BlockItem(DIRT_7.get(), PROPERTIES));
    public static final RegistryObject<Item> DIRT_8_ITEM = ITEMS.register("c8_dirt", () -> new BlockItem(DIRT_8.get(), PROPERTIES));
    public static final RegistryObject<Item> DIRT_9_ITEM = ITEMS.register("c9_dirt", () -> new BlockItem(DIRT_9.get(), PROPERTIES));
    public static final RegistryObject<Item> CRIMSON_NYLIUM_0_ITEM = ITEMS.register("c0_crimson_nylium", () -> new BlockItem(CRIMSON_NYLIUM_0.get(), PROPERTIES));
    public static final RegistryObject<Item> CRIMSON_NYLIUM_1_ITEM = ITEMS.register("c1_crimson_nylium", () -> new BlockItem(CRIMSON_NYLIUM_1.get(), PROPERTIES));
    public static final RegistryObject<Item> CRIMSON_NYLIUM_2_ITEM = ITEMS.register("c2_crimson_nylium", () -> new BlockItem(CRIMSON_NYLIUM_2.get(), PROPERTIES));
    public static final RegistryObject<Item> CRIMSON_NYLIUM_3_ITEM = ITEMS.register("c3_crimson_nylium", () -> new BlockItem(CRIMSON_NYLIUM_3.get(), PROPERTIES));
    public static final RegistryObject<Item> CRIMSON_NYLIUM_4_ITEM = ITEMS.register("c4_crimson_nylium", () -> new BlockItem(CRIMSON_NYLIUM_4.get(), PROPERTIES));
    public static final RegistryObject<Item> CRIMSON_NYLIUM_5_ITEM = ITEMS.register("c5_crimson_nylium", () -> new BlockItem(CRIMSON_NYLIUM_5.get(), PROPERTIES));
    public static final RegistryObject<Item> CRIMSON_NYLIUM_6_ITEM = ITEMS.register("c6_crimson_nylium", () -> new BlockItem(CRIMSON_NYLIUM_6.get(), PROPERTIES));
    public static final RegistryObject<Item> CRIMSON_NYLIUM_7_ITEM = ITEMS.register("c7_crimson_nylium", () -> new BlockItem(CRIMSON_NYLIUM_7.get(), PROPERTIES));
    public static final RegistryObject<Item> CRIMSON_NYLIUM_8_ITEM = ITEMS.register("c8_crimson_nylium", () -> new BlockItem(CRIMSON_NYLIUM_8.get(), PROPERTIES));
    public static final RegistryObject<Item> CRIMSON_NYLIUM_9_ITEM = ITEMS.register("c9_crimson_nylium", () -> new BlockItem(CRIMSON_NYLIUM_9.get(), PROPERTIES));
    public static final RegistryObject<Item> WARPED_NYLIUM_0_ITEM = ITEMS.register("c0_warped_nylium", () -> new BlockItem(WARPED_NYLIUM_0.get(), PROPERTIES));
    public static final RegistryObject<Item> WARPED_NYLIUM_1_ITEM = ITEMS.register("c1_warped_nylium", () -> new BlockItem(WARPED_NYLIUM_1.get(), PROPERTIES));
    public static final RegistryObject<Item> WARPED_NYLIUM_2_ITEM = ITEMS.register("c2_warped_nylium", () -> new BlockItem(WARPED_NYLIUM_2.get(), PROPERTIES));
    public static final RegistryObject<Item> WARPED_NYLIUM_3_ITEM = ITEMS.register("c3_warped_nylium", () -> new BlockItem(WARPED_NYLIUM_3.get(), PROPERTIES));
    public static final RegistryObject<Item> WARPED_NYLIUM_4_ITEM = ITEMS.register("c4_warped_nylium", () -> new BlockItem(WARPED_NYLIUM_4.get(), PROPERTIES));
    public static final RegistryObject<Item> WARPED_NYLIUM_5_ITEM = ITEMS.register("c5_warped_nylium", () -> new BlockItem(WARPED_NYLIUM_5.get(), PROPERTIES));
    public static final RegistryObject<Item> WARPED_NYLIUM_6_ITEM = ITEMS.register("c6_warped_nylium", () -> new BlockItem(WARPED_NYLIUM_6.get(), PROPERTIES));
    public static final RegistryObject<Item> WARPED_NYLIUM_7_ITEM = ITEMS.register("c7_warped_nylium", () -> new BlockItem(WARPED_NYLIUM_7.get(), PROPERTIES));
    public static final RegistryObject<Item> WARPED_NYLIUM_8_ITEM = ITEMS.register("c8_warped_nylium", () -> new BlockItem(WARPED_NYLIUM_8.get(), PROPERTIES));
    public static final RegistryObject<Item> WARPED_NYLIUM_9_ITEM = ITEMS.register("c9_warped_nylium", () -> new BlockItem(WARPED_NYLIUM_9.get(), PROPERTIES));
    public static final RegistryObject<Item> COBBLESTONE_0_ITEM = ITEMS.register("c0_cobblestone", () -> new BlockItem(COBBLESTONE_0.get(), PROPERTIES));
    public static final RegistryObject<Item> COBBLESTONE_1_ITEM = ITEMS.register("c1_cobblestone", () -> new BlockItem(COBBLESTONE_1.get(), PROPERTIES));
    public static final RegistryObject<Item> COBBLESTONE_2_ITEM = ITEMS.register("c2_cobblestone", () -> new BlockItem(COBBLESTONE_2.get(), PROPERTIES));
    public static final RegistryObject<Item> COBBLESTONE_3_ITEM = ITEMS.register("c3_cobblestone", () -> new BlockItem(COBBLESTONE_3.get(), PROPERTIES));
    public static final RegistryObject<Item> COBBLESTONE_4_ITEM = ITEMS.register("c4_cobblestone", () -> new BlockItem(COBBLESTONE_4.get(), PROPERTIES));
    public static final RegistryObject<Item> COBBLESTONE_5_ITEM = ITEMS.register("c5_cobblestone", () -> new BlockItem(COBBLESTONE_5.get(), PROPERTIES));
    public static final RegistryObject<Item> COBBLESTONE_6_ITEM = ITEMS.register("c6_cobblestone", () -> new BlockItem(COBBLESTONE_6.get(), PROPERTIES));
    public static final RegistryObject<Item> COBBLESTONE_7_ITEM = ITEMS.register("c7_cobblestone", () -> new BlockItem(COBBLESTONE_7.get(), PROPERTIES));
    public static final RegistryObject<Item> COBBLESTONE_8_ITEM = ITEMS.register("c8_cobblestone", () -> new BlockItem(COBBLESTONE_8.get(), PROPERTIES));
    public static final RegistryObject<Item> COBBLESTONE_9_ITEM = ITEMS.register("c9_cobblestone", () -> new BlockItem(COBBLESTONE_9.get(), PROPERTIES));
    public static final RegistryObject<Item> CLAY_0_ITEM = ITEMS.register("c0_clay", () -> new BlockItem(CLAY_0.get(), PROPERTIES));
    public static final RegistryObject<Item> CLAY_1_ITEM = ITEMS.register("c1_clay", () -> new BlockItem(CLAY_1.get(), PROPERTIES));
    public static final RegistryObject<Item> CLAY_2_ITEM = ITEMS.register("c2_clay", () -> new BlockItem(CLAY_2.get(), PROPERTIES));
    public static final RegistryObject<Item> CLAY_3_ITEM = ITEMS.register("c3_clay", () -> new BlockItem(CLAY_3.get(), PROPERTIES));
    public static final RegistryObject<Item> CLAY_4_ITEM = ITEMS.register("c4_clay", () -> new BlockItem(CLAY_4.get(), PROPERTIES));
    public static final RegistryObject<Item> CLAY_5_ITEM = ITEMS.register("c5_clay", () -> new BlockItem(CLAY_5.get(), PROPERTIES));
    public static final RegistryObject<Item> CLAY_6_ITEM = ITEMS.register("c6_clay", () -> new BlockItem(CLAY_6.get(), PROPERTIES));
    public static final RegistryObject<Item> CLAY_7_ITEM = ITEMS.register("c7_clay", () -> new BlockItem(CLAY_7.get(), PROPERTIES));
    public static final RegistryObject<Item> CLAY_8_ITEM = ITEMS.register("c8_clay", () -> new BlockItem(CLAY_8.get(), PROPERTIES));
    public static final RegistryObject<Item> CLAY_9_ITEM = ITEMS.register("c9_clay", () -> new BlockItem(CLAY_9.get(), PROPERTIES));
    public static final RegistryObject<Item> SAND_0_ITEM = ITEMS.register("c0_sand", () -> new BlockItem(SAND_0.get(), PROPERTIES));
    public static final RegistryObject<Item> SAND_2_ITEM = ITEMS.register("c2_sand", () -> new BlockItem(SAND_2.get(), PROPERTIES));
    public static final RegistryObject<Item> SAND_1_ITEM = ITEMS.register("c1_sand", () -> new BlockItem(SAND_1.get(), PROPERTIES));
    public static final RegistryObject<Item> SAND_3_ITEM = ITEMS.register("c3_sand", () -> new BlockItem(SAND_3.get(), PROPERTIES));
    public static final RegistryObject<Item> SAND_4_ITEM = ITEMS.register("c4_sand", () -> new BlockItem(SAND_4.get(), PROPERTIES));
    public static final RegistryObject<Item> SAND_5_ITEM = ITEMS.register("c5_sand", () -> new BlockItem(SAND_5.get(), PROPERTIES));
    public static final RegistryObject<Item> SAND_6_ITEM = ITEMS.register("c6_sand", () -> new BlockItem(SAND_6.get(), PROPERTIES));
    public static final RegistryObject<Item> SAND_7_ITEM = ITEMS.register("c7_sand", () -> new BlockItem(SAND_7.get(), PROPERTIES));
    public static final RegistryObject<Item> SAND_8_ITEM = ITEMS.register("c8_sand", () -> new BlockItem(SAND_8.get(), PROPERTIES));
    public static final RegistryObject<Item> SAND_9_ITEM = ITEMS.register("c9_sand", () -> new BlockItem(SAND_9.get(), PROPERTIES));
    public static final RegistryObject<Item> RED_SAND_0_ITEM = ITEMS.register("c0_red_sand", () -> new BlockItem(RED_SAND_0.get(), PROPERTIES));
    public static final RegistryObject<Item> RED_SAND_1_ITEM = ITEMS.register("c1_red_sand", () -> new BlockItem(RED_SAND_1.get(), PROPERTIES));
    public static final RegistryObject<Item> RED_SAND_2_ITEM = ITEMS.register("c2_red_sand", () -> new BlockItem(RED_SAND_2.get(), PROPERTIES));
    public static final RegistryObject<Item> RED_SAND_3_ITEM = ITEMS.register("c3_red_sand", () -> new BlockItem(RED_SAND_3.get(), PROPERTIES));
    public static final RegistryObject<Item> RED_SAND_4_ITEM = ITEMS.register("c4_red_sand", () -> new BlockItem(RED_SAND_4.get(), PROPERTIES));
    public static final RegistryObject<Item> RED_SAND_5_ITEM = ITEMS.register("c5_red_sand", () -> new BlockItem(RED_SAND_5.get(), PROPERTIES));
    public static final RegistryObject<Item> RED_SAND_6_ITEM = ITEMS.register("c6_red_sand", () -> new BlockItem(RED_SAND_6.get(), PROPERTIES));
    public static final RegistryObject<Item> RED_SAND_7_ITEM = ITEMS.register("c7_red_sand", () -> new BlockItem(RED_SAND_7.get(), PROPERTIES));
    public static final RegistryObject<Item> RED_SAND_8_ITEM = ITEMS.register("c8_red_sand", () -> new BlockItem(RED_SAND_8.get(), PROPERTIES));
    public static final RegistryObject<Item> RED_SAND_9_ITEM = ITEMS.register("c9_red_sand", () -> new BlockItem(RED_SAND_9.get(), PROPERTIES));
    public static final RegistryObject<Item> GRAVEL_0_ITEM = ITEMS.register("c0_gravel", () -> new BlockItem(GRAVEL_0.get(), PROPERTIES));
    public static final RegistryObject<Item> GRAVEL_1_ITEM = ITEMS.register("c1_gravel", () -> new BlockItem(GRAVEL_1.get(), PROPERTIES));
    public static final RegistryObject<Item> GRAVEL_2_ITEM = ITEMS.register("c2_gravel", () -> new BlockItem(GRAVEL_2.get(), PROPERTIES));
    public static final RegistryObject<Item> GRAVEL_3_ITEM = ITEMS.register("c3_gravel", () -> new BlockItem(GRAVEL_3.get(), PROPERTIES));
    public static final RegistryObject<Item> GRAVEL_4_ITEM = ITEMS.register("c4_gravel", () -> new BlockItem(GRAVEL_4.get(), PROPERTIES));
    public static final RegistryObject<Item> GRAVEL_5_ITEM = ITEMS.register("c5_gravel", () -> new BlockItem(GRAVEL_5.get(), PROPERTIES));
    public static final RegistryObject<Item> GRAVEL_6_ITEM = ITEMS.register("c6_gravel", () -> new BlockItem(GRAVEL_6.get(), PROPERTIES));
    public static final RegistryObject<Item> GRAVEL_7_ITEM = ITEMS.register("c7_gravel", () -> new BlockItem(GRAVEL_7.get(), PROPERTIES));
    public static final RegistryObject<Item> GRAVEL_8_ITEM = ITEMS.register("c8_gravel", () -> new BlockItem(GRAVEL_8.get(), PROPERTIES));
    public static final RegistryObject<Item> GRAVEL_9_ITEM = ITEMS.register("c9_gravel", () -> new BlockItem(GRAVEL_9.get(), PROPERTIES));
    public static final RegistryObject<Item> SANDSTONE_0_ITEM = ITEMS.register("c0_sandstone", () -> new BlockItem(SANDSTONE_0.get(), PROPERTIES));
    public static final RegistryObject<Item> SANDSTONE_1_ITEM = ITEMS.register("c1_sandstone", () -> new BlockItem(SANDSTONE_1.get(), PROPERTIES));
    public static final RegistryObject<Item> SANDSTONE_2_ITEM = ITEMS.register("c2_sandstone", () -> new BlockItem(SANDSTONE_2.get(), PROPERTIES));
    public static final RegistryObject<Item> SANDSTONE_3_ITEM = ITEMS.register("c3_sandstone", () -> new BlockItem(SANDSTONE_3.get(), PROPERTIES));
    public static final RegistryObject<Item> SANDSTONE_4_ITEM = ITEMS.register("c4_sandstone", () -> new BlockItem(SANDSTONE_4.get(), PROPERTIES));
    public static final RegistryObject<Item> SANDSTONE_5_ITEM = ITEMS.register("c5_sandstone", () -> new BlockItem(SANDSTONE_5.get(), PROPERTIES));
    public static final RegistryObject<Item> SANDSTONE_6_ITEM = ITEMS.register("c6_sandstone", () -> new BlockItem(SANDSTONE_6.get(), PROPERTIES));
    public static final RegistryObject<Item> SANDSTONE_7_ITEM = ITEMS.register("c7_sandstone", () -> new BlockItem(SANDSTONE_7.get(), PROPERTIES));
    public static final RegistryObject<Item> SANDSTONE_8_ITEM = ITEMS.register("c8_sandstone", () -> new BlockItem(SANDSTONE_8.get(), PROPERTIES));
    public static final RegistryObject<Item> SANDSTONE_9_ITEM = ITEMS.register("c9_sandstone", () -> new BlockItem(SANDSTONE_9.get(), PROPERTIES));
    public static final RegistryObject<Item> RED_SANDSTONE_0_ITEM = ITEMS.register("c0_red_sandstone", () -> new BlockItem(RED_SANDSTONE_0.get(), PROPERTIES));
    public static final RegistryObject<Item> RED_SANDSTONE_1_ITEM = ITEMS.register("c1_red_sandstone", () -> new BlockItem(RED_SANDSTONE_1.get(), PROPERTIES));
    public static final RegistryObject<Item> RED_SANDSTONE_2_ITEM = ITEMS.register("c2_red_sandstone", () -> new BlockItem(RED_SANDSTONE_2.get(), PROPERTIES));
    public static final RegistryObject<Item> RED_SANDSTONE_3_ITEM = ITEMS.register("c3_red_sandstone", () -> new BlockItem(RED_SANDSTONE_3.get(), PROPERTIES));
    public static final RegistryObject<Item> RED_SANDSTONE_4_ITEM = ITEMS.register("c4_red_sandstone", () -> new BlockItem(RED_SANDSTONE_4.get(), PROPERTIES));
    public static final RegistryObject<Item> RED_SANDSTONE_5_ITEM = ITEMS.register("c5_red_sandstone", () -> new BlockItem(RED_SANDSTONE_5.get(), PROPERTIES));
    public static final RegistryObject<Item> RED_SANDSTONE_6_ITEM = ITEMS.register("c6_red_sandstone", () -> new BlockItem(RED_SANDSTONE_6.get(), PROPERTIES));
    public static final RegistryObject<Item> RED_SANDSTONE_7_ITEM = ITEMS.register("c7_red_sandstone", () -> new BlockItem(RED_SANDSTONE_7.get(), PROPERTIES));
    public static final RegistryObject<Item> RED_SANDSTONE_8_ITEM = ITEMS.register("c8_red_sandstone", () -> new BlockItem(RED_SANDSTONE_8.get(), PROPERTIES));
    public static final RegistryObject<Item> RED_SANDSTONE_9_ITEM = ITEMS.register("c9_red_sandstone", () -> new BlockItem(RED_SANDSTONE_9.get(), PROPERTIES));
    public static final RegistryObject<Item> COAL_ORE_0_ITEM = ITEMS.register("c0_coal_ore", () -> new BlockItem(COAL_ORE_0.get(), PROPERTIES));
    public static final RegistryObject<Item> COAL_ORE_1_ITEM = ITEMS.register("c1_coal_ore", () -> new BlockItem(COAL_ORE_1.get(), PROPERTIES));
    public static final RegistryObject<Item> COAL_ORE_2_ITEM = ITEMS.register("c2_coal_ore", () -> new BlockItem(COAL_ORE_2.get(), PROPERTIES));
    public static final RegistryObject<Item> COAL_ORE_3_ITEM = ITEMS.register("c3_coal_ore", () -> new BlockItem(COAL_ORE_3.get(), PROPERTIES));
    public static final RegistryObject<Item> COAL_ORE_4_ITEM = ITEMS.register("c4_coal_ore", () -> new BlockItem(COAL_ORE_4.get(), PROPERTIES));
    public static final RegistryObject<Item> COAL_ORE_5_ITEM = ITEMS.register("c5_coal_ore", () -> new BlockItem(COAL_ORE_5.get(), PROPERTIES));
    public static final RegistryObject<Item> COAL_ORE_6_ITEM = ITEMS.register("c6_coal_ore", () -> new BlockItem(COAL_ORE_6.get(), PROPERTIES));
    public static final RegistryObject<Item> COAL_ORE_7_ITEM = ITEMS.register("c7_coal_ore", () -> new BlockItem(COAL_ORE_7.get(), PROPERTIES));
    public static final RegistryObject<Item> COAL_ORE_8_ITEM = ITEMS.register("c8_coal_ore", () -> new BlockItem(COAL_ORE_8.get(), PROPERTIES));
    public static final RegistryObject<Item> COAL_ORE_9_ITEM = ITEMS.register("c9_coal_ore", () -> new BlockItem(COAL_ORE_9.get(), PROPERTIES));
    public static final RegistryObject<Item> IRON_ORE_0_ITEM = ITEMS.register("c0_iron_ore", () -> new BlockItem(IRON_ORE_0.get(), PROPERTIES));
    public static final RegistryObject<Item> IRON_ORE_1_ITEM = ITEMS.register("c1_iron_ore", () -> new BlockItem(IRON_ORE_1.get(), PROPERTIES));
    public static final RegistryObject<Item> IRON_ORE_2_ITEM = ITEMS.register("c2_iron_ore", () -> new BlockItem(IRON_ORE_2.get(), PROPERTIES));
    public static final RegistryObject<Item> IRON_ORE_3_ITEM = ITEMS.register("c3_iron_ore", () -> new BlockItem(IRON_ORE_3.get(), PROPERTIES));
    public static final RegistryObject<Item> IRON_ORE_4_ITEM = ITEMS.register("c4_iron_ore", () -> new BlockItem(IRON_ORE_4.get(), PROPERTIES));
    public static final RegistryObject<Item> IRON_ORE_5_ITEM = ITEMS.register("c5_iron_ore", () -> new BlockItem(IRON_ORE_5.get(), PROPERTIES));
    public static final RegistryObject<Item> IRON_ORE_6_ITEM = ITEMS.register("c6_iron_ore", () -> new BlockItem(IRON_ORE_6.get(), PROPERTIES));
    public static final RegistryObject<Item> IRON_ORE_7_ITEM = ITEMS.register("c7_iron_ore", () -> new BlockItem(IRON_ORE_7.get(), PROPERTIES));
    public static final RegistryObject<Item> IRON_ORE_8_ITEM = ITEMS.register("c8_iron_ore", () -> new BlockItem(IRON_ORE_8.get(), PROPERTIES));
    public static final RegistryObject<Item> IRON_ORE_9_ITEM = ITEMS.register("c9_iron_ore", () -> new BlockItem(IRON_ORE_9.get(), PROPERTIES));
    public static final RegistryObject<Item> GOLD_ORE_0_ITEM = ITEMS.register("c0_gold_ore", () -> new BlockItem(GOLD_ORE_0.get(), PROPERTIES));
    public static final RegistryObject<Item> GOLD_ORE_1_ITEM = ITEMS.register("c1_gold_ore", () -> new BlockItem(GOLD_ORE_1.get(), PROPERTIES));
    public static final RegistryObject<Item> GOLD_ORE_2_ITEM = ITEMS.register("c2_gold_ore", () -> new BlockItem(GOLD_ORE_2.get(), PROPERTIES));
    public static final RegistryObject<Item> GOLD_ORE_3_ITEM = ITEMS.register("c3_gold_ore", () -> new BlockItem(GOLD_ORE_3.get(), PROPERTIES));
    public static final RegistryObject<Item> GOLD_ORE_4_ITEM = ITEMS.register("c4_gold_ore", () -> new BlockItem(GOLD_ORE_4.get(), PROPERTIES));
    public static final RegistryObject<Item> GOLD_ORE_5_ITEM = ITEMS.register("c5_gold_ore", () -> new BlockItem(GOLD_ORE_5.get(), PROPERTIES));
    public static final RegistryObject<Item> GOLD_ORE_6_ITEM = ITEMS.register("c6_gold_ore", () -> new BlockItem(GOLD_ORE_6.get(), PROPERTIES));
    public static final RegistryObject<Item> GOLD_ORE_7_ITEM = ITEMS.register("c7_gold_ore", () -> new BlockItem(GOLD_ORE_7.get(), PROPERTIES));
    public static final RegistryObject<Item> GOLD_ORE_8_ITEM = ITEMS.register("c8_gold_ore", () -> new BlockItem(GOLD_ORE_8.get(), PROPERTIES));
    public static final RegistryObject<Item> GOLD_ORE_9_ITEM = ITEMS.register("c9_gold_ore", () -> new BlockItem(GOLD_ORE_9.get(), PROPERTIES));
    public static final RegistryObject<Item> NETHER_GOLD_ORE_0_ITEM = ITEMS.register("c0_nether_gold_ore", () -> new BlockItem(NETHER_GOLD_ORE_0.get(), PROPERTIES));
    public static final RegistryObject<Item> NETHER_GOLD_ORE_1_ITEM = ITEMS.register("c1_nether_gold_ore", () -> new BlockItem(NETHER_GOLD_ORE_1.get(), PROPERTIES));
    public static final RegistryObject<Item> NETHER_GOLD_ORE_2_ITEM = ITEMS.register("c2_nether_gold_ore", () -> new BlockItem(NETHER_GOLD_ORE_2.get(), PROPERTIES));
    public static final RegistryObject<Item> NETHER_GOLD_ORE_3_ITEM = ITEMS.register("c3_nether_gold_ore", () -> new BlockItem(NETHER_GOLD_ORE_3.get(), PROPERTIES));
    public static final RegistryObject<Item> NETHER_GOLD_ORE_4_ITEM = ITEMS.register("c4_nether_gold_ore", () -> new BlockItem(NETHER_GOLD_ORE_4.get(), PROPERTIES));
    public static final RegistryObject<Item> NETHER_GOLD_ORE_5_ITEM = ITEMS.register("c5_nether_gold_ore", () -> new BlockItem(NETHER_GOLD_ORE_5.get(), PROPERTIES));
    public static final RegistryObject<Item> NETHER_GOLD_ORE_6_ITEM = ITEMS.register("c6_nether_gold_ore", () -> new BlockItem(NETHER_GOLD_ORE_6.get(), PROPERTIES));
    public static final RegistryObject<Item> NETHER_GOLD_ORE_7_ITEM = ITEMS.register("c7_nether_gold_ore", () -> new BlockItem(NETHER_GOLD_ORE_7.get(), PROPERTIES));
    public static final RegistryObject<Item> NETHER_GOLD_ORE_8_ITEM = ITEMS.register("c8_nether_gold_ore", () -> new BlockItem(NETHER_GOLD_ORE_8.get(), PROPERTIES));
    public static final RegistryObject<Item> NETHER_GOLD_ORE_9_ITEM = ITEMS.register("c9_nether_gold_ore", () -> new BlockItem(NETHER_GOLD_ORE_9.get(), PROPERTIES));
    public static final RegistryObject<Item> NETHER_QUARTZ_ORE_0_ITEM = ITEMS.register("c0_nether_quartz_ore", () -> new BlockItem(NETHER_QUARTZ_ORE_0.get(), PROPERTIES));
    public static final RegistryObject<Item> NETHER_QUARTZ_ORE_1_ITEM = ITEMS.register("c1_nether_quartz_ore", () -> new BlockItem(NETHER_QUARTZ_ORE_1.get(), PROPERTIES));
    public static final RegistryObject<Item> NETHER_QUARTZ_ORE_2_ITEM = ITEMS.register("c2_nether_quartz_ore", () -> new BlockItem(NETHER_QUARTZ_ORE_2.get(), PROPERTIES));
    public static final RegistryObject<Item> NETHER_QUARTZ_ORE_3_ITEM = ITEMS.register("c3_nether_quartz_ore", () -> new BlockItem(NETHER_QUARTZ_ORE_3.get(), PROPERTIES));
    public static final RegistryObject<Item> NETHER_QUARTZ_ORE_4_ITEM = ITEMS.register("c4_nether_quartz_ore", () -> new BlockItem(NETHER_QUARTZ_ORE_4.get(), PROPERTIES));
    public static final RegistryObject<Item> NETHER_QUARTZ_ORE_5_ITEM = ITEMS.register("c5_nether_quartz_ore", () -> new BlockItem(NETHER_QUARTZ_ORE_5.get(), PROPERTIES));
    public static final RegistryObject<Item> NETHER_QUARTZ_ORE_6_ITEM = ITEMS.register("c6_nether_quartz_ore", () -> new BlockItem(NETHER_QUARTZ_ORE_6.get(), PROPERTIES));
    public static final RegistryObject<Item> NETHER_QUARTZ_ORE_7_ITEM = ITEMS.register("c7_nether_quartz_ore", () -> new BlockItem(NETHER_QUARTZ_ORE_7.get(), PROPERTIES));
    public static final RegistryObject<Item> NETHER_QUARTZ_ORE_8_ITEM = ITEMS.register("c8_nether_quartz_ore", () -> new BlockItem(NETHER_QUARTZ_ORE_8.get(), PROPERTIES));
    public static final RegistryObject<Item> NETHER_QUARTZ_ORE_9_ITEM = ITEMS.register("c9_nether_quartz_ore", () -> new BlockItem(NETHER_QUARTZ_ORE_9.get(), PROPERTIES));
    public static final RegistryObject<Item> LAPIS_ORE_0_ITEM = ITEMS.register("c0_lapis_ore", () -> new BlockItem(LAPIS_ORE_0.get(), PROPERTIES));
    public static final RegistryObject<Item> LAPIS_ORE_1_ITEM = ITEMS.register("c1_lapis_ore", () -> new BlockItem(LAPIS_ORE_1.get(), PROPERTIES));
    public static final RegistryObject<Item> LAPIS_ORE_2_ITEM = ITEMS.register("c2_lapis_ore", () -> new BlockItem(LAPIS_ORE_2.get(), PROPERTIES));
    public static final RegistryObject<Item> LAPIS_ORE_3_ITEM = ITEMS.register("c3_lapis_ore", () -> new BlockItem(LAPIS_ORE_3.get(), PROPERTIES));
    public static final RegistryObject<Item> LAPIS_ORE_4_ITEM = ITEMS.register("c4_lapis_ore", () -> new BlockItem(LAPIS_ORE_4.get(), PROPERTIES));
    public static final RegistryObject<Item> LAPIS_ORE_5_ITEM = ITEMS.register("c5_lapis_ore", () -> new BlockItem(LAPIS_ORE_5.get(), PROPERTIES));
    public static final RegistryObject<Item> LAPIS_ORE_6_ITEM = ITEMS.register("c6_lapis_ore", () -> new BlockItem(LAPIS_ORE_6.get(), PROPERTIES));
    public static final RegistryObject<Item> LAPIS_ORE_7_ITEM = ITEMS.register("c7_lapis_ore", () -> new BlockItem(LAPIS_ORE_7.get(), PROPERTIES));
    public static final RegistryObject<Item> LAPIS_ORE_8_ITEM = ITEMS.register("c8_lapis_ore", () -> new BlockItem(LAPIS_ORE_8.get(), PROPERTIES));
    public static final RegistryObject<Item> LAPIS_ORE_9_ITEM = ITEMS.register("c9_lapis_ore", () -> new BlockItem(LAPIS_ORE_9.get(), PROPERTIES));
    public static final RegistryObject<Item> REDSTONE_ORE_0_ITEM = ITEMS.register("c0_redstone_ore", () -> new BlockItem(REDSTONE_ORE_0.get(), PROPERTIES));
    public static final RegistryObject<Item> REDSTONE_ORE_1_ITEM = ITEMS.register("c1_redstone_ore", () -> new BlockItem(REDSTONE_ORE_1.get(), PROPERTIES));
    public static final RegistryObject<Item> REDSTONE_ORE_2_ITEM = ITEMS.register("c2_redstone_ore", () -> new BlockItem(REDSTONE_ORE_2.get(), PROPERTIES));
    public static final RegistryObject<Item> REDSTONE_ORE_3_ITEM = ITEMS.register("c3_redstone_ore", () -> new BlockItem(REDSTONE_ORE_3.get(), PROPERTIES));
    public static final RegistryObject<Item> REDSTONE_ORE_4_ITEM = ITEMS.register("c4_redstone_ore", () -> new BlockItem(REDSTONE_ORE_4.get(), PROPERTIES));
    public static final RegistryObject<Item> REDSTONE_ORE_5_ITEM = ITEMS.register("c5_redstone_ore", () -> new BlockItem(REDSTONE_ORE_5.get(), PROPERTIES));
    public static final RegistryObject<Item> REDSTONE_ORE_6_ITEM = ITEMS.register("c6_redstone_ore", () -> new BlockItem(REDSTONE_ORE_6.get(), PROPERTIES));
    public static final RegistryObject<Item> REDSTONE_ORE_7_ITEM = ITEMS.register("c7_redstone_ore", () -> new BlockItem(REDSTONE_ORE_7.get(), PROPERTIES));
    public static final RegistryObject<Item> REDSTONE_ORE_8_ITEM = ITEMS.register("c8_redstone_ore", () -> new BlockItem(REDSTONE_ORE_8.get(), PROPERTIES));
    public static final RegistryObject<Item> REDSTONE_ORE_9_ITEM = ITEMS.register("c9_redstone_ore", () -> new BlockItem(REDSTONE_ORE_9.get(), PROPERTIES));
    public static final RegistryObject<Item> IRON_BLOCK_0_ITEM = ITEMS.register("c0_iron_block", () -> new BlockItem(IRON_BLOCK_0.get(), PROPERTIES));
    public static final RegistryObject<Item> IRON_BLOCK_1_ITEM = ITEMS.register("c1_iron_block", () -> new BlockItem(IRON_BLOCK_1.get(), PROPERTIES));
    public static final RegistryObject<Item> IRON_BLOCK_2_ITEM = ITEMS.register("c2_iron_block", () -> new BlockItem(IRON_BLOCK_2.get(), PROPERTIES));
    public static final RegistryObject<Item> IRON_BLOCK_3_ITEM = ITEMS.register("c3_iron_block", () -> new BlockItem(IRON_BLOCK_3.get(), PROPERTIES));
    public static final RegistryObject<Item> IRON_BLOCK_4_ITEM = ITEMS.register("c4_iron_block", () -> new BlockItem(IRON_BLOCK_4.get(), PROPERTIES));
    public static final RegistryObject<Item> IRON_BLOCK_5_ITEM = ITEMS.register("c5_iron_block", () -> new BlockItem(IRON_BLOCK_5.get(), PROPERTIES));
    public static final RegistryObject<Item> IRON_BLOCK_6_ITEM = ITEMS.register("c6_iron_block", () -> new BlockItem(IRON_BLOCK_6.get(), PROPERTIES));
    public static final RegistryObject<Item> IRON_BLOCK_7_ITEM = ITEMS.register("c7_iron_block", () -> new BlockItem(IRON_BLOCK_7.get(), PROPERTIES));
    public static final RegistryObject<Item> IRON_BLOCK_8_ITEM = ITEMS.register("c8_iron_block", () -> new BlockItem(IRON_BLOCK_8.get(), PROPERTIES));
    public static final RegistryObject<Item> IRON_BLOCK_9_ITEM = ITEMS.register("c9_iron_block", () -> new BlockItem(IRON_BLOCK_9.get(), PROPERTIES));
    public static final RegistryObject<Item> GOLD_BLOCK_0_ITEM = ITEMS.register("c0_gold_block", () -> new BlockItem(GOLD_BLOCK_0.get(), PROPERTIES));
    public static final RegistryObject<Item> GOLD_BLOCK_1_ITEM = ITEMS.register("c1_gold_block", () -> new BlockItem(GOLD_BLOCK_1.get(), PROPERTIES));
    public static final RegistryObject<Item> GOLD_BLOCK_2_ITEM = ITEMS.register("c2_gold_block", () -> new BlockItem(GOLD_BLOCK_2.get(), PROPERTIES));
    public static final RegistryObject<Item> GOLD_BLOCK_3_ITEM = ITEMS.register("c3_gold_block", () -> new BlockItem(GOLD_BLOCK_3.get(), PROPERTIES));
    public static final RegistryObject<Item> GOLD_BLOCK_4_ITEM = ITEMS.register("c4_gold_block", () -> new BlockItem(GOLD_BLOCK_4.get(), PROPERTIES));
    public static final RegistryObject<Item> GOLD_BLOCK_5_ITEM = ITEMS.register("c5_gold_block", () -> new BlockItem(GOLD_BLOCK_5.get(), PROPERTIES));
    public static final RegistryObject<Item> GOLD_BLOCK_6_ITEM = ITEMS.register("c6_gold_block", () -> new BlockItem(GOLD_BLOCK_6.get(), PROPERTIES));
    public static final RegistryObject<Item> GOLD_BLOCK_7_ITEM = ITEMS.register("c7_gold_block", () -> new BlockItem(GOLD_BLOCK_7.get(), PROPERTIES));
    public static final RegistryObject<Item> GOLD_BLOCK_8_ITEM = ITEMS.register("c8_gold_block", () -> new BlockItem(GOLD_BLOCK_8.get(), PROPERTIES));
    public static final RegistryObject<Item> GOLD_BLOCK_9_ITEM = ITEMS.register("c9_gold_block", () -> new BlockItem(GOLD_BLOCK_9.get(), PROPERTIES));
    public static final RegistryObject<Item> LAPIS_BLOCK_0_ITEM = ITEMS.register("c0_lapis_block", () -> new BlockItem(LAPIS_BLOCK_0.get(), PROPERTIES));
    public static final RegistryObject<Item> LAPIS_BLOCK_1_ITEM = ITEMS.register("c1_lapis_block", () -> new BlockItem(LAPIS_BLOCK_1.get(), PROPERTIES));
    public static final RegistryObject<Item> LAPIS_BLOCK_2_ITEM = ITEMS.register("c2_lapis_block", () -> new BlockItem(LAPIS_BLOCK_2.get(), PROPERTIES));
    public static final RegistryObject<Item> LAPIS_BLOCK_3_ITEM = ITEMS.register("c3_lapis_block", () -> new BlockItem(LAPIS_BLOCK_3.get(), PROPERTIES));
    public static final RegistryObject<Item> LAPIS_BLOCK_4_ITEM = ITEMS.register("c4_lapis_block", () -> new BlockItem(LAPIS_BLOCK_4.get(), PROPERTIES));
    public static final RegistryObject<Item> LAPIS_BLOCK_5_ITEM = ITEMS.register("c5_lapis_block", () -> new BlockItem(LAPIS_BLOCK_5.get(), PROPERTIES));
    public static final RegistryObject<Item> LAPIS_BLOCK_6_ITEM = ITEMS.register("c6_lapis_block", () -> new BlockItem(LAPIS_BLOCK_6.get(), PROPERTIES));
    public static final RegistryObject<Item> LAPIS_BLOCK_7_ITEM = ITEMS.register("c7_lapis_block", () -> new BlockItem(LAPIS_BLOCK_7.get(), PROPERTIES));
    public static final RegistryObject<Item> LAPIS_BLOCK_8_ITEM = ITEMS.register("c8_lapis_block", () -> new BlockItem(LAPIS_BLOCK_8.get(), PROPERTIES));
    public static final RegistryObject<Item> LAPIS_BLOCK_9_ITEM = ITEMS.register("c9_lapis_block", () -> new BlockItem(LAPIS_BLOCK_9.get(), PROPERTIES));
    public static final RegistryObject<Item> REDSTONE_BLOCK_0_ITEM = ITEMS.register("c0_redstone_block", () -> new BlockItem(REDSTONE_BLOCK_0.get(), PROPERTIES));
    public static final RegistryObject<Item> REDSTONE_BLOCK_1_ITEM = ITEMS.register("c1_redstone_block", () -> new BlockItem(REDSTONE_BLOCK_1.get(), PROPERTIES));
    public static final RegistryObject<Item> REDSTONE_BLOCK_2_ITEM = ITEMS.register("c2_redstone_block", () -> new BlockItem(REDSTONE_BLOCK_2.get(), PROPERTIES));
    public static final RegistryObject<Item> REDSTONE_BLOCK_3_ITEM = ITEMS.register("c3_redstone_block", () -> new BlockItem(REDSTONE_BLOCK_3.get(), PROPERTIES));
    public static final RegistryObject<Item> REDSTONE_BLOCK_4_ITEM = ITEMS.register("c4_redstone_block", () -> new BlockItem(REDSTONE_BLOCK_4.get(), PROPERTIES));
    public static final RegistryObject<Item> REDSTONE_BLOCK_5_ITEM = ITEMS.register("c5_redstone_block", () -> new BlockItem(REDSTONE_BLOCK_5.get(), PROPERTIES));
    public static final RegistryObject<Item> REDSTONE_BLOCK_6_ITEM = ITEMS.register("c6_redstone_block", () -> new BlockItem(REDSTONE_BLOCK_6.get(), PROPERTIES));
    public static final RegistryObject<Item> REDSTONE_BLOCK_7_ITEM = ITEMS.register("c7_redstone_block", () -> new BlockItem(REDSTONE_BLOCK_7.get(), PROPERTIES));
    public static final RegistryObject<Item> REDSTONE_BLOCK_8_ITEM = ITEMS.register("c8_redstone_block", () -> new BlockItem(REDSTONE_BLOCK_8.get(), PROPERTIES));
    public static final RegistryObject<Item> REDSTONE_BLOCK_9_ITEM = ITEMS.register("c9_redstone_block", () -> new BlockItem(REDSTONE_BLOCK_9.get(), PROPERTIES));
    public static final RegistryObject<Item> COAL_BLOCK_0_ITEM = ITEMS.register("c0_coal_block", () -> new BlockItem(COAL_BLOCK_0.get(), PROPERTIES));
    public static final RegistryObject<Item> COAL_BLOCK_1_ITEM = ITEMS.register("c1_coal_block", () -> new BlockItem(COAL_BLOCK_1.get(), PROPERTIES));
    public static final RegistryObject<Item> COAL_BLOCK_2_ITEM = ITEMS.register("c2_coal_block", () -> new BlockItem(COAL_BLOCK_2.get(), PROPERTIES));
    public static final RegistryObject<Item> COAL_BLOCK_3_ITEM = ITEMS.register("c3_coal_block", () -> new BlockItem(COAL_BLOCK_3.get(), PROPERTIES));
    public static final RegistryObject<Item> COAL_BLOCK_4_ITEM = ITEMS.register("c4_coal_block", () -> new BlockItem(COAL_BLOCK_4.get(), PROPERTIES));
    public static final RegistryObject<Item> COAL_BLOCK_5_ITEM = ITEMS.register("c5_coal_block", () -> new BlockItem(COAL_BLOCK_5.get(), PROPERTIES));
    public static final RegistryObject<Item> COAL_BLOCK_6_ITEM = ITEMS.register("c6_coal_block", () -> new BlockItem(COAL_BLOCK_6.get(), PROPERTIES));
    public static final RegistryObject<Item> COAL_BLOCK_7_ITEM = ITEMS.register("c7_coal_block", () -> new BlockItem(COAL_BLOCK_7.get(), PROPERTIES));
    public static final RegistryObject<Item> COAL_BLOCK_8_ITEM = ITEMS.register("c8_coal_block", () -> new BlockItem(COAL_BLOCK_8.get(), PROPERTIES));
    public static final RegistryObject<Item> COAL_BLOCK_9_ITEM = ITEMS.register("c9_coal_block", () -> new BlockItem(COAL_BLOCK_9.get(), PROPERTIES));
    public static final RegistryObject<Item> SLIME_BLOCK_0_ITEM = ITEMS.register("c0_slime_block", () -> new BlockItem(SLIME_BLOCK_0.get(), PROPERTIES));
    public static final RegistryObject<Item> SLIME_BLOCK_1_ITEM = ITEMS.register("c1_slime_block", () -> new BlockItem(SLIME_BLOCK_1.get(), PROPERTIES));
    public static final RegistryObject<Item> SLIME_BLOCK_2_ITEM = ITEMS.register("c2_slime_block", () -> new BlockItem(SLIME_BLOCK_2.get(), PROPERTIES));
    public static final RegistryObject<Item> SLIME_BLOCK_3_ITEM = ITEMS.register("c3_slime_block", () -> new BlockItem(SLIME_BLOCK_3.get(), PROPERTIES));
    public static final RegistryObject<Item> SLIME_BLOCK_4_ITEM = ITEMS.register("c4_slime_block", () -> new BlockItem(SLIME_BLOCK_4.get(), PROPERTIES));
    public static final RegistryObject<Item> SLIME_BLOCK_5_ITEM = ITEMS.register("c5_slime_block", () -> new BlockItem(SLIME_BLOCK_5.get(), PROPERTIES));
    public static final RegistryObject<Item> SLIME_BLOCK_6_ITEM = ITEMS.register("c6_slime_block", () -> new BlockItem(SLIME_BLOCK_6.get(), PROPERTIES));
    public static final RegistryObject<Item> SLIME_BLOCK_7_ITEM = ITEMS.register("c7_slime_block", () -> new BlockItem(SLIME_BLOCK_7.get(), PROPERTIES));
    public static final RegistryObject<Item> SLIME_BLOCK_8_ITEM = ITEMS.register("c8_slime_block", () -> new BlockItem(SLIME_BLOCK_8.get(), PROPERTIES));
    public static final RegistryObject<Item> SLIME_BLOCK_9_ITEM = ITEMS.register("c9_slime_block", () -> new BlockItem(SLIME_BLOCK_9.get(), PROPERTIES));
    public static final RegistryObject<Item> BRICKS_0_ITEM = ITEMS.register("c0_bricks", () -> new BlockItem(BRICKS_0.get(), PROPERTIES));
    public static final RegistryObject<Item> BRICKS_1_ITEM = ITEMS.register("c1_bricks", () -> new BlockItem(BRICKS_1.get(), PROPERTIES));
    public static final RegistryObject<Item> BRICKS_2_ITEM = ITEMS.register("c2_bricks", () -> new BlockItem(BRICKS_2.get(), PROPERTIES));
    public static final RegistryObject<Item> BRICKS_3_ITEM = ITEMS.register("c3_bricks", () -> new BlockItem(BRICKS_3.get(), PROPERTIES));
    public static final RegistryObject<Item> BRICKS_4_ITEM = ITEMS.register("c4_bricks", () -> new BlockItem(BRICKS_4.get(), PROPERTIES));
    public static final RegistryObject<Item> BRICKS_5_ITEM = ITEMS.register("c5_bricks", () -> new BlockItem(BRICKS_5.get(), PROPERTIES));
    public static final RegistryObject<Item> BRICKS_6_ITEM = ITEMS.register("c6_bricks", () -> new BlockItem(BRICKS_6.get(), PROPERTIES));
    public static final RegistryObject<Item> BRICKS_7_ITEM = ITEMS.register("c7_bricks", () -> new BlockItem(BRICKS_7.get(), PROPERTIES));
    public static final RegistryObject<Item> BRICKS_8_ITEM = ITEMS.register("c8_bricks", () -> new BlockItem(BRICKS_8.get(), PROPERTIES));
    public static final RegistryObject<Item> BRICKS_9_ITEM = ITEMS.register("c9_bricks", () -> new BlockItem(BRICKS_9.get(), PROPERTIES));
    public static final RegistryObject<Item> STONE_BRICKS_0_ITEM = ITEMS.register("c0_stone_bricks", () -> new BlockItem(STONE_BRICKS_0.get(), PROPERTIES));
    public static final RegistryObject<Item> STONE_BRICKS_1_ITEM = ITEMS.register("c1_stone_bricks", () -> new BlockItem(STONE_BRICKS_1.get(), PROPERTIES));
    public static final RegistryObject<Item> STONE_BRICKS_2_ITEM = ITEMS.register("c2_stone_bricks", () -> new BlockItem(STONE_BRICKS_2.get(), PROPERTIES));
    public static final RegistryObject<Item> STONE_BRICKS_3_ITEM = ITEMS.register("c3_stone_bricks", () -> new BlockItem(STONE_BRICKS_3.get(), PROPERTIES));
    public static final RegistryObject<Item> STONE_BRICKS_4_ITEM = ITEMS.register("c4_stone_bricks", () -> new BlockItem(STONE_BRICKS_4.get(), PROPERTIES));
    public static final RegistryObject<Item> STONE_BRICKS_5_ITEM = ITEMS.register("c5_stone_bricks", () -> new BlockItem(STONE_BRICKS_5.get(), PROPERTIES));
    public static final RegistryObject<Item> STONE_BRICKS_6_ITEM = ITEMS.register("c6_stone_bricks", () -> new BlockItem(STONE_BRICKS_6.get(), PROPERTIES));
    public static final RegistryObject<Item> STONE_BRICKS_7_ITEM = ITEMS.register("c7_stone_bricks", () -> new BlockItem(STONE_BRICKS_7.get(), PROPERTIES));
    public static final RegistryObject<Item> STONE_BRICKS_8_ITEM = ITEMS.register("c8_stone_bricks", () -> new BlockItem(STONE_BRICKS_8.get(), PROPERTIES));
    public static final RegistryObject<Item> STONE_BRICKS_9_ITEM = ITEMS.register("c9_stone_bricks", () -> new BlockItem(STONE_BRICKS_9.get(), PROPERTIES));
    public static final RegistryObject<Item> NETHERRACK_0_ITEM = ITEMS.register("c0_netherrack", () -> new BlockItem(NETHERRACK_0.get(), PROPERTIES));
    public static final RegistryObject<Item> NETHERRACK_1_ITEM = ITEMS.register("c1_netherrack", () -> new BlockItem(NETHERRACK_1.get(), PROPERTIES));
    public static final RegistryObject<Item> NETHERRACK_2_ITEM = ITEMS.register("c2_netherrack", () -> new BlockItem(NETHERRACK_2.get(), PROPERTIES));
    public static final RegistryObject<Item> NETHERRACK_3_ITEM = ITEMS.register("c3_netherrack", () -> new BlockItem(NETHERRACK_3.get(), PROPERTIES));
    public static final RegistryObject<Item> NETHERRACK_4_ITEM = ITEMS.register("c4_netherrack", () -> new BlockItem(NETHERRACK_4.get(), PROPERTIES));
    public static final RegistryObject<Item> NETHERRACK_5_ITEM = ITEMS.register("c5_netherrack", () -> new BlockItem(NETHERRACK_5.get(), PROPERTIES));
    public static final RegistryObject<Item> NETHERRACK_6_ITEM = ITEMS.register("c6_netherrack", () -> new BlockItem(NETHERRACK_6.get(), PROPERTIES));
    public static final RegistryObject<Item> NETHERRACK_7_ITEM = ITEMS.register("c7_netherrack", () -> new BlockItem(NETHERRACK_7.get(), PROPERTIES));
    public static final RegistryObject<Item> NETHERRACK_8_ITEM = ITEMS.register("c8_netherrack", () -> new BlockItem(NETHERRACK_8.get(), PROPERTIES));
    public static final RegistryObject<Item> NETHERRACK_9_ITEM = ITEMS.register("c9_netherrack", () -> new BlockItem(NETHERRACK_9.get(), PROPERTIES));
    public static final RegistryObject<Item> NETHER_BRICKS_0_ITEM = ITEMS.register("c0_nether_bricks", () -> new BlockItem(NETHER_BRICKS_0.get(), PROPERTIES));
    public static final RegistryObject<Item> NETHER_BRICKS_1_ITEM = ITEMS.register("c1_nether_bricks", () -> new BlockItem(NETHER_BRICKS_1.get(), PROPERTIES));
    public static final RegistryObject<Item> NETHER_BRICKS_2_ITEM = ITEMS.register("c2_nether_bricks", () -> new BlockItem(NETHER_BRICKS_2.get(), PROPERTIES));
    public static final RegistryObject<Item> NETHER_BRICKS_3_ITEM = ITEMS.register("c3_nether_bricks", () -> new BlockItem(NETHER_BRICKS_3.get(), PROPERTIES));
    public static final RegistryObject<Item> NETHER_BRICKS_4_ITEM = ITEMS.register("c4_nether_bricks", () -> new BlockItem(NETHER_BRICKS_4.get(), PROPERTIES));
    public static final RegistryObject<Item> NETHER_BRICKS_5_ITEM = ITEMS.register("c5_nether_bricks", () -> new BlockItem(NETHER_BRICKS_5.get(), PROPERTIES));
    public static final RegistryObject<Item> NETHER_BRICKS_6_ITEM = ITEMS.register("c6_nether_bricks", () -> new BlockItem(NETHER_BRICKS_6.get(), PROPERTIES));
    public static final RegistryObject<Item> NETHER_BRICKS_7_ITEM = ITEMS.register("c7_nether_bricks", () -> new BlockItem(NETHER_BRICKS_7.get(), PROPERTIES));
    public static final RegistryObject<Item> NETHER_BRICKS_8_ITEM = ITEMS.register("c8_nether_bricks", () -> new BlockItem(NETHER_BRICKS_8.get(), PROPERTIES));
    public static final RegistryObject<Item> NETHER_BRICKS_9_ITEM = ITEMS.register("c9_nether_bricks", () -> new BlockItem(NETHER_BRICKS_9.get(), PROPERTIES));
    public static final RegistryObject<Item> RED_NETHER_BRICKS_0_ITEM = ITEMS.register("c0_red_nether_bricks", () -> new BlockItem(RED_NETHER_BRICKS_0.get(), PROPERTIES));
    public static final RegistryObject<Item> RED_NETHER_BRICKS_1_ITEM = ITEMS.register("c1_red_nether_bricks", () -> new BlockItem(RED_NETHER_BRICKS_1.get(), PROPERTIES));
    public static final RegistryObject<Item> RED_NETHER_BRICKS_2_ITEM = ITEMS.register("c2_red_nether_bricks", () -> new BlockItem(RED_NETHER_BRICKS_2.get(), PROPERTIES));
    public static final RegistryObject<Item> RED_NETHER_BRICKS_3_ITEM = ITEMS.register("c3_red_nether_bricks", () -> new BlockItem(RED_NETHER_BRICKS_3.get(), PROPERTIES));
    public static final RegistryObject<Item> RED_NETHER_BRICKS_4_ITEM = ITEMS.register("c4_red_nether_bricks", () -> new BlockItem(RED_NETHER_BRICKS_4.get(), PROPERTIES));
    public static final RegistryObject<Item> RED_NETHER_BRICKS_5_ITEM = ITEMS.register("c5_red_nether_bricks", () -> new BlockItem(RED_NETHER_BRICKS_5.get(), PROPERTIES));
    public static final RegistryObject<Item> RED_NETHER_BRICKS_6_ITEM = ITEMS.register("c6_red_nether_bricks", () -> new BlockItem(RED_NETHER_BRICKS_6.get(), PROPERTIES));
    public static final RegistryObject<Item> RED_NETHER_BRICKS_7_ITEM = ITEMS.register("c7_red_nether_bricks", () -> new BlockItem(RED_NETHER_BRICKS_7.get(), PROPERTIES));
    public static final RegistryObject<Item> RED_NETHER_BRICKS_8_ITEM = ITEMS.register("c8_red_nether_bricks", () -> new BlockItem(RED_NETHER_BRICKS_8.get(), PROPERTIES));
    public static final RegistryObject<Item> RED_NETHER_BRICKS_9_ITEM = ITEMS.register("c9_red_nether_bricks", () -> new BlockItem(RED_NETHER_BRICKS_9.get(), PROPERTIES));
    public static final RegistryObject<Item> NETHER_WART_BLOCK_0_ITEM = ITEMS.register("c0_nether_wart_block", () -> new BlockItem(NETHER_WART_BLOCK_0.get(), PROPERTIES));
    public static final RegistryObject<Item> NETHER_WART_BLOCK_1_ITEM = ITEMS.register("c1_nether_wart_block", () -> new BlockItem(NETHER_WART_BLOCK_1.get(), PROPERTIES));
    public static final RegistryObject<Item> NETHER_WART_BLOCK_2_ITEM = ITEMS.register("c2_nether_wart_block", () -> new BlockItem(NETHER_WART_BLOCK_2.get(), PROPERTIES));
    public static final RegistryObject<Item> NETHER_WART_BLOCK_3_ITEM = ITEMS.register("c3_nether_wart_block", () -> new BlockItem(NETHER_WART_BLOCK_3.get(), PROPERTIES));
    public static final RegistryObject<Item> NETHER_WART_BLOCK_4_ITEM = ITEMS.register("c4_nether_wart_block", () -> new BlockItem(NETHER_WART_BLOCK_4.get(), PROPERTIES));
    public static final RegistryObject<Item> NETHER_WART_BLOCK_5_ITEM = ITEMS.register("c5_nether_wart_block", () -> new BlockItem(NETHER_WART_BLOCK_5.get(), PROPERTIES));
    public static final RegistryObject<Item> NETHER_WART_BLOCK_6_ITEM = ITEMS.register("c6_nether_wart_block", () -> new BlockItem(NETHER_WART_BLOCK_6.get(), PROPERTIES));
    public static final RegistryObject<Item> NETHER_WART_BLOCK_7_ITEM = ITEMS.register("c7_nether_wart_block", () -> new BlockItem(NETHER_WART_BLOCK_7.get(), PROPERTIES));
    public static final RegistryObject<Item> NETHER_WART_BLOCK_8_ITEM = ITEMS.register("c8_nether_wart_block", () -> new BlockItem(NETHER_WART_BLOCK_8.get(), PROPERTIES));
    public static final RegistryObject<Item> NETHER_WART_BLOCK_9_ITEM = ITEMS.register("c9_nether_wart_block", () -> new BlockItem(NETHER_WART_BLOCK_9.get(), PROPERTIES));
    public static final RegistryObject<Item> SOUL_SAND_0_ITEM = ITEMS.register("c0_soul_sand", () -> new BlockItem(SOUL_SAND_0.get(), PROPERTIES));
    public static final RegistryObject<Item> SOUL_SAND_1_ITEM = ITEMS.register("c1_soul_sand", () -> new BlockItem(SOUL_SAND_1.get(), PROPERTIES));
    public static final RegistryObject<Item> SOUL_SAND_2_ITEM = ITEMS.register("c2_soul_sand", () -> new BlockItem(SOUL_SAND_2.get(), PROPERTIES));
    public static final RegistryObject<Item> SOUL_SAND_3_ITEM = ITEMS.register("c3_soul_sand", () -> new BlockItem(SOUL_SAND_3.get(), PROPERTIES));
    public static final RegistryObject<Item> SOUL_SAND_4_ITEM = ITEMS.register("c4_soul_sand", () -> new BlockItem(SOUL_SAND_4.get(), PROPERTIES));
    public static final RegistryObject<Item> SOUL_SAND_5_ITEM = ITEMS.register("c5_soul_sand", () -> new BlockItem(SOUL_SAND_5.get(), PROPERTIES));
    public static final RegistryObject<Item> SOUL_SAND_6_ITEM = ITEMS.register("c6_soul_sand", () -> new BlockItem(SOUL_SAND_6.get(), PROPERTIES));
    public static final RegistryObject<Item> SOUL_SAND_7_ITEM = ITEMS.register("c7_soul_sand", () -> new BlockItem(SOUL_SAND_7.get(), PROPERTIES));
    public static final RegistryObject<Item> SOUL_SAND_8_ITEM = ITEMS.register("c8_soul_sand", () -> new BlockItem(SOUL_SAND_8.get(), PROPERTIES));
    public static final RegistryObject<Item> SOUL_SAND_9_ITEM = ITEMS.register("c9_soul_sand", () -> new BlockItem(SOUL_SAND_9.get(), PROPERTIES));
    public static final RegistryObject<Item> SOUL_SOIL_0_ITEM = ITEMS.register("c0_soul_soil", () -> new BlockItem(SOUL_SOIL_0.get(), PROPERTIES));
    public static final RegistryObject<Item> SOUL_SOIL_1_ITEM = ITEMS.register("c1_soul_soil", () -> new BlockItem(SOUL_SOIL_1.get(), PROPERTIES));
    public static final RegistryObject<Item> SOUL_SOIL_2_ITEM = ITEMS.register("c2_soul_soil", () -> new BlockItem(SOUL_SOIL_2.get(), PROPERTIES));
    public static final RegistryObject<Item> SOUL_SOIL_3_ITEM = ITEMS.register("c3_soul_soil", () -> new BlockItem(SOUL_SOIL_3.get(), PROPERTIES));
    public static final RegistryObject<Item> SOUL_SOIL_4_ITEM = ITEMS.register("c4_soul_soil", () -> new BlockItem(SOUL_SOIL_4.get(), PROPERTIES));
    public static final RegistryObject<Item> SOUL_SOIL_5_ITEM = ITEMS.register("c5_soul_soil", () -> new BlockItem(SOUL_SOIL_5.get(), PROPERTIES));
    public static final RegistryObject<Item> SOUL_SOIL_6_ITEM = ITEMS.register("c6_soul_soil", () -> new BlockItem(SOUL_SOIL_6.get(), PROPERTIES));
    public static final RegistryObject<Item> SOUL_SOIL_7_ITEM = ITEMS.register("c7_soul_soil", () -> new BlockItem(SOUL_SOIL_7.get(), PROPERTIES));
    public static final RegistryObject<Item> SOUL_SOIL_8_ITEM = ITEMS.register("c8_soul_soil", () -> new BlockItem(SOUL_SOIL_8.get(), PROPERTIES));
    public static final RegistryObject<Item> SOUL_SOIL_9_ITEM = ITEMS.register("c9_soul_soil", () -> new BlockItem(SOUL_SOIL_9.get(), PROPERTIES));
    public static final RegistryObject<Item> END_STONE_0_ITEM = ITEMS.register("c0_end_stone", () -> new BlockItem(END_STONE_0.get(), PROPERTIES));
    public static final RegistryObject<Item> END_STONE_1_ITEM = ITEMS.register("c1_end_stone", () -> new BlockItem(END_STONE_1.get(), PROPERTIES));
    public static final RegistryObject<Item> END_STONE_2_ITEM = ITEMS.register("c2_end_stone", () -> new BlockItem(END_STONE_2.get(), PROPERTIES));
    public static final RegistryObject<Item> END_STONE_3_ITEM = ITEMS.register("c3_end_stone", () -> new BlockItem(END_STONE_3.get(), PROPERTIES));
    public static final RegistryObject<Item> END_STONE_4_ITEM = ITEMS.register("c4_end_stone", () -> new BlockItem(END_STONE_4.get(), PROPERTIES));
    public static final RegistryObject<Item> END_STONE_5_ITEM = ITEMS.register("c5_end_stone", () -> new BlockItem(END_STONE_5.get(), PROPERTIES));
    public static final RegistryObject<Item> END_STONE_6_ITEM = ITEMS.register("c6_end_stone", () -> new BlockItem(END_STONE_6.get(), PROPERTIES));
    public static final RegistryObject<Item> END_STONE_7_ITEM = ITEMS.register("c7_end_stone", () -> new BlockItem(END_STONE_7.get(), PROPERTIES));
    public static final RegistryObject<Item> END_STONE_8_ITEM = ITEMS.register("c8_end_stone", () -> new BlockItem(END_STONE_8.get(), PROPERTIES));
    public static final RegistryObject<Item> END_STONE_9_ITEM = ITEMS.register("c9_end_stone", () -> new BlockItem(END_STONE_9.get(), PROPERTIES));
    public static final RegistryObject<Item> END_STONE_BRICKS_0_ITEM = ITEMS.register("c0_end_stone_bricks", () -> new BlockItem(END_STONE_BRICKS_0.get(), PROPERTIES));
    public static final RegistryObject<Item> END_STONE_BRICKS_1_ITEM = ITEMS.register("c1_end_stone_bricks", () -> new BlockItem(END_STONE_BRICKS_1.get(), PROPERTIES));
    public static final RegistryObject<Item> END_STONE_BRICKS_2_ITEM = ITEMS.register("c2_end_stone_bricks", () -> new BlockItem(END_STONE_BRICKS_2.get(), PROPERTIES));
    public static final RegistryObject<Item> END_STONE_BRICKS_3_ITEM = ITEMS.register("c3_end_stone_bricks", () -> new BlockItem(END_STONE_BRICKS_3.get(), PROPERTIES));
    public static final RegistryObject<Item> END_STONE_BRICKS_4_ITEM = ITEMS.register("c4_end_stone_bricks", () -> new BlockItem(END_STONE_BRICKS_4.get(), PROPERTIES));
    public static final RegistryObject<Item> END_STONE_BRICKS_5_ITEM = ITEMS.register("c5_end_stone_bricks", () -> new BlockItem(END_STONE_BRICKS_5.get(), PROPERTIES));
    public static final RegistryObject<Item> END_STONE_BRICKS_6_ITEM = ITEMS.register("c6_end_stone_bricks", () -> new BlockItem(END_STONE_BRICKS_6.get(), PROPERTIES));
    public static final RegistryObject<Item> END_STONE_BRICKS_7_ITEM = ITEMS.register("c7_end_stone_bricks", () -> new BlockItem(END_STONE_BRICKS_7.get(), PROPERTIES));
    public static final RegistryObject<Item> END_STONE_BRICKS_8_ITEM = ITEMS.register("c8_end_stone_bricks", () -> new BlockItem(END_STONE_BRICKS_8.get(), PROPERTIES));
    public static final RegistryObject<Item> END_STONE_BRICKS_9_ITEM = ITEMS.register("c9_end_stone_bricks", () -> new BlockItem(END_STONE_BRICKS_9.get(), PROPERTIES));
    public static final RegistryObject<Item> BLACKSTONE_0_ITEM = ITEMS.register("c0_blackstone", () -> new BlockItem(BLACKSTONE_0.get(), PROPERTIES));
    public static final RegistryObject<Item> BLACKSTONE_1_ITEM = ITEMS.register("c1_blackstone", () -> new BlockItem(BLACKSTONE_1.get(), PROPERTIES));
    public static final RegistryObject<Item> BLACKSTONE_2_ITEM = ITEMS.register("c2_blackstone", () -> new BlockItem(BLACKSTONE_2.get(), PROPERTIES));
    public static final RegistryObject<Item> BLACKSTONE_3_ITEM = ITEMS.register("c3_blackstone", () -> new BlockItem(BLACKSTONE_3.get(), PROPERTIES));
    public static final RegistryObject<Item> BLACKSTONE_4_ITEM = ITEMS.register("c4_blackstone", () -> new BlockItem(BLACKSTONE_4.get(), PROPERTIES));
    public static final RegistryObject<Item> BLACKSTONE_5_ITEM = ITEMS.register("c5_blackstone", () -> new BlockItem(BLACKSTONE_5.get(), PROPERTIES));
    public static final RegistryObject<Item> BLACKSTONE_6_ITEM = ITEMS.register("c6_blackstone", () -> new BlockItem(BLACKSTONE_6.get(), PROPERTIES));
    public static final RegistryObject<Item> BLACKSTONE_7_ITEM = ITEMS.register("c7_blackstone", () -> new BlockItem(BLACKSTONE_7.get(), PROPERTIES));
    public static final RegistryObject<Item> BLACKSTONE_8_ITEM = ITEMS.register("c8_blackstone", () -> new BlockItem(BLACKSTONE_8.get(), PROPERTIES));
    public static final RegistryObject<Item> BLACKSTONE_9_ITEM = ITEMS.register("c9_blackstone", () -> new BlockItem(BLACKSTONE_9.get(), PROPERTIES));
    public static final RegistryObject<Item> DEEPSLATE_0_ITEM = ITEMS.register("c0_deepslate", () -> new BlockItem(DEEPSLATE_0.get(), PROPERTIES));
    public static final RegistryObject<Item> DEEPSLATE_1_ITEM = ITEMS.register("c1_deepslate", () -> new BlockItem(DEEPSLATE_1.get(), PROPERTIES));
    public static final RegistryObject<Item> DEEPSLATE_2_ITEM = ITEMS.register("c2_deepslate", () -> new BlockItem(DEEPSLATE_2.get(), PROPERTIES));
    public static final RegistryObject<Item> DEEPSLATE_3_ITEM = ITEMS.register("c3_deepslate", () -> new BlockItem(DEEPSLATE_3.get(), PROPERTIES));
    public static final RegistryObject<Item> DEEPSLATE_4_ITEM = ITEMS.register("c4_deepslate", () -> new BlockItem(DEEPSLATE_4.get(), PROPERTIES));
    public static final RegistryObject<Item> DEEPSLATE_5_ITEM = ITEMS.register("c5_deepslate", () -> new BlockItem(DEEPSLATE_5.get(), PROPERTIES));
    public static final RegistryObject<Item> DEEPSLATE_6_ITEM = ITEMS.register("c6_deepslate", () -> new BlockItem(DEEPSLATE_6.get(), PROPERTIES));
    public static final RegistryObject<Item> DEEPSLATE_7_ITEM = ITEMS.register("c7_deepslate", () -> new BlockItem(DEEPSLATE_7.get(), PROPERTIES));
    public static final RegistryObject<Item> DEEPSLATE_8_ITEM = ITEMS.register("c8_deepslate", () -> new BlockItem(DEEPSLATE_8.get(), PROPERTIES));
    public static final RegistryObject<Item> DEEPSLATE_9_ITEM = ITEMS.register("c9_deepslate", () -> new BlockItem(DEEPSLATE_9.get(), PROPERTIES));

    public static final RegistryObject<Item> COBBLED_DEEPSLATE_0_ITEM = ITEMS.register("c0_cobbled_deepslate", () -> new BlockItem(COBBLED_DEEPSLATE_0.get(), PROPERTIES));
    public static final RegistryObject<Item> COBBLED_DEEPSLATE_1_ITEM = ITEMS.register("c1_cobbled_deepslate", () -> new BlockItem(COBBLED_DEEPSLATE_1.get(), PROPERTIES));
    public static final RegistryObject<Item> COBBLED_DEEPSLATE_2_ITEM = ITEMS.register("c2_cobbled_deepslate", () -> new BlockItem(COBBLED_DEEPSLATE_2.get(), PROPERTIES));
    public static final RegistryObject<Item> COBBLED_DEEPSLATE_3_ITEM = ITEMS.register("c3_cobbled_deepslate", () -> new BlockItem(COBBLED_DEEPSLATE_3.get(), PROPERTIES));
    public static final RegistryObject<Item> COBBLED_DEEPSLATE_4_ITEM = ITEMS.register("c4_cobbled_deepslate", () -> new BlockItem(COBBLED_DEEPSLATE_4.get(), PROPERTIES));
    public static final RegistryObject<Item> COBBLED_DEEPSLATE_5_ITEM = ITEMS.register("c5_cobbled_deepslate", () -> new BlockItem(COBBLED_DEEPSLATE_5.get(), PROPERTIES));
    public static final RegistryObject<Item> COBBLED_DEEPSLATE_6_ITEM = ITEMS.register("c6_cobbled_deepslate", () -> new BlockItem(COBBLED_DEEPSLATE_6.get(), PROPERTIES));
    public static final RegistryObject<Item> COBBLED_DEEPSLATE_7_ITEM = ITEMS.register("c7_cobbled_deepslate", () -> new BlockItem(COBBLED_DEEPSLATE_7.get(), PROPERTIES));
    public static final RegistryObject<Item> COBBLED_DEEPSLATE_8_ITEM = ITEMS.register("c8_cobbled_deepslate", () -> new BlockItem(COBBLED_DEEPSLATE_8.get(), PROPERTIES));
    public static final RegistryObject<Item> COBBLED_DEEPSLATE_9_ITEM = ITEMS.register("c9_cobbled_deepslate", () -> new BlockItem(COBBLED_DEEPSLATE_9.get(), PROPERTIES));
    public static final RegistryObject<Item> TUFF_0_ITEM = ITEMS.register("c0_tuff", () -> new BlockItem(TUFF_0.get(), PROPERTIES));
    public static final RegistryObject<Item> TUFF_1_ITEM = ITEMS.register("c1_tuff", () -> new BlockItem(TUFF_1.get(), PROPERTIES));
    public static final RegistryObject<Item> TUFF_2_ITEM = ITEMS.register("c2_tuff", () -> new BlockItem(TUFF_2.get(), PROPERTIES));
    public static final RegistryObject<Item> TUFF_3_ITEM = ITEMS.register("c3_tuff", () -> new BlockItem(TUFF_3.get(), PROPERTIES));
    public static final RegistryObject<Item> TUFF_4_ITEM = ITEMS.register("c4_tuff", () -> new BlockItem(TUFF_4.get(), PROPERTIES));
    public static final RegistryObject<Item> TUFF_5_ITEM = ITEMS.register("c5_tuff", () -> new BlockItem(TUFF_5.get(), PROPERTIES));
    public static final RegistryObject<Item> TUFF_6_ITEM = ITEMS.register("c6_tuff", () -> new BlockItem(TUFF_6.get(), PROPERTIES));
    public static final RegistryObject<Item> TUFF_7_ITEM = ITEMS.register("c7_tuff", () -> new BlockItem(TUFF_7.get(), PROPERTIES));
    public static final RegistryObject<Item> TUFF_8_ITEM = ITEMS.register("c8_tuff", () -> new BlockItem(TUFF_8.get(), PROPERTIES));
    public static final RegistryObject<Item> TUFF_9_ITEM = ITEMS.register("c9_tuff", () -> new BlockItem(TUFF_9.get(), PROPERTIES));
    public static final RegistryObject<Item> BASALT_0_ITEM = ITEMS.register("c0_basalt", () -> new BlockItem(BASALT_0.get(), PROPERTIES));
    public static final RegistryObject<Item> BASALT_1_ITEM = ITEMS.register("c1_basalt", () -> new BlockItem(BASALT_1.get(), PROPERTIES));
    public static final RegistryObject<Item> BASALT_2_ITEM = ITEMS.register("c2_basalt", () -> new BlockItem(BASALT_2.get(), PROPERTIES));
    public static final RegistryObject<Item> BASALT_3_ITEM = ITEMS.register("c3_basalt", () -> new BlockItem(BASALT_3.get(), PROPERTIES));
    public static final RegistryObject<Item> BASALT_4_ITEM = ITEMS.register("c4_basalt", () -> new BlockItem(BASALT_4.get(), PROPERTIES));
    public static final RegistryObject<Item> BASALT_5_ITEM = ITEMS.register("c5_basalt", () -> new BlockItem(BASALT_5.get(), PROPERTIES));
    public static final RegistryObject<Item> BASALT_6_ITEM = ITEMS.register("c6_basalt", () -> new BlockItem(BASALT_6.get(), PROPERTIES));
    public static final RegistryObject<Item> BASALT_7_ITEM = ITEMS.register("c7_basalt", () -> new BlockItem(BASALT_7.get(), PROPERTIES));
    public static final RegistryObject<Item> BASALT_8_ITEM = ITEMS.register("c8_basalt", () -> new BlockItem(BASALT_8.get(), PROPERTIES));
    public static final RegistryObject<Item> BASALT_9_ITEM = ITEMS.register("c9_basalt", () -> new BlockItem(BASALT_9.get(), PROPERTIES));

    // fixme: fix translations
    public static void populate() {
        // FOOD
        CRATE_ITEMS.add("apple");
        CRATE_ITEMS.add("mushroom_stew");
        CRATE_ITEMS.add("bread");
        CRATE_ITEMS.add("porkchop");
        CRATE_ITEMS.add("cooked_porkchop");
        CRATE_ITEMS.add("cod");
        CRATE_ITEMS.add("salmon");
        CRATE_ITEMS.add("tropical_fish");
        CRATE_ITEMS.add("pufferfish");
        CRATE_ITEMS.add("cooked_cod");
        CRATE_ITEMS.add("cooked_salmon");
        CRATE_ITEMS.add("cake");
        CRATE_ITEMS.add("cookie");
        CRATE_ITEMS.add("melon_slice");
        CRATE_ITEMS.add("melon_seeds");
        CRATE_ITEMS.add("dried_kelp");
        CRATE_ITEMS.add("beef");
        CRATE_ITEMS.add("cooked_beef");
        CRATE_ITEMS.add("chicken");
        CRATE_ITEMS.add("cooked_chicken");
        CRATE_ITEMS.add("rotten_flesh");
        CRATE_ITEMS.add("carrot");
        CRATE_ITEMS.add("potato");
        CRATE_ITEMS.add("baked_potato");
        CRATE_ITEMS.add("poisonous_potato");
        CRATE_ITEMS.add("pumpkin_pie");
        CRATE_ITEMS.add("rabbit");
        CRATE_ITEMS.add("cooked_rabbit");
        CRATE_ITEMS.add("rabbit_stew");
        CRATE_ITEMS.add("mutton");
        CRATE_ITEMS.add("cooked_mutton");
        CRATE_ITEMS.add("beetroot");
        CRATE_ITEMS.add("beetroot_seeds");
        CRATE_ITEMS.add("beetroot_soup");
        CRATE_ITEMS.add("sweet_berries");
        CRATE_ITEMS.add("glow_berries");
        CRATE_ITEMS.add("egg");
        CRATE_ITEMS.add("sugar_cane");
        CRATE_ITEMS.add("sugar");
        CRATE_ITEMS.add("pumpkin");
        CRATE_ITEMS.add("pumpkin_seeds");
        CRATE_ITEMS.add("wheat");
        CRATE_ITEMS.add("wheat_seeds");
        CRATE_ITEMS.add("cocoa_beans");
        // MOB LOOT
        CRATE_ITEMS.add("arrow");
        CRATE_ITEMS.add("spider_eye");
        CRATE_ITEMS.add("fermented_spider_eye");
        CRATE_ITEMS.add("blaze_rod");
        CRATE_ITEMS.add("blaze_powder");
        CRATE_ITEMS.add("magma_cream");
        CRATE_ITEMS.add("bone");
        CRATE_ITEMS.add("bone_meal");
        CRATE_ITEMS.add("ender_eye");
        CRATE_ITEMS.add("ender_pearl");
        CRATE_ITEMS.add("feather");
        CRATE_ITEMS.add("leather");
        CRATE_ITEMS.add("string");
        CRATE_ITEMS.add("ink_sac");
        CRATE_ITEMS.add("glow_ink_sac");
        // MISC
        CRATE_ITEMS.add("stick");
        CRATE_ITEMS.add("glass_bottle");
        CRATE_ITEMS.add("snowball");
        CRATE_ITEMS.add("paper");
        CRATE_ITEMS.add("flint");
        // SAPLINGS / NATURE
        CRATE_ITEMS.add("oak_sapling");
        CRATE_ITEMS.add("spruce_sapling");
        CRATE_ITEMS.add("birch_sapling");
        CRATE_ITEMS.add("jungle_sapling");
        CRATE_ITEMS.add("acacia_sapling");
        CRATE_ITEMS.add("dark_oak_sapling");
        CRATE_ITEMS.add("chorus_fruit");
        CRATE_ITEMS.add("seagrass");
        CRATE_ITEMS.add("kelp");
        CRATE_ITEMS.add("bamboo");
        CRATE_ITEMS.add("brown_mushroom");
        CRATE_ITEMS.add("red_mushroom");
        CRATE_ITEMS.add("crimson_fungus");
        CRATE_ITEMS.add("warped_fungus");
        CRATE_ITEMS.add("wither_rose");
        CRATE_ITEMS.add("nether_wart");

        APPLES.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.APPLE), ForgeRegistries.ITEMS));
        MUSHROOM_STEW.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.MUSHROOM_STEW), ForgeRegistries.ITEMS));
        BREAD.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.BREAD), ForgeRegistries.ITEMS));
        PORKCHOP.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.PORKCHOP), ForgeRegistries.ITEMS));
        COOKED_PORKCHOP.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.COOKED_PORKCHOP), ForgeRegistries.ITEMS));
        COD.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.COD), ForgeRegistries.ITEMS));
        SALMON.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.SALMON), ForgeRegistries.ITEMS));
        TROPICAL_FISH.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.TROPICAL_FISH), ForgeRegistries.ITEMS));
        PUFFERFISH.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.PUFFERFISH), ForgeRegistries.ITEMS));
        COOKED_COD.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.COOKED_COD), ForgeRegistries.ITEMS));
        COOKED_SALMON.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.COOKED_SALMON), ForgeRegistries.ITEMS));
        CAKES.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.CAKE), ForgeRegistries.ITEMS));
        COOKIES.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.COOKIE), ForgeRegistries.ITEMS));
        MELON_SLICES.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.MELON_SLICE), ForgeRegistries.ITEMS));
        MELON_SEEDS.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.MELON_SEEDS), ForgeRegistries.ITEMS));
        DRIED_KELP.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.DRIED_KELP), ForgeRegistries.ITEMS));
        BEEF.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.BEEF), ForgeRegistries.ITEMS));
        COOKED_BEEF.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.COOKED_BEEF), ForgeRegistries.ITEMS));
        CHICKEN.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.CHICKEN), ForgeRegistries.ITEMS));
        COOKED_CHICKEN.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.COOKED_CHICKEN), ForgeRegistries.ITEMS));
        ROTTEN_FLESH.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.ROTTEN_FLESH), ForgeRegistries.ITEMS));
        CARROTS.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.CARROT), ForgeRegistries.ITEMS));
        POTATOES.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.POTATO), ForgeRegistries.ITEMS));
        BAKED_POTATOES.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.BAKED_POTATO), ForgeRegistries.ITEMS));
        POISONOUS_POTATOES.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.POISONOUS_POTATO), ForgeRegistries.ITEMS));
        PUMPKIN_PIES.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.PUMPKIN_PIE), ForgeRegistries.ITEMS));
        RABBIT.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.RABBIT), ForgeRegistries.ITEMS));
        COOKED_RABBIT.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.COOKED_RABBIT), ForgeRegistries.ITEMS));
        RABBIT_STEW.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.RABBIT_STEW), ForgeRegistries.ITEMS));
        MUTTON.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.MUTTON), ForgeRegistries.ITEMS));
        COOKED_MUTTON.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.COOKED_MUTTON), ForgeRegistries.ITEMS));
        BEETROOT.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.BEETROOT), ForgeRegistries.ITEMS));
        BEETROOT_SEEDS.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.BEETROOT_SEEDS), ForgeRegistries.ITEMS));
        BEETROOT_SOUP.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.BEETROOT_SOUP), ForgeRegistries.ITEMS));
        SWEET_BERRIES.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.SWEET_BERRIES), ForgeRegistries.ITEMS));
        GLOW_BERRIES.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.GLOW_BERRIES), ForgeRegistries.ITEMS));
        EGGS.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.EGG), ForgeRegistries.ITEMS));
        SUGAR_CANES.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.SUGAR_CANE), ForgeRegistries.ITEMS));
        SUGAR.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.SUGAR), ForgeRegistries.ITEMS));
        PUMPKINS.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.PUMPKIN), ForgeRegistries.ITEMS));
        PUMPKIN_SEEDS.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.PUMPKIN_SEEDS), ForgeRegistries.ITEMS));
        WHEAT.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.WHEAT), ForgeRegistries.ITEMS));
        WHEAT_SEEDS.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.WHEAT_SEEDS), ForgeRegistries.ITEMS));
        COCOA_BEANS.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.COCOA_BEANS), ForgeRegistries.ITEMS));
        ARROWS.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.ARROW), ForgeRegistries.ITEMS));
        SPIDER_EYES.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.SPIDER_EYE), ForgeRegistries.ITEMS));
        FERMENTED_SPIDER_EYES.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.FERMENTED_SPIDER_EYE), ForgeRegistries.ITEMS));
        BLAZE_RODS.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.BLAZE_ROD), ForgeRegistries.ITEMS));
        BLAZE_POWDER.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.BLAZE_POWDER), ForgeRegistries.ITEMS));
        MAGMA_CREAM.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.MAGMA_CREAM), ForgeRegistries.ITEMS));
        BONES.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.BONE), ForgeRegistries.ITEMS));
        BONE_MEAL.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.BONE_MEAL), ForgeRegistries.ITEMS));
        ENDER_EYES.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.ENDER_EYE), ForgeRegistries.ITEMS));
        ENDER_PEARLS.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.ENDER_PEARL), ForgeRegistries.ITEMS));
        FEATHERS.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.FEATHER), ForgeRegistries.ITEMS));
        LEATHER.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.LEATHER), ForgeRegistries.ITEMS));
        STRINGS.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.STRING), ForgeRegistries.ITEMS));
        INK_SACS.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.INK_SAC), ForgeRegistries.ITEMS));
        GLOW_INK_SACS.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.GLOW_INK_SAC), ForgeRegistries.ITEMS));
        STICKS.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.STICK), ForgeRegistries.ITEMS));
        GLASS_BOTTLES.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.GLASS_BOTTLE), ForgeRegistries.ITEMS));
        SNOWBALLS.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.SNOWBALL), ForgeRegistries.ITEMS));
        PAPER.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.PAPER), ForgeRegistries.ITEMS));
        FLINTS.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.FLINT), ForgeRegistries.ITEMS));
        OAK_SAPLINGS.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.OAK_SAPLING), ForgeRegistries.ITEMS));
        SPRUCE_SAPLINGS.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.SPRUCE_SAPLING), ForgeRegistries.ITEMS));
        BIRCH_SAPLINGS.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.BIRCH_SAPLING), ForgeRegistries.ITEMS));
        JUNGLE_SAPLINGS.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.JUNGLE_SAPLING), ForgeRegistries.ITEMS));
        ACACIA_SAPLINGS.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.ACACIA_SAPLING), ForgeRegistries.ITEMS));
        DARK_OAK_SAPLINGS.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.DARK_OAK_SAPLING), ForgeRegistries.ITEMS));
        CHORUS_FRUITS.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.CHORUS_FRUIT), ForgeRegistries.ITEMS));
        SEAGRASS.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.SEAGRASS), ForgeRegistries.ITEMS));
        KELP.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.KELP), ForgeRegistries.ITEMS));
        BAMBOO.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.BAMBOO), ForgeRegistries.ITEMS));
        BROWN_MUSHROOMS.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.BROWN_MUSHROOM), ForgeRegistries.ITEMS));
        RED_MUSHROOMS.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.RED_MUSHROOM), ForgeRegistries.ITEMS));
        CRIMSON_FUNGUS.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.CRIMSON_FUNGUS), ForgeRegistries.ITEMS));
        WARPED_FUNGUS.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.WARPED_FUNGUS), ForgeRegistries.ITEMS));
        WITHER_ROSES.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.WITHER_ROSE.asItem()), ForgeRegistries.ITEMS));
        NETHER_WARTS.add(0, RegistryObject.create(StringUtils.resourceLocationFixer(Items.NETHER_WART), ForgeRegistries.ITEMS));
    }
}
