#file: noinspection SpellCheckingInspection

name: publish
run-name: ${{ github.ref_name }}

on:
  workflow_dispatch:
  push:
    branches:
      - "1.20.1"
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: windows-latest
    env:
      JAVA_VERSION: 17
      MINECRAFT_VERSIONS: |
        1.20.1
      ACT: ${{ vars.ACT }}
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v7

      - name: "Cache Gradle packages"
        uses: actions/cache@v6
        id: cache-gradle
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: "${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}"
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: "Read gradle.properties and set variables (Windows)"
        shell: pwsh
        run: |
          $properties = Get-Content -Path gradle.properties -Raw | ConvertFrom-StringData
          foreach ($key in $properties.Keys) {
            $value = $properties[$key]
            if ($key.StartsWith('#') -or [string]::IsNullOrEmpty($key)) {
              continue
            }
            if ($value.Contains('|')) {
              $value = $value.Trim('[]').Replace(' ', '')
              $array = $value.Split('|')
              $value = $array -join "`n"
            }
            "$key<<EOF" >> $env:GITHUB_ENV
            "$value" >> $env:GITHUB_ENV
            "EOF" >> $env:GITHUB_ENV
          }

      - name: "Validate gradle wrapper"
        uses: gradle/actions/wrapper-validation@v6

      - name: "Setup jdk ${{ env.JAVA_VERSION }}"
        uses: actions/setup-java@v6
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'

      - name: "Run gradle task: fabric:datagen"
        run: ./gradlew :fabric:runDatagen

      - name: "Build project"
        run: ./gradlew build

      - name: "Capture build artifacts"
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v7
        with:
          name: Artifacts
          path: |
            forge/build/libs/
            neoforge/build/libs/
            fabric/build/libs/
          if-no-files-found: error

      # Not using a matrix here because files should be uploaded in a specific order (forge -> neoforge -> fabric)
      - name: "Publish FORGE"
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: ${{ env.modrinth_id }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-featured: true
          modrinth-unfeature-mode: intersection

          curseforge-id: ${{ env.curseforge_id }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          files: |
            forge/build/libs/!(*-@(dev|sources|javadoc)).jar

          name: "v${{ env.version }} (${{ env.minecraft_version }}) FORGE"
          version: "${{ env.version }}"
          version-type: "${{ env.version_type }}"
          changelog-file: changelog.md

          loaders: |
            forge
          game-versions: ${{ env.MINECRAFT_VERSIONS }}

          java: ${{ env.JAVA_VERSION }}

          retry-attempts: 2
          retry-delay: 10000
          fail-mode: fail

      - name: "Publish NEOFORGE"
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: ${{ env.modrinth_id }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-featured: true
          modrinth-unfeature-mode: intersection

          curseforge-id: ${{ env.curseforge_id }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          files: |
            neoforge/build/libs/!(*-@(dev|sources|javadoc)).jar

          name: "v${{ env.version }} (${{ env.minecraft_version }}) NEOFORGE"
          version: "${{ env.version }}"
          version-type: "${{ env.version_type }}"
          changelog-file: changelog.md

          loaders: |
            neoforge
          game-versions: ${{ env.MINECRAFT_VERSIONS }}
          dependencies: |
            forgeconfigapiport(optional){modrinth:ohNO6lps}{curseforge:547434}

          java: ${{ env.JAVA_VERSION }}

          retry-attempts: 2
          retry-delay: 10000
          fail-mode: fail

      - name: "Publish FABRIC"
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: ${{ env.modrinth_id }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-featured: true
          modrinth-unfeature-mode: intersection

          curseforge-id: ${{ env.curseforge_id }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          files: |
            fabric/build/libs/!(*-@(dev|sources|javadoc)).jar

          name: "v${{ env.version }} (${{ env.minecraft_version }}) FABRIC"
          version: "${{ env.version }}"
          version-type: "${{ env.version_type }}"
          changelog-file: changelog.md

          loaders: |
            fabric
          game-versions: ${{ env.MINECRAFT_VERSIONS }}
          dependencies: |
            fabric-api{modrinth:P7dR8mSH}{curseforge:306612}
            forgeconfigapiport{modrinth:ohNO6lps}{curseforge:547434}
            modmenu(optional){modrinth:mOgUt4GM}{curseforge:308702}

          java: ${{ env.JAVA_VERSION }}

          retry-attempts: 2
          retry-delay: 10000
          fail-mode: fail

      - name: "Prepare Discord announcement"
        shell: pwsh
        env:
          DISCORD_ROLE_ID: ${{ secrets.DISCORD_ANNOUNCEMENT_ROLE_ID }}
        run: |
          $changelog = Get-Content changelog.md -Raw

          $payload = @{
            content = "<@&$($env:DISCORD_ROLE_ID)>`n`n$changelog"
          } | ConvertTo-Json -Depth 10

          $payload | Out-File discord.json -Encoding utf8

      - name: "Discord Webhook"
        shell: pwsh
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          Invoke-RestMethod `
            -Uri $env:DISCORD_WEBHOOK_URL `
            -Method Post `
            -ContentType "application/json" `
            -Body (Get-Content discord.json -Raw)